Repository finos/perspective, pull requests merged in 2019-05, with the labels that each got.

#559 Fixed docs links
  README.md
Labels: cla-present

#561 Correctly read and generate boolean values for Arrow format
  cpp/perspective/src/cpp/emscripten.cpp
  packages/perspective/src/js/perspective.js
  packages/perspective/test/arrow/bool.arrow
  packages/perspective/test/arrow/partial.arrow
  packages/perspective/test/arrow/partial_missing_rows.arrow
  packages/perspective/test/js/multiple.js
  packages/perspective/test/js/perspective.spec.js
  packages/perspective/test/js/to_format.js
  packages/perspective/test/js/updates.js
Labels: cla-present

#563 D3 Treemaps
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/html/parent-controls.html
  packages/perspective-viewer-d3fc/src/html/zoom-controls.html
  packages/perspective-viewer-d3fc/src/js/axis/axisFactory.js
  packages/perspective-viewer-d3fc/src/js/charts/charts.js
  packages/perspective-viewer-d3fc/src/js/charts/ohlcCandle.js
  packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
  packages/perspective-viewer-d3fc/src/js/charts/treemap.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/data/heatmapData.js
  packages/perspective-viewer-d3fc/src/js/data/treeData.js
  packages/perspective-viewer-d3fc/src/js/layout/gridLayoutMultiChart.js
  packages/perspective-viewer-d3fc/src/js/legend/scrollableLegend.js
  packages/perspective-viewer-d3fc/src/js/legend/styling/draggableComponent.js
  packages/perspective-viewer-d3fc/src/js/legend/styling/resizableComponent.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
  packages/perspective-viewer-d3fc/src/js/series/seriesRange.js
  packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstColor.js
  packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstSeries.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapColor.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapControls.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLabel.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLayout.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLevelCalculation.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapTransitions.js
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
  packages/perspective-viewer-d3fc/src/js/tooltip/tooltip.js
  packages/perspective-viewer-d3fc/src/js/utils/utils.js
  packages/perspective-viewer-d3fc/src/js/zoom/zoomableChart.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/js/unit/data/findBest.spec.js
  packages/perspective-viewer-d3fc/test/js/unit/data/testTreeData.js
  packages/perspective-viewer-d3fc/test/js/unit/data/treeData.spec.js
  packages/perspective-viewer-d3fc/test/js/unit/series/colorStyles.spec.js
  packages/perspective-viewer-d3fc/test/js/unit/series/seriesRange.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer/src/themes/material.dark.less
  yarn.lock
Labels: JS, cla-present, enhancement

#570 JupyterLab enhancements
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-viewer/index.d.ts
Labels: Jupyter, cla-present, enhancement

#571 Refactor Javascript API +add documentation
  docs/md/usage.md
  packages/perspective/src/js/API/dispatch.js
  packages/perspective/src/js/API/host.js
  packages/perspective/src/js/API/table_api.js
  packages/perspective/src/js/API/view_api.js
  packages/perspective/src/js/API/worker.js
  packages/perspective/src/js/api.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
  packages/perspective/src/js/utils.js
Labels: cla-present

#573 Fix the format of long numbers
  packages/perspective-viewer-d3fc/src/js/axis/axisFactory.js
  packages/perspective-viewer-d3fc/src/js/axis/chartFactory.js
  packages/perspective-viewer-d3fc/src/js/axis/linearAxis.js
  packages/perspective-viewer-d3fc/src/js/axis/valueFormatter.js
  packages/perspective-viewer-d3fc/src/js/legend/colorRangeLegend.js
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: cla-present

#574 Performance overhaul for `table.update()`
  cmake/hopscotch.txt.in
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/column.cpp
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/cpp/sym_table.cpp
  cpp/perspective/src/cpp/tracing.cpp
  cpp/perspective/src/cpp/tracing_impl_linux.cpp
  cpp/perspective/src/cpp/tracing_impl_osx.cpp
  cpp/perspective/src/cpp/tree_context_common.cpp
  cpp/perspective/src/cpp/vocab.cpp
  cpp/perspective/src/include/perspective/column.h
  cpp/perspective/src/include/perspective/flat_traversal.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/scalar.h
  cpp/perspective/src/include/perspective/sym_table.h
  cpp/perspective/src/include/perspective/vocab.h
  packages/perspective/bench/js/bench.js
  packages/perspective/bench/js/browser_runtime.js
  packages/perspective/src/js/perspective.js
  scripts/test.js
Labels: cla-present

#575 UX fixes
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/test/results/results.json
Labels: cla-present

#576 Fixed grid styling
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
Labels: cla-present

#564 Feature/dual y axis POC
  packages/perspective-viewer-d3fc/src/js/axis/axisSplitter.js
  packages/perspective-viewer-d3fc/src/js/axis/chartFactory.js
  packages/perspective-viewer-d3fc/src/js/axis/splitterLabels.js
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/js/tooltip/nearbyTip.js
  packages/perspective-viewer-d3fc/src/js/zoom/zoomableChart.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: JS, cla-present, enhancement

#578 add restyle to type definitions, fix dark mode in jlab, fix CSS issue
  packages/perspective-phosphor/src/less/index.less
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-viewer/index.d.ts
Labels: JS, Jupyter, cla-present, enhancement

#580 Undo condensed column layout when width < 600px
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/test/js/responsive_tests.js
  packages/perspective-viewer/test/results/results.json
Labels: cla-present

#582 Row delta supports addition, delete, non-contiguous updates
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/step_delta.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/context_common_decls.h
  cpp/perspective/src/include/perspective/context_zero.h
  cpp/perspective/src/include/perspective/flat_traversal.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/step_delta.h
  cpp/perspective/src/include/perspective/view.h
  packages/perspective/bench/js/bench.js
  packages/perspective/bench/js/browser_runtime.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/delta.js
  packages/perspective/test/js/updates.js
Labels: cla-present

#583 Fixed tooltip value when split_values and multiple main values
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
Labels: JS, cla-present, enhancement

#584 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-present, documentation

#587 Port to Webpack 4
  package.json
  packages/perspective-phosphor/src/less/index.less
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer/src/config/themes.config.js
  packages/perspective-webpack-plugin/package.json
  packages/perspective-webpack-plugin/src/js/psp-worker-compiler-loader.js
  packages/perspective/src/config/common.config.js
  packages/perspective/src/config/perspective.config.js
  packages/perspective/src/config/perspective.node.config.js
  yarn.lock
Labels: cla-present

#588 New benchmark suite
  package.json
  packages/perspective-bench/bench/perspective.benchmark.js
  packages/perspective-bench/bench/versions.js
  packages/perspective-bench/package.json
  packages/perspective-bench/perspective-bench
  packages/perspective-bench/src/html/benchmark.html
  packages/perspective-bench/src/js/bench.js
  packages/perspective-bench/src/js/browser_runtime.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective/bench/js/bench.js
  packages/perspective/bench/js/browser_runtime.js
  packages/perspective/package.json
  packages/perspective/src/config/common.config.js
  packages/perspective/src/config/perspective.config.js
  packages/perspective/src/config/perspective.node.config.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
  scripts/bench.js
Labels: cla-present

#590 Fix for webpack 4 themes generation error on Windows
  packages/perspective-viewer/src/config/themes.config.js
Labels: cla-present

#589 Row deltas return arrow-serialized data
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_slice.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/step_delta.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/context_common_decls.h
  cpp/perspective/src/include/perspective/data_slice.h
  cpp/perspective/src/include/perspective/flat_traversal.h
  cpp/perspective/src/include/perspective/step_delta.h
  cpp/perspective/src/include/perspective/view.h
  packages/perspective/src/js/API/host.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/delta.js
  packages/perspective/test/js/to_format.js
Labels: cla-present

#591 A few quality-of-life improvements for perspective-phosphor
  packages/perspective-phosphor/src/ts/widget.ts
Labels: JS, cla-present, enhancement

#594 Row delta fixes
  examples/remote/index.css
  examples/remote/index.html
  examples/remote/package.json
  examples/remote/server.js
  package.json
  packages/perspective-bench/src/html/benchmark.html
  packages/perspective/package.json
  packages/perspective/src/js/API/host.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
  yarn.lock
Labels: cla-present

#595 Fixed D3FC heatmap color for Material dark theme.
  packages/perspective-viewer/src/themes/material.dark.less
Labels: cla-present

#596 simplify python setup.py, add psp_test to python tests
  cpp/perspective/CMakeLists.txt
  cpp/perspective/test/CMakeLists.txt
  python/table/.gitignore
  python/table/setup.cfg
  python/table/setup.py
Labels: Python, cla-present

#599 D3FC Default Plugin
  README.md
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_slice.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/step_delta.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/data_slice.h
  cpp/perspective/src/include/perspective/step_delta.h
  docs/i18n/en.json
  docs/md/installation.md
  docs/md/usage.md
  docs/pages/en/help.js
  docs/pages/en/index.js
  docs/pages/en/users.js
  docs/siteConfig.js
  docs/static/css/custom.css
  docs/static/css/material.dark.css
  docs/static/css/material.dark.less
  docs/static/js/animation.js
  examples/git_history/chained.html
  examples/git_history/index.html
  examples/git_history/package.json
  examples/remote/index.html
  examples/remote/package.json
  examples/remote/server.js
  examples/simple/citibike.html
  examples/simple/csv.html
  examples/simple/linked.html
  examples/simple/package.json
  examples/simple/streaming.html
  examples/simple/superstore-arrow.html
  examples/webpack/index.js
  examples/webpack/package.json
  packages/perspective-bench/package.json
  packages/perspective-bench/src/html/benchmark.html
  packages/perspective-cli/package.json
  packages/perspective-cli/src/html/index.html
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/js/data/transposeData.js
  packages/perspective-viewer-d3fc/src/js/series/colorStyles.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLayout.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-highcharts/src/js/highcharts/color_axis.js
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective/bench/html/delta_benchmark.html
  packages/perspective/package.json
  packages/perspective/src/js/API/host.js
  packages/perspective/src/js/API/worker.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/test/js/sort.js
  yarn.lock
Labels: cla-present

#600 Clean up API names
  examples/git_history/chained.html
  examples/git_history/index.html
  examples/git_history/server.js
  examples/remote/index.html
  examples/remote/server.js
  examples/simple/server.js
  examples/simple/superstore-d3fc.html
  packages/perspective-bench/src/js/bench.js
  packages/perspective-cli/src/js/index.js
  packages/perspective-viewer/test/js/utils.js
  packages/perspective/README.md
  packages/perspective/bench/html/delta_benchmark.html
  packages/perspective/src/js/API/client.js
  packages/perspective/src/js/API/server.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
Labels: cla-present

#603 Replace atomic
  examples/git_history/server.js
  packages/perspective-bench/bench/versions.js
  packages/perspective/src/js/API/dispatch.js
  packages/perspective/src/js/API/server.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/html/benchmark.html
  packages/perspective/test/js/clear.js
  scripts/test.js
Labels: cla-present

#604 Replace "distinct count" default aggregate with "count"
  cpp/perspective/src/cpp/base.cpp
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/test/results/results.json
  packages/perspective/src/js/defaults.js
  packages/perspective/test/js/delta.js
  packages/perspective/test/js/pivots.js
Labels: cla-present
