Repository finos/perspective, pull requests merged in 2019-01, with the labels that each got.

#371 reorganize cpp test directory for better organization
  test/CMakeLists.txt
  test/cpp/psp.cpp
  test/cpp/simple.cpp
  test/include/perspective/test_utils.h
Labels: C++, enhancement

#373 Fixes local cpp build -> need to cd into build dir (not needed on docker, working dir is set)
  scripts/build_cpp.js
Labels: C++, bug

#374 remove boost::format
  src/cpp/main.cpp
Labels: C++, JS, enhancement

#375 Invalid filters
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/src/html/row.html
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/js/viewer/state_element.js
  packages/perspective-viewer/src/less/column_labels.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/test/js/simple_tests.js
  packages/perspective-viewer/test/results/results.json
  packages/perspective/src/js/api.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/filters.js
Labels: JS, enhancement

#381 Interoperability between CMAKE_BUILD_TYPE and PSP_DEBUG
  CMakeLists.txt
  scripts/build.js
  scripts/build_cpp.js
  scripts/build_python.js
  scripts/lint_python.js
  scripts/test.js
  scripts/test_cpp.js
  scripts/test_python.js
Labels: C++, enhancement

#390 Remove cross /src imports in packages
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-highcharts/src/js/draw.js
  packages/perspective-viewer-highcharts/src/js/series.js
  packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer/dragdrop.js
  packages/perspective/package.json
  packages/perspective/src/js/utils.js
  yarn.lock
Labels: JS

#389 [WIP] Merging JS and Python binding code - Part 2
  CMakeLists.txt
  python/perspective/include/perspective/binding.h
  python/perspective/include/perspective/numpy.h
  python/perspective/include/perspective/python.h
  python/perspective/src/binding.cpp
  python/perspective/src/python.cpp
  python/perspective/table/__init__.py
  python/perspective/tests/test_column.py
  python/perspective/tests/test_gnode.py
  python/perspective/tests/test_schema.py
  src/cpp/binding.cpp
  src/cpp/emscripten.cpp
  src/cpp/main.cpp
  src/cpp/pool.cpp
  src/include/perspective/binding.h
  src/include/perspective/emscripten.h
  src/include/perspective/pool.h
Labels: C++, JS, Python

#394 Websocket heartbeat detection
  packages/perspective/package.json
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
Labels: JS

#391 Output CJS module bundles for perspective-viewer packages
  .gitignore
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-highcharts/src/config/highcharts.plugin.cjs.config.js
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer-hypergrid/src/config/hypergrid.plugin.cjs.config.js
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/config/view.cjs.config.js
Labels: JS

#393 Update Webpack example to webpack 4
  examples/webpack/in.js
  examples/webpack/package.json
  examples/webpack/webpack.config.js
  package.json
  yarn.lock
Labels: JS

#392 Output CJS files perspective package
  package.json
  packages/perspective/babel.config.js
  packages/perspective/package.json
  packages/perspective/src/config/perspective.config.js
  packages/perspective/src/config/perspective.node.config.js
  packages/perspective/src/loader/cross_origin_file_loader.js
  packages/perspective/src/loader/file_worker_loader.js
  yarn.lock
Labels: JS

#387 Empty filters
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/filters.js
Labels: JS

#402 expand os for c++ testing
  .appveyor.yml
  .travis.yml
  CMakeLists.txt
  cmake/TBB.txt.in
  scripts/test_python.js
  src/cpp/base.cpp
  src/cpp/compat_impl_win.cpp
  src/cpp/context_grouped_pkey.cpp
  src/cpp/sparse_tree.cpp
  src/cpp/storage_impl_win.cpp
  src/include/perspective/base.h
  src/include/perspective/context_common_decls.h
  src/include/perspective/context_grouped_pkey.h
  src/include/perspective/first.h
  src/include/perspective/table.h
  test/CMakeLists.txt
  test/cpp/psp.cpp
  test/cpp/simple.cpp
  test/include/perspective/simple.h
  test/include/perspective/test_utils.h
Labels: C++
