Repository finos/perspective, pull requests merged in 2019-03, with the labels that each got.

#458 Integration tests for D3FC
  packages/perspective-viewer-d3fc/src/js/tooltip/tooltip.js
  packages/perspective-viewer-d3fc/test/html/line.html
  packages/perspective-viewer-d3fc/test/html/scatter.html
  packages/perspective-viewer-d3fc/test/js/bar.spec.js
  packages/perspective-viewer-d3fc/test/js/line.spec.js
  packages/perspective-viewer-d3fc/test/js/scatter.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: in progress

#464 Add perspective click to usage
  docs/perspective-viewer.md
  docs/perspective.md
  docs/usage.md
  packages/perspective-viewer/README.md
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective/README.md
Labels: in progress

#465 Updated README
  README.md
Labels: in progress

#468 Ported Javascript build, test and clean tasks to Windows
  .travis.yml
  package.json
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer/package.json
  packages/perspective-webpack-plugin/src/js/psp-worker-loader.js
  packages/perspective-webpack-plugin/src/js/wasm-loader.js
  packages/perspective/package.json
  scripts/build.js
  scripts/clean.js
  scripts/lint_cpp.js
  scripts/test.js
  yarn.lock
Labels: in progress

#469 Update remote API to accept a `perspective.table()`
  docs/usage.md
  examples/cli/server.js
  examples/git_history/server.js
  packages/perspective/src/js/perspective.node.js
Labels: in progress

#470 Fix for Juypterlab build->dist
  packages/perspective-jupyterlab/package.json
Labels: in progress

#471 CSV integer parse bug
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/constructors.js
Labels: in progress

#475 Added ‘not in’ filter to `perspective-viewer` defaults
  packages/perspective/src/js/defaults.js
Labels: in progress

#474 D3FC fixes
  package.json
  packages/perspective-viewer-d3fc/src/js/series/lineSeries.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeries.js
  packages/perspective-viewer-d3fc/src/js/series/seriesColours.js
  packages/perspective-viewer-d3fc/src/js/series/seriesLinearRange.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: in progress

#476 Fixed calls to `update()` with empty list from throwing exception
  packages/perspective/src/js/DataAccessor/DataAccessor.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/updates.js
Labels: in progress

#477 Fixed “not in” filter to array conversion in viewer
  packages/perspective-viewer/src/js/row.js
Labels: in progress

#473 Add t_data_slice for data output
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/config.cpp
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_slice.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/get_data_extents.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/config.h
  cpp/perspective/src/include/perspective/data_slice.h
  cpp/perspective/src/include/perspective/get_data_extents.h
  cpp/perspective/src/include/perspective/view.h
  packages/perspective/bench/js/bench.js
  packages/perspective/src/js/perspective.js
  python/perspective/src/python.cpp
Labels: in progress

#478 Date filter issue
  cpp/perspective/src/cpp/emscripten.cpp
  packages/perspective/test/js/filters.js
Labels: in progress

#481 Get version from package json: fixes #423
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/config/plugin.config.js
  packages/perspective-jupyterlab/src/ts/version.ts
  packages/perspective-jupyterlab/tsconfig.json
Labels: JS, Jupyter, enhancement

#479 d3fc plugin - Label rotation, interpolated legend, zooming, scatter chart things
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/html/zoom-controls.html
  packages/perspective-viewer-d3fc/src/js/axis/crossAxis.js
  packages/perspective-viewer-d3fc/src/js/charts/area.js
  packages/perspective-viewer-d3fc/src/js/charts/bar.js
  packages/perspective-viewer-d3fc/src/js/charts/charts.js
  packages/perspective-viewer-d3fc/src/js/charts/column.js
  packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter-canvas.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/charts/y-scatter.js
  packages/perspective-viewer-d3fc/src/js/d3fc/annotation/canvas/gridline.js
  packages/perspective-viewer-d3fc/src/js/d3fc/annotation/ticks.js
  packages/perspective-viewer-d3fc/src/js/d3fc/axis/axis.js
  packages/perspective-viewer-d3fc/src/js/d3fc/axis/multi-axis.js
  packages/perspective-viewer-d3fc/src/js/d3fc/chart/svg/cartesian.js
  packages/perspective-viewer-d3fc/src/js/d3fc/series/base.js
  packages/perspective-viewer-d3fc/src/js/d3fc/series/canvas/multi.js
  packages/perspective-viewer-d3fc/src/js/d3fc/series/multiBase.js
  packages/perspective-viewer-d3fc/src/js/data/groupAndStackData.js
  packages/perspective-viewer-d3fc/src/js/data/groupData.js
  packages/perspective-viewer-d3fc/src/js/data/pointData.js
  packages/perspective-viewer-d3fc/src/js/data/splitAndBaseData.js
  packages/perspective-viewer-d3fc/src/js/gridlines/gridlines.js
  packages/perspective-viewer-d3fc/src/js/legend/colorLegend.js
  packages/perspective-viewer-d3fc/src/js/legend/colourRangeLegend.js
  packages/perspective-viewer-d3fc/src/js/legend/filter.js
  packages/perspective-viewer-d3fc/src/js/legend/legend.js
  packages/perspective-viewer-d3fc/src/js/legend/scrollableLegend.js
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
  packages/perspective-viewer-d3fc/src/js/series/categoryPointSeries.js
  packages/perspective-viewer-d3fc/src/js/series/heatmapSeries.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeries.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
  packages/perspective-viewer-d3fc/src/js/series/seriesColours.js
  packages/perspective-viewer-d3fc/src/js/series/seriesRange.js
  packages/perspective-viewer-d3fc/src/js/series/seriesSymbols.js
  packages/perspective-viewer-d3fc/src/js/tooltip/generateHTML.js
  packages/perspective-viewer-d3fc/src/js/tooltip/tooltip.js
  packages/perspective-viewer-d3fc/src/js/zoom/zoomableChart.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/src/less/d3fc.less
  packages/perspective-viewer-d3fc/src/less/perspective-view.less
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer/src/themes/material.dark.less
  yarn.lock
Labels: JS, enhancement

#483 Implement t_data_slice API for data extraction from 0 & 1-sided views
  cpp/perspective/src/cpp/config.cpp
  cpp/perspective/src/cpp/data_slice.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/config.h
  cpp/perspective/src/include/perspective/data_slice.h
  cpp/perspective/src/include/perspective/view.h
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/to_format.js
Labels: in progress

#486 Fixed 0-sided schema
  cpp/perspective/src/cpp/view.cpp
  packages/perspective/test/js/constructors.js
Labels: in progress

#487 Fixed lint_cpp script
  scripts/lint_cpp.js
Labels: in progress

#485 Added window support to `to_arrow()`
  cpp/perspective/src/cpp/emscripten.cpp
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/to_format.js
Labels: in progress

#488 D3fc plugin - Basic OHLC and Candlestick charts
  examples/simple/FTSE100.csv
  examples/simple/index.html
  examples/simple/investing.ohlc.html
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/js/axis/crossAxis.js
  packages/perspective-viewer-d3fc/src/js/axis/mainAxis.js
  packages/perspective-viewer-d3fc/src/js/charts/candlestick.js
  packages/perspective-viewer-d3fc/src/js/charts/charts.js
  packages/perspective-viewer-d3fc/src/js/charts/ohlc.js
  packages/perspective-viewer-d3fc/src/js/charts/ohlcCandle.js
  packages/perspective-viewer-d3fc/src/js/d3fc/axis/axisOrdinal.js
  packages/perspective-viewer-d3fc/src/js/d3fc/axis/multi-axis.js
  packages/perspective-viewer-d3fc/src/js/d3fc/axis/store.js
  packages/perspective-viewer-d3fc/src/js/data/ohlcData.js
  packages/perspective-viewer-d3fc/src/js/series/seriesColors.js
  packages/perspective-viewer-d3fc/src/js/tooltip/generateHTML.js
  packages/perspective-viewer-d3fc/src/less/perspective-view.less
  packages/perspective-viewer-d3fc/test/results/results.json
  yarn.lock
Labels: JS, enhancement

#494 D3FC unit test
  package.json
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/test/js/beforeEachSpec.js
  packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
  packages/perspective-viewer-d3fc/test/js/transform.js
  packages/perspective-viewer-d3fc/test/js/unit/group_and_stack.spec.js
  yarn.lock
Labels: JS, tests
