Repository finos/perspective, pull requests merged in 2019-11, with the labels that each got.

#790 New logo & demo gif
  README.md
  docs/logo.config.js
  docs/logo.js
  docs/package.json
  docs/pages/en/index.js
  docs/siteConfig.js
  docs/static/css/custom.css
  docs/static/css/material.dark.css
  docs/static/js/animation.js
Labels: cla-present

#788 Fixed `client` flag to default to True on Windows
  python/perspective/.bumpversion.cfg
  python/perspective/perspective/core/_version.py
  python/perspective/perspective/core/widget.py
  python/perspective/perspective/table/__init__.py
Labels: cla-present

#791 Dataframe/Numpy Array Loader
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/arrow.cpp
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/include/perspective/arrow.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/raw_types.h
  python/perspective/perspective/core/data/__init__.py
  python/perspective/perspective/core/data/np.py
  python/perspective/perspective/core/data/pd.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/fill.h
  python/perspective/perspective/include/perspective/python/numpy.h
  python/perspective/perspective/src/fill.cpp
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_table_numpy.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_update.py
  scripts/setup.js
Labels: cla-present

#792 Fixed aggregates to apply to hidden sorted columns
  cpp/perspective/src/cpp/view_config.cpp
Labels: cla-present

#793 Add `update` for widget in client mode, fix `on_update` in Python 2
  packages/perspective-jupyterlab/src/ts/client.ts
  packages/perspective-jupyterlab/src/ts/view.ts
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-viewer/index.d.ts
  python/perspective/perspective/core/manager.py
  python/perspective/perspective/core/widget.py
  python/perspective/perspective/tests/core/test_widget.py
  scripts/build_python.js
  scripts/install_python.js
Labels: cla-present

#794 Added `promo` example project
  examples/promo/package.json
  examples/promo/script.js
  examples/promo/src/index.js
  examples/promo/src/style/index.less
  examples/promo/src/symbols.json
  examples/promo/webpack.config.js
Labels: cla-present

#795 Fixed travis build error & hypergrid console error
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  python/perspective/perspective/core/widget.py
  scripts/build_python.js
Labels: cla-present

#798 Add umd build and updated tests for `perspective-phosphor`
  packages/perspective-phosphor/__mocks__/@finos/perspective-viewer.js
  packages/perspective-phosphor/config/tsconfig.json
  packages/perspective-phosphor/config/webpack.config.js
  packages/perspective-phosphor/config/webpack.theme.config.js
  packages/perspective-phosphor/config/webpack.umd.config.js
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/src/ts/dockpanel/contextmenu.ts
  packages/perspective-phosphor/src/ts/dockpanel/dockpanel.ts
  packages/perspective-phosphor/src/ts/dockpanel/index.ts
  packages/perspective-phosphor/src/ts/dockpanel/tabbar.ts
  packages/perspective-phosphor/src/ts/dockpanel/tabbarrenderer.ts
  packages/perspective-phosphor/src/ts/index.ts
  packages/perspective-phosphor/src/ts/utils.ts
  packages/perspective-phosphor/src/ts/workspace/index.ts
  packages/perspective-phosphor/src/ts/workspace/workspace.ts
  packages/perspective-phosphor/test/js/dockpanel.spec.js
  packages/perspective-phosphor/test/js/workspace.spec.js
  packages/perspective-phosphor/test/setup-jest.js
  yarn.lock
Labels: JS, cla-present, enhancement

#800 add websocket export in type definition
  packages/perspective/index.d.ts
Labels: JS, cla-present, enhancement

#802 Tweak date/datetime inference, remove dependency on non-core Numpy/Pandas API
  python/perspective/perspective/core/data/np.py
  python/perspective/perspective/core/data/pd.py
  python/perspective/perspective/include/perspective/python/numpy.h
  python/perspective/perspective/src/accessor.cpp
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/conftest.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_table_infer.py
  python/perspective/perspective/tests/table/test_table_numpy.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_to_format.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/tests/table/test_update_numpy.py
  python/perspective/perspective/tests/table/test_update_pandas.py
Labels: Python, cla-present, enhancement

#805 Two sided sort fixes
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/include/perspective/context_two.h
  packages/perspective/test/js/clear.js
Labels: cla-present

#799 allow for right master
  packages/perspective-phosphor/src/ts/workspace/workspace.ts
Labels: JS, cla-present, enhancement

#806 Fixed Python Arrow loading bug
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/arrow.cpp
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/table/test_table_arrow.py
Labels: cla-present

#807 Allow client mode widget to be constructed with schema
  python/perspective/perspective/core/widget.py
  python/perspective/perspective/tests/core/test_widget.py
Labels: cla-present

#809 Python build fixes
  .eslintrc.json
  .gitattributes
  .gitignore
  docs/pages/en/index.js
  package.json
  packages/perspective-phosphor/.eslintrc.json
  packages/perspective-phosphor/config/webpack.config.js
  packages/perspective-phosphor/config/webpack.theme.config.js
  packages/perspective-phosphor/src/less/widget.less
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-hypergrid/src/less/hypergrid.less
  packages/perspective-viewer/src/js/polyfill.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-webpack-plugin/package.json
  packages/perspective/package.json
  python/perspective/.gitattributes
  python/perspective/.gitignore
  python/perspective/MANIFEST.in
  python/perspective/js/server.js
  python/perspective/package.json
  python/perspective/setup.py
  python/perspective/yarn.lock
  scripts/build_python.js
  scripts/ci_python.js
  scripts/clean.js
  yarn.lock
Labels: cla-present

#811 Hypergrid no longer depends on `Object.keys` order of dataset
  .gitignore
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/view.h
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
  packages/perspective/src/js/api/view_api.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/pivots.js
  packages/perspective/test/js/sort.js
  python/perspective/perspective/core/widget.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/table/test_view.py
Labels: cla-present

#812 Add puppeteer tests for `perspective-phosphor`
  packages/perspective-phosphor/config/jest.integration.config.js
  packages/perspective-phosphor/config/jest.unit.config.js
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/test/integration/css/index.css
  packages/perspective-phosphor/test/integration/csv/superstore.csv
  packages/perspective-phosphor/test/integration/html/index.html
  packages/perspective-phosphor/test/integration/js/workspace.spec.js
  packages/perspective-phosphor/test/results/results.json
  packages/perspective-phosphor/test/unit/__mocks__/@finos/perspective-viewer.js
  packages/perspective-phosphor/test/unit/js/dockpanel.spec.js
  packages/perspective-phosphor/test/unit/js/workspace.spec.js
  packages/perspective-test/jest.all.config.js
  packages/perspective-test/src/js/beforeEachSpec.js
  packages/perspective-test/src/js/index.js
  scripts/test_js.js
Labels: cla-present

#813 Client mode supports dataframes, np.ndarray, structured and recarray
  cpp/perspective/src/cpp/emscripten.cpp
  packages/perspective-jupyterlab/src/ts/view.ts
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-viewer/index.d.ts
  packages/perspective-viewer/src/js/viewer.js
  python/perspective/perspective/core/__init__.py
  python/perspective/perspective/core/viewer.py
  python/perspective/perspective/core/widget.py
  python/perspective/perspective/src/fill.cpp
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/core/test_viewer.py
  python/perspective/perspective/tests/core/test_widget.py
  python/perspective/perspective/tests/table/test_table.py
Labels: cla-present

#815 Fixed 2-sided sorting on column-only pivots
  cpp/perspective/src/cpp/view_config.cpp
  packages/perspective/test/js/sort.js
Labels: cla-present

#818 Fix misordered columns in update
  python/perspective/perspective/table/table.py
Labels: Python, bug, cla-present

#819 Update Perspective website with Python API and user guide
  .gitignore
  docs/conf.py
  docs/core/Footer.js
  docs/i18n/en.json
  docs/md/development.md
  docs/md/installation.md
  docs/md/js.md
  docs/md/python.md
  docs/md/styles.md
  docs/pages/en/index.js
  docs/sidebars.json
  docs/siteConfig.js
  docs/static/css/custom.css
  docs/static/js/animation.js
  examples/webpack/index.js
  package.json
  packages/perspective-bench/src/js/browser_runtime.js
  packages/perspective-viewer-highcharts/test/js/bar.spec.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/test/js/hypergrid.spec.js
  packages/perspective-viewer/README.md
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/computed_column.js
  packages/perspective-viewer/test/js/computed_columns.spec.js
  packages/perspective/README.md
  packages/perspective/package.json
  packages/perspective/test/js/clear.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/delta.js
  packages/perspective/test/js/filters.js
  packages/perspective/test/js/pivot_nulls.js
  packages/perspective/test/js/pivots.js
  packages/perspective/test/js/sort.js
  packages/perspective/test/js/to_format.js
  packages/perspective/test/js/updates.js
  python/perspective/docs/conf.py
  python/perspective/docs/generate.py
  python/perspective/docs/index.rst
  python/perspective/docs/perspective-python.rst
  python/perspective/docs/perspective.core.rst
  python/perspective/docs/perspective.table.rst
  python/perspective/package.json
  python/perspective/perspective/core/aggregate.py
  python/perspective/perspective/core/data/pd.py
  python/perspective/perspective/core/manager.py
  python/perspective/perspective/core/plugin.py
  python/perspective/perspective/core/sort.py
  python/perspective/perspective/core/tornado_handler.py
  python/perspective/perspective/core/viewer.py
  python/perspective/perspective/core/widget.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_callback_cache.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/table/view_config.py
  scripts/docs.js
  yarn.lock
Labels: Python, cla-present, documentation, enhancement

#820 Add PerspectiveWorkspace olympics example to README
  README.md
Labels: JS, cla-present, enhancement

#821 Default to int64 in Python3, add `long` and `unicode` to schema and type inference
  python/perspective/perspective/src/accessor.cpp
  python/perspective/perspective/src/fill.cpp
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_table_infer.py
  python/perspective/perspective/tests/table/test_table_numpy.py
  python/perspective/perspective/tests/table/test_table_pandas.py
Labels: Python, cla-present, enhancement

#822 Properly remove `on_delete` and `on_update` callbacks that fail.
  .gitignore
  packages/perspective/src/js/api/server.js
  packages/perspective/test/js/delete.js
  packages/perspective/test/js/updates.js
Labels: JS, bug, cla-present

#826 Widget fixes for resizing, TS typings, boolean columns
  README.md
  cpp/perspective/src/cpp/scalar.cpp
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-viewer/index.d.ts
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_table_infer.py
  python/perspective/perspective/tests/table/test_table_numpy.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/tests/table/test_update_numpy.py
  python/perspective/perspective/tests/table/test_view.py
Labels: cla-present
