Repository finos/perspective, pull requests merged in 2019-09, with the labels that each got.

#698 `index` column support
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/column.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/table.h
  examples/simple/schema.html
  examples/simple/test.html
  packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
  packages/perspective/README.md
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/filters.js
Labels: cla-present

#699 `leaves_only` flag for perspective
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/to_format.js
Labels: cla-present

#700 Limit charts
  docs/static/css/material.dark.css
  packages/perspective-viewer-d3fc/src/js/charts/area.js
  packages/perspective-viewer-d3fc/src/js/charts/bar.js
  packages/perspective-viewer-d3fc/src/js/charts/candlestick.js
  packages/perspective-viewer-d3fc/src/js/charts/column.js
  packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/js/charts/ohlc.js
  packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
  packages/perspective-viewer-d3fc/src/js/charts/treemap.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/charts/y-scatter.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-highcharts/src/js/highcharts/draw.js
  packages/perspective-viewer-highcharts/src/js/highcharts/highcharts.js
  packages/perspective-viewer-highcharts/test/js/bar.spec.js
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer/src/html/viewer.html
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/js/unit/perspective_element.spec.js
  packages/perspective-viewer/test/js/utils.js
  packages/perspective-viewer/test/results/results.json
Labels: cla-present

#702 Allow for perspective in ipywidgets layouts
  packages/perspective-jupyterlab/src/less/index.less
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective-phosphor/src/ts/widget.ts
Labels: Jupyter, cla-present

#703 `perspective-viewer` cleanup
  docs/static/css/material.dark.css
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer/src/js/computed_column.js
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/dragdrop.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/js/viewer/state_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/test/js/computed_columns.spec.js
Labels: cla-present

#706 Test implicit index & remove extraneous example file
  examples/simple/schema.html
  packages/perspective/src/js/data_accessor/index.js
  packages/perspective/test/js/to_format.js
  packages/perspective/test/js/updates.js
Labels: cla-present

#705 documentation/style fix
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective-phosphor/src/ts/widget.ts
Labels: cla-present

#707 Refactor C++
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/table.h
  cpp/perspective/src/include/perspective/view_config.h
  packages/perspective-viewer-hypergrid/test/js/regressions.spec.js
  packages/perspective/test/js/filters.js
Labels: cla-present

#710 Copy-paste error in last PR
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective-viewer/src/js/viewer/dom_element.js
Labels: Jupyter, bug, cla-present

#711 `perspective-test` Module
  package.json
  packages/perspective-test/babel.config.js
  packages/perspective-test/jest.all.config.js
  packages/perspective-test/jest.config.js
  packages/perspective-test/package.json
  packages/perspective-test/src/js/beforeEachSpec.js
  packages/perspective-test/src/js/index.js
  packages/perspective-test/src/js/transform.js
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/test/js/integration/area.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/candlestick.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/heatmap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/ohlc.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/yscatter.spec.js
  packages/perspective-viewer-d3fc/test/js/jest.unit.config.js
  packages/perspective-viewer-d3fc/test/js/transform.js
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-highcharts/test/js/bar.spec.js
  packages/perspective-viewer-highcharts/test/js/heatmap.spec.js
  packages/perspective-viewer-highcharts/test/js/line.spec.js
  packages/perspective-viewer-highcharts/test/js/scatter.spec.js
  packages/perspective-viewer-highcharts/test/js/slow.spec.js
  packages/perspective-viewer-highcharts/test/js/treemap.spec.js
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer-hypergrid/test/html/empty.html
  packages/perspective-viewer-hypergrid/test/html/superstore.html
  packages/perspective-viewer-hypergrid/test/js/hypergrid.spec.js
  packages/perspective-viewer-hypergrid/test/js/regressions.spec.js
  packages/perspective-viewer-hypergrid/test/js/slow.spec.js
  packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/test/js/computed_columns.spec.js
  packages/perspective-viewer/test/js/jest.unit.config.js
  packages/perspective-viewer/test/js/leaks.spec.js
  packages/perspective-viewer/test/js/regressions.spec.js
  packages/perspective-viewer/test/js/simple_tests.js
  packages/perspective-viewer/test/js/slow.spec.js
  packages/perspective-viewer/test/js/superstore.spec.js
  packages/perspective-viewer/test/js/transform.js
  packages/perspective-viewer/test/results/results.json
  packages/perspective/src/js/perspective.node.js
  scripts/test.js
Labels: cla-present

#708 Editing for `@finos/perspective-viewer-hypergrid`
  cpp/perspective/src/cpp/emscripten.cpp
  packages/perspective-viewer-d3fc/src/js/charts/candlestick.js
  packages/perspective-viewer-d3fc/src/js/charts/ohlc.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/editors.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/src/js/styles.js
  packages/perspective-viewer-hypergrid/src/less/hypergrid.less
  packages/perspective-viewer-hypergrid/test/html/editable.html
  packages/perspective-viewer-hypergrid/test/js/editing.spec.js
  packages/perspective-viewer-hypergrid/test/js/utils.js
  packages/perspective-viewer/src/js/computed_column.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
Labels: JS, cla-present, enhancement

#725 `yarn setup`
  .gitignore
  .travis.yml
  README.md
  docs/md/development.md
  docs/md/usage.md
  docs/pages/en/index.js
  package.json
  scripts/build.js
  scripts/build_js.js
  scripts/setup.js
  scripts/test.js
  scripts/test_js.js
  yarn.lock
Labels: cla-present

#726 Misc cleanup and fixes
  packages/perspective-viewer-d3fc/src/js/axis/axisType.js
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/test/results/results.json
Labels: cla-present

#715 Type-on-edit
  examples/simple/superstore-hypergrid.html
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/editors.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/styles.js
  packages/perspective-viewer-hypergrid/src/less/hypergrid.less
  packages/perspective-viewer-hypergrid/test/js/editing.spec.js
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/src/js/viewer/dom_element.js
  scripts/test_js.js
Labels: cla-present

#727 Fixed schema miscalculation with computed columns and implicit index
  packages/perspective/src/js/perspective.js
Labels: cla-present

#729 Allow partial updates on computed column source columns
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/pool.h
  cpp/perspective/src/include/perspective/table.h
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/updates.js
  python/table/perspective/include/perspective/python/fill.h
  python/table/perspective/src/fill.cpp
Labels: cla-present

#695 Readable dates
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/to_format.js
Labels: JS, enhancement

#730 Python improvements + refactor
  .gitignore
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/cpp/update_task.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/pool.h
  examples/simple/superstore-hypergrid.html
  examples/simple/test.html
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/filters.js
  python/perspective/README.md
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/serialization.h
  python/perspective/perspective/node/assets/zmq.node
  python/perspective/perspective/src/fill.cpp
  python/perspective/perspective/src/serialization.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_callback_cache.py
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/_exception.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/table/view_config.py
  python/perspective/perspective/tests/core/data/test_pd.py
  python/perspective/perspective/tests/table/binding/test_make_view.py
  python/perspective/perspective/tests/table/psp_test
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_to_format.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/setup.py
Labels: cla-present

#731 fixes view->plugin rename that didnt make it from original repo
  python/perspective/perspective/core/__init__.py
  python/perspective/perspective/core/base.py
  python/perspective/perspective/core/examples.py
  python/perspective/perspective/core/plugin.py
  python/perspective/perspective/core/psp.py
  python/perspective/perspective/core/validate.py
  python/perspective/perspective/core/widget.py
  python/perspective/perspective/tests/core/test_aggregates.py
  python/perspective/perspective/tests/core/test_layout.py
Labels: cla-present

#733 Enable update with __INDEX__ on explicit index column
  cpp/perspective/src/cpp/table.cpp
  packages/perspective/test/js/updates.js
Labels: cla-present

#734 Added .gitattributes
  .gitattributes
Labels: cla-present

#735 Test suite failure feedback
  docker/puppeteer/Dockerfile
  package.json
  packages/perspective-test/jest.all.config.js
  packages/perspective-test/jest.config.js
  packages/perspective-test/src/js/index.js
  packages/perspective-test/src/js/reporter.js
  packages/perspective/src/js/perspective.node.js
  scripts/setup.js
  scripts/test_js.js
  yarn.lock
Labels: cla-present

#739 ＶΛＰＯＲＷΛＶΞ
  docs/md/styles.md
  examples/simple/index.html
  examples/simple/superstore-vaporwave.html
  packages/perspective-test/jest.all.config.js
  packages/perspective-test/jest.config.js
  packages/perspective-test/src/js/reporter.js
  packages/perspective-viewer-d3fc/test/html/themed-template.html
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid-tree-cell-renderer.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/src/js/styles.js
  packages/perspective-viewer-hypergrid/test/results/results.darwin.json
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/js/viewer/renderers.js
  packages/perspective-viewer/src/less/column_labels.less
  packages/perspective-viewer/src/less/computed_column.less
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/src/themes/vaporwave.less
  packages/perspective-viewer/test/results/results.darwin.json
  packages/perspective-viewer/test/results/results.json
Labels: cla-present

#740 Computed column partial update
  .gitignore
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/gnode.h
  packages/perspective/test/js/computed.js
  packages/perspective/test/js/perspective.spec.js
Labels: cla-present

#741 Read numpy nans/datetimes
  .gitignore
  cpp/perspective/src/include/perspective/val.h
  examples/simple/test.html
  packages/perspective/test/js/updates.js
  python/perspective/README.md
  python/perspective/perspective/include/perspective/python/base.h
  python/perspective/perspective/include/perspective/python/utils.h
  python/perspective/perspective/node/assets/zmq.node
  python/perspective/perspective/src/fill.cpp
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/node/test_node.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/requirements-dev.txt
Labels: cla-present

#743 Add PerspectiveManager remote API for Python, Tornado server example
  packages/perspective/src/js/api/server.js
  python/perspective/examples/FTSE100.pkl
  python/perspective/examples/perspective_tornado_client.html
  python/perspective/examples/perspective_tornado_server.py
  python/perspective/perspective/table/__init__.py
  python/perspective/perspective/table/_callback_cache.py
  python/perspective/perspective/table/manager.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/node/test_node.py
  python/perspective/perspective/tests/table/test_manager.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_update.py
Labels: cla-present

#745 Fix empty list in phosphor plugin
  packages/perspective-phosphor/src/ts/widget.ts
Labels: JS, Jupyter, cla-present

#744 Some cleanup items
  package.json
  python/perspective/MANIFEST.in
  python/perspective/README.md
  python/perspective/examples/FTSE100.pkl
  python/perspective/examples/perspective_tornado_server.py
  python/perspective/examples/superstore.csv
  python/perspective/perspective/core/__init__.py
  python/perspective/perspective/core/aggregate.py
  python/perspective/perspective/core/computed.py
  python/perspective/perspective/core/exception.py
  python/perspective/perspective/core/filters.py
  python/perspective/perspective/core/plugin.py
  python/perspective/perspective/core/sort.py
  python/perspective/perspective/core/validate.py
  python/perspective/perspective/core/web.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_callback_cache.py
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/_exception.py
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/table/manager.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/table/view_config.py
  python/perspective/perspective/tests/core/test_aggregates.py
  python/perspective/perspective/tests/core/test_layout.py
  python/perspective/perspective/tests/core/test_widget.py
  python/perspective/perspective/tests/table/binding/test_View_ctx.py
  python/perspective/perspective/tests/table/binding/test_make_table.py
  python/perspective/perspective/tests/table/binding/test_make_view.py
  python/perspective/perspective/tests/table/binding/test_t_cellupd.py
  python/perspective/perspective/tests/table/binding/test_t_ctx.py
  python/perspective/perspective/tests/table/binding/test_t_data_slice.py
  python/perspective/perspective/tests/table/binding/test_t_data_table.py
  python/perspective/perspective/tests/table/binding/test_t_gnode.py
  python/perspective/perspective/tests/table/binding/test_t_pool.py
  python/perspective/perspective/tests/table/binding/test_t_schema.py
  python/perspective/perspective/tests/table/binding/test_t_stepdelta.py
  python/perspective/perspective/tests/table/binding/test_t_tscalar.py
  python/perspective/perspective/tests/table/binding/test_t_updctx.py
  python/perspective/perspective/tests/table/binding/test_table.py
  python/perspective/perspective/tests/table/binding/test_view_config.py
  python/perspective/perspective/tests/table/test_manager.py
  python/perspective/perspective/tests/table/test_remove.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_to_format.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/setup.py
  scripts/clean.js
Labels: Python, cla-present
