Repository finos/perspective, pull requests merged in 2019-02, with the labels that each got.

#404 add another IEX demo
  README.md
Labels: documentation

#418 limit to a single build (15 minutes) until we have more resources
  .appveyor.yml
Labels: C++, tests

#413 Port View to C++
  API.md
  CMakeLists.txt
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/translator.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/pivots.js
  src/cpp/emscripten.cpp
  src/cpp/scalar.cpp
  src/cpp/view.cpp
  src/include/perspective/binding.h
  src/include/perspective/view.h
Labels: C++, JS

#415 [WIP] Better python build for location of shared objects.
  scripts/test_python.js
  setup.py
Labels: Python, enhancement

#428 Allow mac failures on travis, have travis fail fast
  .travis.yml
Labels: enhancement, tests

#427 Tidy up dependencies
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/computed_column/state.js
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective/package.json
  packages/perspective/test/js/updates.js
  yarn.lock
Labels: JS, enhancement

#434 Make sort syntax consistent in tests
  packages/perspective-viewer/test/js/computed_columns.spec.js
  packages/perspective-viewer/test/js/simple_tests.js
  packages/perspective/src/js/perspective.js
Labels: JS, enhancement, in progress

#435 Write arrows
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/include/perspective/emscripten.h
  package.json
  packages/perspective-webpack-plugin/index.js
  packages/perspective-webpack-plugin/package.json
  packages/perspective/bench/js/bench.js
  packages/perspective/bench/js/browser_runtime.js
  packages/perspective/src/js/api.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/perspective.spec.js
  packages/perspective/test/js/pivots.js
  packages/perspective/test/js/to_format.js
  yarn.lock
Labels: C++, JS, enhancement

#439 Interactions click dispatch
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/test/html/hypergrid.html
  packages/perspective-viewer-hypergrid/test/js/hypergrid.spec.js
  packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
  packages/perspective-viewer-hypergrid/test/results/results.json
Labels: in progress

#445 Fix regression on view expand
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/view.h
  packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/pivots.js
Labels: in progress

#437 Purges phosphor and jlab tests
  packages/perspective-jupyterlab/__mocks__/@jpmorganchase/perspective-viewer-highcharts.js
  packages/perspective-jupyterlab/__mocks__/@jpmorganchase/perspective-viewer-hypergrid.js
  packages/perspective-jupyterlab/__mocks__/@jpmorganchase/perspective-viewer.js
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/test/js/fileMock.js
  packages/perspective-jupyterlab/test/js/styleMock.js
  packages/perspective-jupyterlab/test/ts/version.spec.ts
  packages/perspective-jupyterlab/tsconfig.json
  packages/perspective-phosphor/__mocks__/@jpmorganchase/perspective-viewer-highcharts.js
  packages/perspective-phosphor/__mocks__/@jpmorganchase/perspective-viewer-hypergrid.js
  packages/perspective-phosphor/__mocks__/@jpmorganchase/perspective-viewer.js
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/test/js/fileMock.js
  packages/perspective-phosphor/test/js/styleMock.js
  packages/perspective-phosphor/test/ts/widget.spec.ts
  packages/perspective-phosphor/tsconfig.json
Labels: JS, tests

#449 Add tests for filtering datetime columns by string
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/test/js/simple_tests.js
  packages/perspective-viewer/test/results/results.json
  packages/perspective/test/js/filters.js
Labels: in progress

#444 Add high chart click interactions
  examples/simple/linked.html
  packages/perspective-viewer-highcharts/src/js/config.js
  packages/perspective-viewer-highcharts/src/js/tooltip.js
  packages/perspective-viewer-highcharts/test/js/bar.spec.js
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/test/js/hypergrid.spec.js
  packages/perspective-viewer/test/js/utils.js
Labels: JS, enhancement, in progress

#448 Build cleanup
  package.json
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective-phosphor/src/config/plugin.config.js
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-viewer-highcharts/babel.config.js
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-highcharts/src/config/highcharts.plugin.config.js
  packages/perspective-viewer-highcharts/src/js/draw.js
  packages/perspective-viewer-highcharts/src/js/series.js
  packages/perspective-viewer-highcharts/test/js/bar.spec.js
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/babel.config.js
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer-hypergrid/src/config/hypergrid.plugin.config.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer/babel.config.js
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/config/view.config.js
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-webpack-plugin/babel.config.js
  packages/perspective-webpack-plugin/index.js
  packages/perspective-webpack-plugin/package.json
  packages/perspective/babel.config.js
  packages/perspective/package.json
  yarn.lock
Labels: in progress

#450 Moved `perspective-jupyterlab` build from `build/` to `dist/` to work…
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/config/plugin.config.js
Labels: in progress

#453 Added `shared_worker()` to ts definition
  packages/perspective/index.d.ts
Labels: in progress

#451 Fixed Github reported dependency vulnerabilities
  examples/webpack/package.json
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-webpack-plugin/package.json
  yarn.lock
Labels: in progress

#420 D3fc plugin
  examples/simple/index.html
  examples/simple/superstore-d3fc.html
  packages/perspective-viewer-d3fc/babel.config.js
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/config/d3fc.plugin.config.js
  packages/perspective-viewer-d3fc/src/html/d3fc-chart.html
  packages/perspective-viewer-d3fc/src/html/d3fc.html
  packages/perspective-viewer-d3fc/src/html/legend-controls.html
  packages/perspective-viewer-d3fc/src/html/tooltip.html
  packages/perspective-viewer-d3fc/src/js/axis/crossAxis.js
  packages/perspective-viewer-d3fc/src/js/axis/mainAxis.js
  packages/perspective-viewer-d3fc/src/js/axis/minBandwidth.js
  packages/perspective-viewer-d3fc/src/js/axis/withoutTicks.js
  packages/perspective-viewer-d3fc/src/js/charts/bar.js
  packages/perspective-viewer-d3fc/src/js/charts/charts.js
  packages/perspective-viewer-d3fc/src/js/charts/column.js
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/data/groupAndStackData.js
  packages/perspective-viewer-d3fc/src/js/data/pointData.js
  packages/perspective-viewer-d3fc/src/js/data/splitData.js
  packages/perspective-viewer-d3fc/src/js/data/splitIntoMultiSeries.js
  packages/perspective-viewer-d3fc/src/js/gridlines/gridlines.js
  packages/perspective-viewer-d3fc/src/js/legend/legend.js
  packages/perspective-viewer-d3fc/src/js/legend/scrollableLegend.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/plugin/root.js
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
  packages/perspective-viewer-d3fc/src/js/series/barSeries.js
  packages/perspective-viewer-d3fc/src/js/series/lineSeries.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeries.js
  packages/perspective-viewer-d3fc/src/js/series/seriesColours.js
  packages/perspective-viewer-d3fc/src/js/series/seriesKey.js
  packages/perspective-viewer-d3fc/src/js/series/seriesLinearRange.js
  packages/perspective-viewer-d3fc/src/js/styling/chartStyling.js
  packages/perspective-viewer-d3fc/src/js/styling/crossAxisMap.js
  packages/perspective-viewer-d3fc/src/js/tooltip/tooltip.js
  packages/perspective-viewer-d3fc/src/js/utils/utils.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/src/less/d3fc.less
  packages/perspective-viewer-d3fc/src/less/perspective-view.less
  packages/perspective-viewer-d3fc/test/html/bar.html
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective/src/js/perspective.node.js
  yarn.lock
Labels: JS, enhancement

#454 Fixed babel compilation in `perspective-d3fc-plugin` package
  packages/perspective-viewer-d3fc/babel.config.js
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/config/d3fc.plugin.config.js
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
Labels: in progress

#452 Port view to C++
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/config.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/config.h
  cpp/perspective/src/include/perspective/view.h
  packages/perspective/src/js/emscripten.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/internal.js
  packages/perspective/test/js/to_format.js
  python/perspective/include/perspective/python.h
  python/perspective/src/python.cpp
Labels: C++

#455 Fixes for `clean` and `bench` development scripts
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective/bench/js/bench.js
  packages/perspective/bench/js/browser_runtime.js
  scripts/clean.js
Labels: in progress

#457 Removed NPM caching from travis config
  .travis.yml
Labels: in progress

#456 Updated AUTHORS
  AUTHORS
Labels: in progress

#459 Added missing `@babel/runtime` dependency
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer/package.json
  packages/perspective/package.json
  yarn.lock
Labels: in progress

#461 Click event fix
  packages/perspective-viewer-highcharts/src/js/config.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
Labels: in progress
