Repository finos/perspective, pull requests merged in 2019-06, with the labels that each got.

#606 Sync refactor
  docs/md/usage.md
  examples/remote/README.md
  examples/remote/index.html
  examples/remote/server.js
  packages/perspective-cli/src/html/index.html
  packages/perspective-cli/src/js/index.js
  packages/perspective-cli/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-webpack-plugin/package.json
  packages/perspective/package.json
  packages/perspective/src/js/API/client.js
  packages/perspective/src/js/API/server.js
  packages/perspective/src/js/API/table_api.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/utils.js
  packages/perspective/test/js/internal.js
  packages/perspective/test/js/updates.js
Labels: cla-present

#608 Restore highchairs on phosphor/jlab until d3 is complete
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-webpack-plugin/package.json
  yarn.lock
Labels: JS, Jupyter, cla-present

#607 Allow transfer as columns
  packages/perspective-phosphor/src/ts/widget.ts
Labels: JS, cla-present, enhancement

#609 Fixed split-axis y_line charts in D3FC
  packages/perspective-viewer-d3fc/src/js/charts/area.js
  packages/perspective-viewer-d3fc/src/js/charts/bar.js
  packages/perspective-viewer-d3fc/src/js/charts/column.js
  packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/js/charts/ohlcCandle.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/charts/y-scatter.js
  packages/perspective-viewer-d3fc/src/js/gridlines/gridlines.js
  packages/perspective-viewer-d3fc/src/js/series/colorStyles.js
Labels: cla-present

#610 Made drag/drop zones more generous
  packages/perspective-viewer/src/less/viewer.less
Labels: cla-present

#611 Make "view" attribute of `<perspective-viewer>` backwards compatible
  packages/perspective-viewer/src/js/viewer.js
Labels: cla-present

#614 Updated website
  .gitignore
  docs/i18n/en.json
  docs/md/installation.md
  docs/md/usage.md
  docs/package.json
  docs/pages/en/index.js
  docs/siteConfig.js
  docs/static/css/custom.css
  docs/static/css/material.dark.css
  docs/static/css/material.dark.less
  docs/static/js/animation.js
  examples/simple/index.html
  packages/perspective/README.md
  packages/perspective/src/js/perspective.js
Labels: cla-present

#615 Webpack perf
  package.json
  packages/perspective-cli/babel.config.js
  packages/perspective-viewer-d3fc/babel.config.js
  packages/perspective-viewer-d3fc/test/js/transform.js
  packages/perspective-viewer-highcharts/babel.config.js
  packages/perspective-viewer-hypergrid/babel.config.js
  packages/perspective-viewer/babel.config.js
  packages/perspective/babel.config.js
  yarn.lock
Labels: cla-present

#628 Memory usage fixes
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/include/perspective/gnode.h
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective/src/js/perspective.js
Labels: cla-present

#625 Phosphor and JupyterLab bug and regression fixes
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective-phosphor/README.md
  packages/perspective-phosphor/src/ts/widget.ts
Labels: JS, Jupyter, bug, cla-present

#629 Remove support for ASM.JS, Internet Explorer and other non-WASM browsers
  cpp/perspective/CMakeLists.txt
  packages/perspective-webpack-plugin/src/js/psp-worker-compiler-loader.js
  packages/perspective-webpack-plugin/src/js/psp-worker-loader.js
  packages/perspective/src/js/perspective.asmjs.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
  packages/perspective/src/js/psp.sync.wasm.js
  packages/perspective/test/js/perspective.spec.js
  scripts/build.js
Labels: cla-present

#630 Use MODULARIZE emscripten option instead of a custom one
  cpp/perspective/CMakeLists.txt
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.wasm.js
  scripts/build.js
Labels: cla-present

#631 Update Babel `preset-env`
  packages/perspective-cli/babel.config.js
  packages/perspective-viewer-d3fc/babel.config.js
  packages/perspective-viewer-highcharts/babel.config.js
  packages/perspective-viewer-hypergrid/babel.config.js
  packages/perspective-viewer/babel.config.js
  packages/perspective/babel.config.js
  packages/perspective/src/config/perspective.node.config.js
Labels: cla-present

#632 Fixed safari hypergrid rendering
  packages/perspective-viewer-hypergrid/src/less/hypergrid.less
Labels: cla-present

#634 Fixed async loading of node.js module
  packages/perspective/src/js/API/client.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/test/js/internal.js
  packages/perspective/test/js/sync_load.spec.js
Labels: cla-present

#635 Don't use transferable for WASM payload
  packages/perspective/src/js/perspective.parallel.js
Labels: cla-present
