Repository finos/perspective, pull requests merged in 2019-10, with the labels that each got.

#748 add compute() to dynamically show/hide sidebar computation panel
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective/src/js/api/table_api.js
  packages/perspective/src/js/perspective.js
  python/perspective/perspective/table/table.py
Labels: cla-present

#749 Fix update bugs
  packages/perspective/src/js/api/dispatch.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/delete.js
  packages/perspective/test/js/updates.js
Labels: cla-present

#751 ES6 Client API
  packages/perspective/src/js/api/client.js
Labels: cla-present

#752 Fixed grid performance when pivoted
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
Labels: cla-present

#753 Fixed `yarn clean` script
  scripts/clean.js
  scripts/script_utils.js
Labels: cla-present

#759 Add `to_csv` to Python API
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/table/test_to_format.py
Labels: cla-present

#764 Hypergrid renderer fixes
  packages/perspective-test/src/js/index.js
  packages/perspective-test/src/js/reporter.js
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
  packages/perspective-viewer-hypergrid/test/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
Labels: cla-present

#770 Fixed ios compatibility
  packages/perspective-viewer-hypergrid/src/less/hypergrid.less
  packages/perspective/src/js/perspective.parallel.js
Labels: cla-present

#771 Added `Table()` support for numpy recarray
  python/perspective/perspective/core/manager.py
  python/perspective/perspective/core/session.py
  python/perspective/perspective/core/widget.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/tests/core/test_manager.py
Labels: cla-present

#768 Upgrade Arrow to 0.15.0, link python arrow from prebuilt library
  cmake/arrow.txt.in
  cmake/arrow/CMakeLists.txt
  cmake/arrow/config.h
  cmake/modules/FindPyArrow.cmake
  cpp/perspective/CMakeLists.txt
  scripts/build_python.js
  scripts/test_python.js
Labels: Python, cla-present, enhancement

#772 Arrow fixes
  cpp/perspective/src/cpp/arrow.cpp
  cpp/perspective/src/include/perspective/arrow.h
  docker/python/Dockerfile
Labels: cla-present

#765 Computed UX
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/src/js/computed_column.js
  packages/perspective-viewer/src/js/computed_column/computation.js
  packages/perspective-viewer/src/js/computed_column/state.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/less/computed_column.less
  packages/perspective-viewer/test/js/computed_columns.spec.js
  packages/perspective-viewer/test/results/results.json
Labels: JS, cla-present, enhancement

#776 Multiple views on JLab plugin
  packages/perspective-jupyterlab/src/ts/view.ts
  python/perspective/perspective/core/widget.py
Labels: cla-present

#777 Add exception handling, clean up PSP_COMPLAIN_AND_ABORT
  cpp/perspective/src/cpp/arrow.cpp
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/schema.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/exception.h
  cpp/perspective/test/cpp/simple.cpp
  python/perspective/.gitignore
  python/perspective/examples/perspective_tornado_client.html
  python/perspective/perspective/core/manager.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/node/assets/bundle.js
  python/perspective/perspective/table/__init__.py
  python/perspective/perspective/tests/core/test_manager.py
  python/perspective/perspective/tests/table/test_exception.py
Labels: Python, cla-present, enhancement

#778 Adjust setup.py for MacOS wheel dist
  cpp/perspective/CMakeLists.txt
  python/perspective/.bumpversion.cfg
  python/perspective/MANIFEST.in
  python/perspective/README.md
  python/perspective/requirements.txt
Labels: Python, cla-present, enhancement

#779 Fixes jupyterlab plugin regressions
  packages/perspective-jupyterlab/README.md
  packages/perspective-jupyterlab/src/less/index.less
  packages/perspective-jupyterlab/src/ts/index.ts
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
Labels: JS, Jupyter, cla-present, enhancement

#781 Mobile fixes
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/editors.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/polyfill.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  yarn.lock
Labels: cla-present

#785 Hypergrid paintloop removal
  examples/phosphor/src/index.js
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/README.md
  packages/perspective/src/js/perspective.js
  python/perspective/.bumpversion.cfg
  python/perspective/perspective/core/_version.py
Labels: cla-present
