Repository finos/perspective, pull requests merged in 2019-12, with the labels that each got.

#829 Read date32, date64, decimal128 from Arrow datasets
  cpp/perspective/src/cpp/arrow.cpp
  cpp/perspective/src/include/perspective/arrow.h
  packages/perspective/test/arrow/date32.arrow
  packages/perspective/test/arrow/date64.arrow
  packages/perspective/test/arrow/test_null.arrow
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/internal.js
  packages/perspective/test/js/test_arrows.js
  packages/perspective/test/js/updates.js
  python/perspective/perspective/tests/conftest.py
  python/perspective/perspective/tests/table/test_table_arrow.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_update_arrow.py
Labels: C++, JS, Python, cla-present, enhancement

#831 Fix `PerspectiveWorkspace` when tabbed views are moved to master
  packages/perspective-phosphor/src/theme/material/menu.less
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-phosphor/src/ts/workspace/workspace.ts
Labels: JS, bug, cla-present, enhancement

#833 Preserve user columns and pivots in widget
  python/perspective/perspective/tests/core/test_widget_pandas.py
  python/perspective/perspective/widget/widget.py
Labels: Python, cla-present, enhancement

#832 CSV/JSON renderer in JupyterLab
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/config/plugin.config.js
  packages/perspective-jupyterlab/src/less/index.less
  packages/perspective-jupyterlab/src/ts/index.ts
  packages/perspective-jupyterlab/src/ts/plugin.ts
  packages/perspective-jupyterlab/src/ts/renderer.ts
  packages/perspective-jupyterlab/src/ts/view.ts
  packages/perspective-phosphor/package.json
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/viewer/viewer_traitlets.py
  yarn.lock
Labels: JS, Jupyter, cla-present, enhancement

#834 Set Enums as values for Widget/Viewer, refactor test folder structure
  python/perspective/perspective/tests/core/test_aggregates.py
  python/perspective/perspective/tests/core/test_plugin.py
  python/perspective/perspective/tests/core/test_sort.py
  python/perspective/perspective/tests/manager/test_manager.py
  python/perspective/perspective/tests/viewer/test_validate.py
  python/perspective/perspective/tests/viewer/test_viewer.py
  python/perspective/perspective/tests/widget/test_widget.py
  python/perspective/perspective/tests/widget/test_widget_pandas.py
  python/perspective/perspective/viewer/validate.py
  python/perspective/perspective/viewer/viewer.py
Labels: Python, cla-present, enhancement

#836 Remove `ci_python` and refactor scripts.
  .travis.yml
  package.json
  scripts/build_js.js
  scripts/build_python.js
  scripts/ci_python.js
  scripts/clean.js
  scripts/docs.js
  scripts/fix_cpp.js
  scripts/install_python.js
  scripts/lint_cpp.js
  scripts/lint_python.js
  scripts/script_utils.js
  scripts/setup.js
  scripts/test_js.js
  scripts/test_python.js
  scripts/toggle_puppeteer.js
  scripts/version_python.js
Labels: Python, cla-present, enhancement

#835 Throttle fix
  packages/perspective-viewer/src/js/viewer/perspective_element.js
Labels: JS, cla-present, enhancement

#840 Async resize
  .gitignore
  cpp/perspective/src/cpp/emscripten.cpp
  package.json
  packages/perspective-jupyterlab/test/js/regressions.spec.js
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-test/jest.all.config.js
  packages/perspective-test/jest.config.js
  packages/perspective-test/src/js/globalSetup.js
  packages/perspective-test/src/js/globalTeardown.js
  packages/perspective-test/src/js/index.js
  packages/perspective-viewer-d3fc/src/js/axis/ordinalAxis.js
  packages/perspective-viewer-d3fc/test/results/results.darwin.json
  packages/perspective-viewer-highcharts/test/results/results.darwin.json
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective/src/js/api/client.js
  scripts/script_utils.js
  scripts/test_js.js
  yarn.lock
Labels: JS, cla-present, enhancement

#838 Asynchronously process updates when running in Tornado
  packages/perspective/src/js/perspective.js
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/_state.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/core/test_async.py
  python/perspective/perspective/tests/manager/test_manager.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tornado_handler/tornado_handler.py
  python/perspective/requirements-dev.txt
Labels: Python, cla-present, enhancement

#845 Theme `material-dense`
  cpp/perspective/CMakeLists.txt
  docs/md/styles.md
  examples/webpack/package.json
  package.json
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/src/less/widget.less
  packages/perspective-phosphor/src/theme/material/dockpanel.less
  packages/perspective-phosphor/src/theme/material/index.less
  packages/perspective-phosphor/src/theme/material/menu.less
  packages/perspective-phosphor/src/theme/material/tabbar.less
  packages/perspective-phosphor/src/theme/material/widget.less
  packages/perspective-phosphor/src/theme/material/workspace.less
  packages/perspective-phosphor/src/ts/dockpanel/contextmenu.ts
  packages/perspective-phosphor/src/ts/dockpanel/dockpanel.ts
  packages/perspective-phosphor/src/ts/dockpanel/tabbarrenderer.ts
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-phosphor/src/ts/workspace/workspace.ts
  packages/perspective-phosphor/test/integration/js/workspace.spec.js
  packages/perspective-phosphor/test/results/results.json
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-highcharts/test/results/results.json
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/styles.js
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/src/html/viewer.html
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material-dense.dark.less
  packages/perspective-viewer/src/themes/material-dense.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/results/results.json
  scripts/clean.js
  scripts/test_js.js
  yarn.lock
Labels: cla-present

#844 Node.js `table` unpin
  packages/perspective/src/js/perspective.node.js
Labels: JS, bug, cla-present

#847 add editable example to readme
  README.md
Labels: cla-present, documentation

#846 `weighted mean` aggregate type
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/extract_aggregate.cpp
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/view_config.h
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/state_element.js
  packages/perspective/test/js/pivots.js
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/tests/table/test_view.py
Labels: C++, JS, cla-present, enhancement

#848 Fixed resize behavior
  packages/perspective-viewer/src/js/viewer.js
Labels: JS, bug, cla-present

#842 Add `selectable` attribute to `perspective-viewer`
  examples/datasources/index.js
  examples/datasources/securities.js
  examples/phosphor/src/index.js
  examples/phosphor/src/index.less
  examples/webpack/index.js
  examples/webpack/webpack.config.js
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-phosphor/src/ts/workspace/workspace.ts
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/styles.js
  packages/perspective-viewer-hypergrid/test/html/selectable.html
  packages/perspective-viewer-hypergrid/test/js/selection.spec.js
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/index.d.ts
  packages/perspective-viewer/src/js/custom_styles.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective/src/js/perspective.js
Labels: cla-present

#851 Exp bin functions
  packages/perspective-viewer-hypergrid/test/results/results.json
  packages/perspective-viewer/src/js/computed_column.js
Labels: cla-present

#852 Update versioning script for Python
  python/perspective/perspective/core/_version.py
  scripts/version_python.js
Labels: cla-present

#853 Fix `perspective-jupyterlab` theme
  packages/perspective-jupyterlab/src/less/index.less
  packages/perspective-phosphor/src/less/widget.less
Labels: JS, cla-present, enhancement

#850 Implement `to_arrow` in C++ for JS/Python
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/arrow_loader.cpp
  cpp/perspective/src/cpp/arrow_writer.cpp
  cpp/perspective/src/cpp/data_slice.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/arrow_loader.h
  cpp/perspective/src/include/perspective/arrow_writer.h
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/data_slice.h
  cpp/perspective/src/include/perspective/emscripten.h
  cpp/perspective/src/include/perspective/view.h
  package.json
  packages/perspective/src/config/common.config.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/delta.js
  packages/perspective/test/js/to_format.js
  python/perspective/examples/remote.html
  python/perspective/examples/remote.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/view.h
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/session.py
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/conftest.py
  python/perspective/perspective/tests/table/test_table_arrow.py
  python/perspective/perspective/tests/table/test_to_arrow.py
  python/perspective/perspective/tests/table/test_to_format.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/perspective/tornado_handler/tornado_handler.py
  yarn.lock
Labels: C++, cla-present, enhancement
