Repository finos/perspective, pull requests merged in 2020-06, with the labels that each got.

#1060 Use `regular-table`
  packages/perspective-viewer-datagrid/babel-plugin-transform-tagged-literal.js
  packages/perspective-viewer-datagrid/babel.config.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/constants.js
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/js/events.js
  packages/perspective-viewer-datagrid/src/js/index.js
  packages/perspective-viewer-datagrid/src/js/scroll_panel.js
  packages/perspective-viewer-datagrid/src/js/table.js
  packages/perspective-viewer-datagrid/src/js/tbody.js
  packages/perspective-viewer-datagrid/src/js/thead.js
  packages/perspective-viewer-datagrid/src/js/tree_row_header.js
  packages/perspective-viewer-datagrid/src/js/utils.js
  packages/perspective-viewer-datagrid/src/js/view_model.js
  packages/perspective-viewer-datagrid/src/less/container.less
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/test/html/empty.html
  packages/perspective-viewer-datagrid/test/html/regressions.html
  packages/perspective-viewer-datagrid/test/js/regressions.spec.js
  packages/perspective-viewer-datagrid/test/js/scrolling.spec.js
  packages/perspective-viewer-datagrid/test/js/slow.spec.js
  packages/perspective-viewer-datagrid/test/js/utils.js
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-workspace/test/results/linux.docker.json
  packages/perspective/src/config/common.config.js
  yarn.lock
Labels: JS, cla-present, enhancement

#1074 Use local time for column/row headers and computed functions
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/computed.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/include/perspective/base.h
  docs/i18n/en.json
  docs/md/python.md
  packages/perspective-viewer/README.md
  packages/perspective-viewer/src/js/autocomplete_widget.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/test/js/unit/computed_expressions_parser.spec.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective/README.md
  packages/perspective/src/js/perspective.js
  python/perspective/perspective/include/perspective/python/column.h
  python/perspective/perspective/tests/manager/test_manager.py
  python/perspective/perspective/tests/table/test_table_datetime.py
  python/perspective/perspective/tests/table/test_view.py
Labels: Python, bug, cla-present, documentation, internal

#1078 Fix for CRLF issue
  .eslintrc.json
  .gitattributes
Labels: JS, cla-present, enhancement

#1103 Fix #1068
  cpp/perspective/src/cpp/extract_aggregate.cpp
Labels: cla-present

#1083 Spelling fixes
  docs/md/concepts.md
  docs/md/js.md
  docs/md/python.md
Labels: documentation

#1093 Spell-Fix
  docs/md/python.md
Labels: documentation

#1077 Refactor manager internal API, speed up string filters in UI, add manager API tests
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/test/js/unit/dom_element.spec.js
  python/perspective/perspective/core/data/np.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/manager/session.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_callback_cache.py
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/manager/test_manager.py
  python/perspective/perspective/tests/manager/test_session.py
  python/perspective/perspective/tests/table/test_table_arrow.py
  python/perspective/perspective/tests/table/test_table_datetime.py
  python/perspective/perspective/tests/table/test_table_numpy.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_to_format.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/perspective/tests/table/test_view_computed.py
  python/perspective/perspective/viewer/validate.py
Labels: JS, Python, cla-present, internal

#1090 Computed expressions respect left-to-right associativity and operator precedence
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/computed_expressions/computed_expression_parser.js
  packages/perspective-viewer/src/js/computed_expressions/lexer.js
  packages/perspective-viewer/src/js/computed_expressions/parser.js
  packages/perspective-viewer/src/js/computed_expressions/widget.js
  packages/perspective-viewer/test/js/computed_expressions.spec.js
  packages/perspective-viewer/test/js/unit/computed_expressions_parser.spec.js
  packages/perspective-viewer/test/js/unit/invariant_computed_expressions_parser.spec.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective/package.json
  packages/perspective/test/js/delta.js
Labels: JS, cla-present, enhancement

#1091 Cleans up CMakeLists & Python build scripts, fixes datetime string rendering
  azure-pipelines.yml
  cmake/arrow/CMakeLists.txt
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/arrow_loader.cpp
  cpp/perspective/src/cpp/computed.cpp
  cpp/perspective/src/cpp/scalar.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/tests/conftest.py
  python/perspective/perspective/tests/table/test_table_arrow.py
  python/perspective/perspective/tests/table/test_table_datetime.py
  python/perspective/perspective/tests/table/test_update_arrow.py
  python/perspective/perspective/tests/table/test_view.py
  scripts/build_python.js
  scripts/script_utils.js
  scripts/test_python.js
Labels: C++, Python, cla-present, internal

#1104 Unpin arrow version
  cmake/modules/FindPyArrow.cmake
  cpp/perspective/CMakeLists.txt
Labels: cla-present
