Repository finos/perspective, pull requests merged in 2020-12, with the labels that each got.

#1253 Update Azure Windows boost to 1.72
  azure-pipelines.yml
Labels: Python, cla-present, internal

#1248 Fix #1241 - date and datetime values in client mode are parsed properly
  python/perspective/perspective/tests/client_mode/test_client_mode.py
  python/perspective/perspective/widget/widget.py
Labels: 0.6.0, bug, cla-present

#1240 Remove host_view and open_view from public API
  docs/i18n/en.json
  docs/md/js.md
  docs/md/python.md
  examples/git-history/chained.html
  examples/remote-express-typescript/assets/index.html
  examples/remote-express/index.html
  examples/remote-workspace/server.js
  examples/remote-workspace/src/index.js
  examples/tornado-python/client_server_editing.html
  examples/tornado-python/index.html
  examples/tornado-python/server.py
  examples/workspace-editing-python/src/index.js
  examples/workspace-editing-python/src/server.py
  packages/perspective-jupyterlab/src/ts/view.ts
  packages/perspective-jupyterlab/test/js/unit/view.spec.js
  packages/perspective/README.md
  packages/perspective/index.d.ts
  packages/perspective/src/js/api/client.js
  packages/perspective/src/js/websocket/manager.js
  python/perspective/bench/tornado/async_server.py
  python/perspective/bench/tornado/distributed_mode.py
  python/perspective/perspective/client/client.py
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/manager/session.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/manager/test_manager.py
  python/perspective/perspective/tests/manager/test_session.py
  python/perspective/perspective/tests/viewer/test_viewer.py
  python/perspective/perspective/tests/widget/test_widget.py
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/widget/widget.py
Labels: JS, Python, breaking, cla-present

#1249 Fix #1213 - improve render warning behavior
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/js/charts/area.js
  packages/perspective-viewer-d3fc/src/js/charts/bar.js
  packages/perspective-viewer-d3fc/src/js/charts/candlestick.js
  packages/perspective-viewer-d3fc/src/js/charts/column.js
  packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/js/charts/ohlc.js
  packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
  packages/perspective-viewer-d3fc/src/js/charts/treemap.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-line.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/charts/y-scatter.js
  packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/heatmap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/yscatter.spec.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer/src/html/viewer.html
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/test/js/render_warning_tests.js
  packages/perspective-viewer/test/js/unit/perspective_element.spec.js
Labels: 0.6.0, JS, cla-present, enhancement

#1264 Fix flapping tests for render warnings
  packages/perspective-viewer/test/js/render_warning_tests.js
  packages/perspective/test/js/pivots.js
Labels: cla-present

#1231 Restrict `viewer.load()` to only accept `Table()`
  docs/md/js.md
  examples/blocks/package.json
  examples/blocks/src/csv/csv.js
  examples/blocks/src/custom/index.html
  packages/perspective-jupyterlab/src/config/plugin.config.js
  packages/perspective-jupyterlab/src/config/webpack.config.js
  packages/perspective-jupyterlab/src/ts/psp_widget.ts
  packages/perspective-jupyterlab/src/ts/view.ts
  packages/perspective-jupyterlab/test/html/resize.html
  packages/perspective-jupyterlab/test/js/unit/view.spec.js
  packages/perspective-viewer-d3fc/test/html/shares-template.html
  packages/perspective-viewer-d3fc/test/html/simple-template.html
  packages/perspective-viewer-d3fc/test/html/themed-template.html
  packages/perspective-viewer-datagrid/test/html/superstore.html
  packages/perspective-viewer/index.d.ts
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/test/html/blank.html
  packages/perspective-viewer/test/html/superstore.html
  packages/perspective-viewer/test/js/leaks.spec.js
  packages/perspective-viewer/test/js/mutation_tests.js
  packages/perspective-viewer/test/js/regressions.spec.js
  packages/perspective-viewer/test/js/slow.spec.js
  packages/perspective/index.d.ts
  packages/perspective/src/config/common.config.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/view_formatters.js
  packages/perspective/test/js/leaks.spec.js
Labels: JS, breaking, cla-present
