Repository finos/perspective, pull requests merged in 2020-05, with the labels that each got.

#975 Reference python objects directly in perspective tables
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/column.cpp
  cpp/perspective/src/cpp/context_iterators.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/column.h
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/first.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/raw_types.h
  cpp/perspective/src/include/perspective/scalar.h
  docs/md/python.md
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/column.h
  python/perspective/perspective/include/perspective/python/numpy.h
  python/perspective/perspective/include/perspective/python/utils.h
  python/perspective/perspective/src/accessor.cpp
  python/perspective/perspective/src/column.cpp
  python/perspective/perspective/src/fill.cpp
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/src/serialization.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/table/object_sequence.py
  python/perspective/perspective/tests/table/test_table_object.py
Labels: C++, Python, cla-present, enhancement

#1033 Upgrade `papaparse`
  packages/perspective/package.json
  yarn.lock
Labels: cla-present

#1028 Fix minor bugs in Perspective datetime + NaN handling
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/tests/manager/test_manager.py
  python/perspective/perspective/tests/table/test_table_arrow.py
  python/perspective/perspective/tests/table/test_table_datetime.py
  python/perspective/perspective/tests/table/test_table_infer.py
Labels: Python, cla-present, internal

#1029 Add plugin save and restore api to `perspective-viewer-datagrid`
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/js/events.js
  packages/perspective-viewer-datagrid/src/js/index.js
Labels: cla-present

#1031 Add abs sum as an aggregator
  cpp/perspective/src/cpp/aggspec.cpp
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/config.cpp
  cpp/perspective/src/cpp/extract_aggregate.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/include/perspective/base.h
  python/perspective/perspective/core/aggregate.py
Labels: cla-present

#1040 Adds jsdelivr package.json metadata
  packages/perspective-bench/package.json
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer/package.json
  packages/perspective-workspace/package.json
  packages/perspective/package.json
Labels: cla-present

#1044 Remove duplicate `psp_okey` column from arrow updates
  cpp/perspective/src/cpp/emscripten.cpp
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/tests/table/test_update_arrow.py
Labels: cla-present

#1052 Autocomplete
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/computed.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/include/perspective/base.h
  packages/perspective-test/src/js/index.js
  packages/perspective-viewer-datagrid/test/js/regressions.spec.js
  packages/perspective-viewer/src/html/autocomplete_widget.html
  packages/perspective-viewer/src/html/computed_expression_editor.html
  packages/perspective-viewer/src/html/computed_expression_widget.html
  packages/perspective-viewer/src/html/expression_editor.html
  packages/perspective-viewer/src/html/viewer.html
  packages/perspective-viewer/src/js/autocomplete_widget.js
  packages/perspective-viewer/src/js/computed_expression_editor.js
  packages/perspective-viewer/src/js/computed_expressions/computed_expression_parser.js
  packages/perspective-viewer/src/js/computed_expressions/lexer.js
  packages/perspective-viewer/src/js/computed_expressions/parser.js
  packages/perspective-viewer/src/js/computed_expressions/visitor.js
  packages/perspective-viewer/src/js/computed_expressions/widget.js
  packages/perspective-viewer/src/js/expression_editor.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/js/viewer/state_element.js
  packages/perspective-viewer/src/less/autocomplete_widget.less
  packages/perspective-viewer/src/less/computed_expression_widget.less
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/expression_editor.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/js/computed_expressions.spec.js
  packages/perspective-viewer/test/js/unit/computed_expressions_parser.spec.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/computed/functionality.js
  packages/perspective/test/js/computed/invariant.js
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/src/computed.cpp
  python/perspective/perspective/table/table.py
  yarn.lock
Labels: C++, JS, Python, cla-present, enhancement

#1058 Styleable scroll-area for `@finos/perspective-viewer-datagrid`
  packages/perspective-test/src/js/index.js
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/js/events.js
  packages/perspective-viewer-datagrid/src/js/index.js
  packages/perspective-viewer-datagrid/src/js/scroll_panel.js
  packages/perspective-viewer-datagrid/src/js/table.js
  packages/perspective-viewer-datagrid/src/js/tbody.js
  packages/perspective-viewer-datagrid/src/js/thead.js
  packages/perspective-viewer-datagrid/src/less/container.less
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/test/js/scrolling.spec.js
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/html/viewer.html
  packages/perspective-webpack-plugin/README.md
  packages/perspective-workspace/src/js/workspace/workspace.js
Labels: cla-present

#1062 Fixed typo on documentation page
  docs/md/js.md
Labels: documentation

#1065 Fix regression in regex for Firefox
  packages/perspective-viewer/src/js/computed_expressions/lexer.js
  packages/perspective-viewer/src/js/computed_expressions/widget.js
Labels: JS, bug, cla-present, internal

#1046 Remap lab extension command in makefile
  python/perspective/Makefile
Labels: Python, cla-present, internal

#1027 add perspective-update-complete event example to js guide
  docs/md/js.md
Labels: JS, cla-present, enhancement
