Repository finos/perspective, pull requests merged in 2020-04, with the labels that each got.

#1000 Fix incorrect sort order when hidden, pivoted columns are sorted
  cpp/perspective/src/cpp/view_config.cpp
  packages/perspective/test/js/sort.js
  python/perspective/examples/remote.html
Labels: cla-present

#999 Add `lock` to PerspectiveManager
  python/perspective/examples/perspective_manager_lock.html
  python/perspective/examples/perspective_manager_lock.py
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/tests/manager/test_manager.py
Labels: Python, cla-present, internal

#1002 Fix column resizing when column pivots are present, and update docs and examples.
  docs/blog/2018-10-08-nyc-citibike-analysis-1.md
  docs/pages/en/index.js
  examples/simple/superstore-custom-grid.html
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/js/events.js
  packages/perspective-viewer-datagrid/src/js/scroll_panel.js
  packages/perspective-viewer-datagrid/src/js/table.js
  packages/perspective-viewer-datagrid/src/js/tbody.js
  packages/perspective-viewer-datagrid/src/js/thead.js
  packages/perspective-viewer-datagrid/src/js/tree_row_header.js
  packages/perspective-viewer-datagrid/src/js/view_model.js
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
Labels: cla-present

#1010 Add Manylinux Python 3.7 wheel build + tests, disable Azure Windows Python build
  .artifactignore
  azure-pipelines.yml
  cpp/perspective/CMakeLists.txt
  python/perspective/perspective/tests/core/test_async.py
  scripts/script_utils.js
Labels: cla-present, internal

#1017 Adds -Wall and fixes C++ build warnings
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/aggspec.cpp
  cpp/perspective/src/cpp/computed.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/base.h
Labels: cla-present

#1011 Update Python benchmarks to include results for `update` calls
  python/perspective/bench/bench.py
  python/perspective/bench/perspective_benchmark.py
  python/perspective/bench/run_perspective_benchmark.py
Labels: Python, cla-present

#1012 When updating tables typed as `int` with `float64` numpy arrays, copy instead of filling iteratively
  cpp/perspective/src/cpp/base.cpp
  python/perspective/perspective/core/data/__init__.py
  python/perspective/perspective/core/data/np.py
  python/perspective/perspective/include/perspective/python/numpy.h
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/table/test_table_numpy.py
Labels: C++, Python, cla-present, internal

#1018 Datagrid virtual scroll fixes and `-webkit-scrollbar` CSS
  packages/perspective-viewer-datagrid/src/js/scroll_panel.js
  packages/perspective-viewer-datagrid/src/js/table.js
  packages/perspective-viewer-datagrid/src/js/tbody.js
  packages/perspective-viewer-datagrid/src/less/container.less
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer/src/less/viewer.less
Labels: cla-present

#1022 Fix flapping `perspective-workspace` tests
  packages/perspective-workspace/test/html/index.html
  packages/perspective-workspace/test/js/integration/html.spec.js
  packages/perspective-workspace/test/js/integration/linked.spec.js
  packages/perspective-workspace/test/js/integration/restore.spec.js
  packages/perspective-workspace/test/results/linux.docker.json
Labels: JS, bug, internal
