Repository finos/perspective, pull requests merged in 2020-09, with the labels that each got.

#1169 Updated `@finos/perspective-viewer-datagrid` plugin to `regular-table` 0.0.9
  examples/git_history/index.html
  examples/simple/superstore.html
  package.json
  packages/perspective-test/src/js/index.js
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/index.js
  packages/perspective-viewer-datagrid/src/js/row_selection.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/test/html/superstore.html
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-workspace/src/less/viewer.less
  packages/perspective-workspace/test/results/linux.docker.json
  yarn.lock
Labels: cla-present

#1176 `perspective-viewer-datagrid` support for `editable`
  examples/simple/editable.html
  examples/simple/index.html
  examples/simple/superstore.html
  examples/workspace/src/index.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/config/cjs.config.js
  packages/perspective-viewer-datagrid/src/config/umd.config.js
  packages/perspective-viewer-datagrid/src/js/editing.js
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/row_selection.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-workspace/test/results/linux.docker.json
  yarn.lock
Labels: cla-present

#1177 Add websocket stresstests for Tornado server
  .gitignore
  package.json
  python/perspective/bench/stresstest/__init__.py
  python/perspective/bench/stresstest/client/__init__.py
  python/perspective/bench/stresstest/client/client.py
  python/perspective/bench/stresstest/client/client_runner.py
  python/perspective/bench/stresstest/client/results_schema.py
  python/perspective/bench/stresstest/host_results.py
  python/perspective/bench/stresstest/main.py
  python/perspective/bench/stresstest/results.html
  python/perspective/bench/stresstest/server/__init__.py
  python/perspective/bench/stresstest/server/manager_telemetry.py
  python/perspective/bench/stresstest/server/server.py
  python/perspective/bench/stresstest/server/superstore.arrow
  python/perspective/bench/stresstest/server/tornado_handler_telemetry.py
Labels: Python, enhancement

#1183 `perspective-workspace` CSS fixes
  examples/remote-workspace/src/index.js
  packages/perspective-viewer/src/config/umd.config.js
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective/src/js/api/server.js
Labels: cla-present

#1181 Fix `perspective-viewer-datagrid` sorting
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/sorting.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-workspace/test/results/linux.docker.json
  yarn.lock
Labels: cla-present

#1184 `promo` example project update and computed function fix
  cpp/perspective/src/cpp/computed_function.cpp
  examples/promo/script.js
  examples/promo/src/index.js
  examples/promo/webpack.config.js
  packages/perspective/src/js/perspective.js
Labels: cla-present

#1185 Fix sticky dragdrop on `perspective-viewer`
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/viewer/dragdrop.js
Labels: cla-present

#1186 D3FC render fixes
  packages/perspective-viewer-d3fc/src/js/charts/treemap.js
  packages/perspective-viewer-d3fc/src/js/layout/gridLayoutMultiChart.js
  packages/perspective-viewer-d3fc/src/js/legend/colorRangeLegend.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/js/integration/treemap.spec.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
Labels: JS, bug, cla-present, d3fc

#1187 Datagrid overdraw fix
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-workspace/test/results/linux.docker.json
  yarn.lock
Labels: cla-present

#1194 Remove linking against python
  cpp/perspective/CMakeLists.txt
Labels: Python, bug, cla-present

#1193 add some build troubleshooting docs
  docs/i18n/en.json
  docs/md/development.md
  docs/md/installation.md
Labels: cla-present, documentation

#1195 Server mode for Jupyterlab `PerspectiveWidget`
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/less/index.less
  packages/perspective-jupyterlab/src/ts/client.ts
  packages/perspective-jupyterlab/src/ts/model.ts
  packages/perspective-jupyterlab/src/ts/psp_widget.ts
  packages/perspective-jupyterlab/src/ts/view.ts
  packages/perspective-jupyterlab/test/config/jest.config.js
  packages/perspective-jupyterlab/test/js/mocks/manager.js
  packages/perspective-jupyterlab/test/js/unit/client.spec.js
  packages/perspective-jupyterlab/test/js/unit/view.spec.js
  packages/perspective-test/jest.all.config.js
  packages/perspective-test/jest.config.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer/index.d.ts
  packages/perspective/index.d.ts
  python/perspective/perspective/core/plugin.py
  python/perspective/perspective/table/__init__.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/core/test_plugin.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_to_format.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/tests/viewer/test_validate.py
  python/perspective/perspective/tests/viewer/test_viewer.py
  python/perspective/perspective/tests/widget/test_widget.py
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/viewer/viewer_traitlets.py
  python/perspective/perspective/widget/widget.py
  scripts/test_js.js
  yarn.lock
Labels: cla-present

#1200 `perspective-python` Client fixes
  python/perspective/perspective/client/client.py
  python/perspective/perspective/client/dispatch.py
  python/perspective/perspective/client/table_api.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/tests/client/__init__.py
  python/perspective/perspective/tests/client/test_client.py
  python/perspective/perspective/tests/tornado_handler/test_tornado_handler.py
  python/perspective/perspective/tornado_handler/tornado_client.py
Labels: cla-present

#1198 GIL release for perspective-python Async mode
  docs/md/python.md
  examples/tornado-python/server.py
  examples/tornado-streaming-python/server.py
  packages/perspective/src/js/api/client.js
  python/perspective/bench/giltest.py
  python/perspective/perspective/client/client.py
  python/perspective/perspective/client/dispatch.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/utils.h
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/src/serialization.cpp
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/tests/core/test_async.py
  python/perspective/perspective/tests/manager/test_manager.py
  python/perspective/perspective/tornado_handler/tornado_client.py
  python/perspective/perspective/tornado_handler/tornado_handler.py
  scripts/bench.js
Labels: cla-present

#1202 Release GIL for `Table` methods
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/pyutils.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/pool.h
  cpp/perspective/src/include/perspective/pyutils.h
  cpp/perspective/src/include/perspective/view.h
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/serialization.h
  python/perspective/perspective/include/perspective/python/table.h
  python/perspective/perspective/include/perspective/python/utils.h
  python/perspective/perspective/include/perspective/python/view.h
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/src/serialization.cpp
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/tests/core/test_async.py
Labels: Python, cla-present, enhancement

#1203 Upgrade to regular-table 0.1.5 and fix custom-style example
  examples/blocks/src/custom/index.html
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
  yarn.lock
Labels: cla-present

#1204 Fix typo, update arrow version info.
  docs/md/installation.md
Labels: cla-present
