Repository finos/perspective, pull requests merged in 2020-03, with the labels that each got.

#961 Fully clear queued updates before adding a new computed column
  cpp/perspective/src/cpp/computed.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  examples/simple/streaming.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/computed.js
Labels: cla-present

#957 Add ==, !=, >, <, and string equality computed columns
  cpp/perspective/src/cpp/computed.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/computed.h
  cpp/perspective/src/include/perspective/computed_function.h
  packages/perspective-viewer/src/js/computed_column.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/computed.js
Labels: JS, cla-present, enhancement

#963 Refactor out `WebsSocketManager` from `WebSockerServer`
  examples/datasources/index.js
  examples/datasources/securities.js
  examples/remote-express/README.md
  examples/remote-express/index.css
  examples/remote-express/index.html
  examples/remote-express/package.json
  examples/remote-express/server.js
  examples/remote/server.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
  packages/perspective/src/js/websocket.js
  packages/perspective/test/js/remote.spec.js
  yarn.lock
Labels: JS, cla-present, enhancement

#965 PerspectiveManager no longer treats `str` as `bytes` in Python 2
  python/perspective/perspective/manager/manager.py
Labels: Python, bug, cla-present

#954 New plugin `@finos/perspective-viewer-datagrid`
  examples/simple/superstore-custom-grid.html
  examples/simple/superstore-datagrid.html
  packages/perspective-test/jest.all.config.js
  packages/perspective-viewer-datagrid/babel.config.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/config/cjs.config.js
  packages/perspective-viewer-datagrid/src/config/umd.config.js
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/less/container.less
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/test/html/empty.html
  packages/perspective-viewer-datagrid/test/html/regressions.html
  packages/perspective-viewer-datagrid/test/html/superstore.html
  packages/perspective-viewer-datagrid/test/js/regressions.spec.js
  packages/perspective-viewer-datagrid/test/js/slow.spec.js
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  packages/perspective-viewer-datagrid/test/js/utils.js
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective/src/js/perspective.node.js
  scripts/setup.js
Labels: JS, WIP, cla-present, enhancement

#967 Datagrid header click-to-sort and assorted improvements
  examples/simple/superstore-custom-grid.html
  examples/simple/superstore-datagrid.html
  examples/simple/superstore-hypergrid.html
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/config/umd.config.js
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/less/container.less
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
Labels: JS, cla-present, enhancement

#969 Add `linked` filter mode to `perspective-workspace`
  packages/perspective-workspace/src/js/workspace/commands.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/theme/material.less
  packages/perspective-workspace/test/js/integration/linked.spec.js
  packages/perspective-workspace/test/js/unit/workspace.spec.js
  packages/perspective-workspace/test/results/linux.docker.json
Labels: JS, cla-present, enhancement

#977 Update azure-pipelines.yml for Azure Pipelines
  azure-pipelines.yml
Labels: bug, cla-present, internal

#973 Remove duplicate brew instructions
  docs/md/development.md
Labels: cla-present, documentation, enhancement

#970 update dependencies to jupyterlab 2.0, phosphor -> lumino
  examples/promo/src/index.js
  examples/promo/webpack.config.js
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/config/plugin.config.js
  packages/perspective-jupyterlab/src/config/webpack.config.js
  packages/perspective-jupyterlab/src/ts/plugin.ts
  packages/perspective-jupyterlab/src/ts/psp_widget.ts
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective-jupyterlab/test/html/resize.html
  packages/perspective-workspace/package.json
  packages/perspective-workspace/src/js/index.js
  packages/perspective-workspace/src/js/workspace/commands.js
  packages/perspective-workspace/src/js/workspace/discrete.js
  packages/perspective-workspace/src/js/workspace/dockpanel.js
  packages/perspective-workspace/src/js/workspace/menu.js
  packages/perspective-workspace/src/js/workspace/tabbar.js
  packages/perspective-workspace/src/js/workspace/tabbarrenderer.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/workspace.less
  packages/perspective-workspace/test/js/unit/workspace.spec.js
  yarn.lock
Labels: JS, cla-present, enhancement

#979 Datagrid row selection and column resize
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/themes/material.dark.less
Labels: JS, cla-present, enhancement

#980 Update typings to include nodejs only components
  examples/remote-express-typescript/assets/index.css
  examples/remote-express-typescript/assets/index.html
  examples/remote-express-typescript/package.json
  examples/remote-express-typescript/src/server.ts
  examples/remote-express-typescript/tsconfig.json
  package.json
  packages/perspective/index.d.ts
  yarn.lock
Labels: cla-present

#982 remove cpp test check from setup.py (no more cpp tests)
  python/perspective/setup.py
Labels: Python, bug, cla-present

#987 Documentation: update PerspectiveTornadoServer to PerspectiveTornadoHandler
  docs/md/js.md
  docs/md/python.md
Labels: Python, documentation

#990 perspective-workspace fixes
  examples/remote-workspace/package.json
  examples/remote-workspace/server.js
  examples/remote-workspace/src/index.js
  examples/remote-workspace/src/index.less
  examples/remote-workspace/webpack.config.js
  examples/remote/README.md
  examples/remote/index.css
  examples/remote/index.html
  examples/remote/package.json
  examples/remote/server.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/test/js/unit/__mocks__/@finos/perspective-viewer.js
  packages/perspective-workspace/test/results/linux.docker.json
Labels: JS, bug, cla-present

#985 tweak accessor to accept numpy dict
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/tests/table/test_update_numpy.py
Labels: Python, bug, cla-present

#992 Add config validation for 'sizes' and other minor fixes
  examples/workspace-typescript/package.json
  examples/workspace-typescript/src/index.html
  examples/workspace-typescript/src/index.less
  examples/workspace-typescript/src/index.ts
  examples/workspace-typescript/webpack.config.js
  packages/perspective-workspace/index.d.ts
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/test/js/unit/workspace.spec.js
Labels: JS, cla-present

#993 `@finos/perspective-viewer-datagrid` Tree Formatting
  README.md
  examples/simple/superstore.html
  packages/perspective-viewer-datagrid/babel-plugin-transform-tagged-literal.js
  packages/perspective-viewer-datagrid/babel.config.js
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/js/events.js
  packages/perspective-viewer-datagrid/src/js/scroll_panel.js
  packages/perspective-viewer-datagrid/src/js/table.js
  packages/perspective-viewer-datagrid/src/js/tbody.js
  packages/perspective-viewer-datagrid/src/js/thead.js
  packages/perspective-viewer-datagrid/src/js/tree_row_header.js
  packages/perspective-viewer-datagrid/src/js/utils.js
  packages/perspective-viewer-datagrid/src/js/view_model.js
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/js/viewer.js
Labels: JS, cla-present, enhancement

#995 Look for PyArrow relative to Perspective in @rpath
  cpp/perspective/CMakeLists.txt
  package.json
  scripts/_wheel_python.js
Labels: C++, Python, cla-present, internal

#997 `@finos/perspective-viewer-datagrid` Bug Fixes
  examples/simple/superstore-custom-grid.html
  packages/perspective-viewer-datagrid/src/js/constants.js
  packages/perspective-viewer-datagrid/src/js/datagrid.js
  packages/perspective-viewer-datagrid/src/js/index.js
  packages/perspective-viewer-datagrid/src/js/scroll_panel.js
  packages/perspective-viewer-datagrid/src/js/table.js
  packages/perspective-viewer-datagrid/src/js/tbody.js
  packages/perspective-viewer-datagrid/src/js/tree_row_header.js
  packages/perspective-viewer-datagrid/src/less/container.less
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
Labels: cla-present
