Repository finos/perspective, pull requests merged in 2020-02, with the labels that each got.

#890 Style fixes for `perspective-workspace`
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/less/viewer.less
  packages/perspective-workspace/src/less/widget.less
  packages/perspective-workspace/src/less/workspace.less
  packages/perspective-workspace/test/results/linux.docker.json
Labels: JS, cla-present, enhancement

#893 Update Python README
  docs/md/installation.md
  python/perspective/README.md
  python/perspective/setup.py
Labels: cla-present

#895 Better test screenshot archiving.
  packages/perspective-test/src/js/index.js
  packages/perspective-test/src/js/reporter.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-highcharts/test/results/linux.docker.json
  packages/perspective-viewer-hypergrid/test/results/linux.docker.json
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/test/results/linux.docker.json
  scripts/clean.js
Labels: cla-present

#881 Allow missing columns
  package.json
  packages/perspective-test/babel.config.js
  packages/perspective-test/src/js/index.js
  packages/perspective-test/src/js/mouse_helper.js
  packages/perspective-viewer-d3fc/babel.config.js
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
  packages/perspective-viewer-d3fc/src/js/charts/treemap.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/data/pointData.js
  packages/perspective-viewer-d3fc/src/js/data/treeData.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
  packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstColor.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapColor.js
  packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/treemap.spec.js
  packages/perspective-viewer-d3fc/test/js/unit/data/testTreeData.js
  packages/perspective-viewer-d3fc/test/js/unit/data/treeData.spec.js
  packages/perspective-viewer-d3fc/test/js/unit/tooltip/tooltip.spec.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-highcharts/src/js/highcharts/config.js
  packages/perspective-viewer-highcharts/src/js/highcharts/draw.js
  packages/perspective-viewer-highcharts/src/js/highcharts/highcharts.js
  packages/perspective-viewer-highcharts/src/js/highcharts/series.js
  packages/perspective-viewer-highcharts/src/js/highcharts/tooltip.js
  packages/perspective-viewer-highcharts/test/js/line.spec.js
  packages/perspective-viewer-highcharts/test/js/scatter.spec.js
  packages/perspective-viewer-highcharts/test/results/linux.docker.json
  packages/perspective-viewer-hypergrid/test/results/linux.docker.json
  packages/perspective-viewer/babel.config.js
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/dragdrop.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/js/viewer/state_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/test/results/linux.docker.json
  yarn.lock
Labels: JS, cla-present, enhancement

#894 Add 'perspective-select' event to `@finos/perspective-viewer-hypergrid`
  examples/workspace/webpack.config.js
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/test/js/selection.spec.js
  packages/perspective-viewer-hypergrid/test/results/linux.docker.json
  packages/perspective-workspace/src/js/workspace/workspace.js
Labels: JS, cla-present, enhancement

#891 Make `@finos/perspective-workspace` widget title editable by doubleclick
  packages/perspective-workspace/src/js/workspace/tabbar.js
  packages/perspective-workspace/src/js/workspace/tabbarrenderer.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/test/results/linux.docker.json
Labels: JS, cla-present, enhancement

#892 Implement computed column functions in C++
  .clang-format
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/column.cpp
  cpp/perspective/src/cpp/computed.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/computed.h
  cpp/perspective/src/include/perspective/computed_function.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/pool.h
  cpp/perspective/src/include/perspective/raw_types.h
  cpp/perspective/src/include/perspective/table.h
  cpp/perspective/src/include/perspective/view.h
  cpp/perspective/src/include/perspective/view_config.h
  examples/simple/all_numeric_types.arrow
  examples/simple/arrow.html
  packages/perspective-bench/bench/perspective.benchmark.js
  packages/perspective-bench/bench/versions.js
  packages/perspective-viewer/src/js/computed_column.js
  packages/perspective-viewer/src/js/computed_column/computation.js
  packages/perspective-viewer/src/js/computed_column/state.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/test/js/computed_columns.spec.js
  packages/perspective/index.d.ts
  packages/perspective/src/js/config/constants.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/utils.js
  packages/perspective/test/arrow/number_types.arrow
  packages/perspective/test/js/computed.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/test_arrows.js
  python/perspective/perspective/core/aggregate.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/context.h
  python/perspective/perspective/include/perspective/python/view.h
  python/perspective/perspective/src/context.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/tests/table/test_to_arrow.py
Labels: C++, cla-present, internal

#896 implement save/restore on viewer configuration
  python/perspective/perspective/tests/viewer/test_viewer.py
  python/perspective/perspective/viewer/viewer.py
Labels: Python, cla-present, enhancement

#899 Fix #898 - week bucket overflows
  cpp/perspective/src/cpp/computed_function.cpp
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective/test/js/computed.js
Labels: C++, bug, cla-present

#905 `<perspective-viewer>` UI cleanup
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-highcharts/test/results/linux.docker.json
  packages/perspective-viewer-hypergrid/babel.config.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/test/results/linux.docker.json
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material-dense.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/babel.config.js
  packages/perspective-workspace/package.json
  packages/perspective-workspace/src/js/workspace/tabbar.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/less/viewer.less
Labels: cla-present

#903 Make `perspective-viewer-hypergrid` selection state save/restore compatible
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/test/js/selection.spec.js
  packages/perspective-viewer-hypergrid/test/results/linux.docker.json
Labels: JS, cla-present, enhancement

#906 Bump core-js to v3.6.4 and Babel to 7.8.4
  docs/package.json
  package.json
  packages/perspective-bench/package.json
  packages/perspective-cli/babel.config.js
  packages/perspective-cli/package.json
  packages/perspective-test/babel.config.js
  packages/perspective-test/package.json
  packages/perspective-viewer-d3fc/babel.config.js
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-highcharts/babel.config.js
  packages/perspective-viewer-highcharts/package.json
  packages/perspective-viewer-hypergrid/babel.config.js
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer/babel.config.js
  packages/perspective-viewer/package.json
  packages/perspective-workspace/babel.config.js
  packages/perspective-workspace/package.json
  packages/perspective/babel.config.js
  packages/perspective/package.json
  yarn.lock
Labels: JS, cla-present, internal

#908 Remove yarn dependency duplication.
  package.json
  yarn.lock
Labels: cla-present

#884 updates and fixes for windows build
  .appveyor.yml
  cmake/modules/FindPyArrow.cmake
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/include/perspective/scalar.h
  cpp/perspective/src/include/perspective/sym_table.h
  cpp/perspective/src/include/perspective/view_config.h
  python/perspective/README.md
  python/perspective/package.json
  python/perspective/perspective/include/perspective/python/numpy.h
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/tests/client/test_client.py
  python/perspective/perspective/tests/table/test_table_datetime.py
  python/perspective/setup.py
  scripts/script_utils.js
  scripts/test_python.js
  yarn.lock
Labels: C++, Python, cla-present, enhancement

#902 Add 'workspace-layout-update' event and css class selector names cleanup
  examples/workspace/src/index.js
  packages/perspective-workspace/src/js/workspace/commands.js
  packages/perspective-workspace/src/js/workspace/discrete.js
  packages/perspective-workspace/src/js/workspace/dockpanel.js
  packages/perspective-workspace/src/js/workspace/menu.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/dockpanel.less
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/less/viewer.less
  packages/perspective-workspace/src/less/widget.less
  packages/perspective-workspace/src/less/workspace.less
  packages/perspective-workspace/src/theme/material.less
  packages/perspective-workspace/src/theme/vaporwave.less
  packages/perspective-workspace/test/js/integration/restore.spec.js
  packages/perspective-workspace/test/js/unit/workspace.spec.js
Labels: JS, cla-present, enhancement

#907 Fix column ordering in Python, null handling for computed columns
  cpp/perspective/src/cpp/computed_function.cpp
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective/test/js/computed.js
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/tests/table/test_table_numpy.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/perspective/tornado_handler/tornado_handler.py
Labels: C++, JS, Python, bug, cla-present, internal

#912 Remove `perspective.node` Python module.
  python/perspective/js/server.js
  python/perspective/package.json
  python/perspective/perspective/node/__init__.py
  python/perspective/perspective/tests/node/__init__.py
  python/perspective/perspective/tests/node/test_node.py
  python/perspective/webpack.config.js
  yarn.lock
Labels: Python, cla-present, enhancement

#914 `perspective-viewer-hypergrid` Tree column toggle buttons.
  examples/simple/superstore-arrow.html
  examples/simple/superstore-hypergrid.html
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-highcharts/test/results/linux.docker.json
  packages/perspective-viewer-hypergrid/package.json
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/test/results/linux.docker.json
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/computed_column.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/less/dockpanel.less
  packages/perspective-workspace/src/less/viewer.less
  packages/perspective-workspace/src/theme/material.less
  packages/perspective-workspace/test/results/linux.docker.json
  yarn.lock
Labels: JS, enhancement

#901 Custom Element API for `<perspective-workspace>`
  examples/workspace/src/index.js
  packages/perspective-workspace/src/js/index.js
  packages/perspective-workspace/src/js/workspace/tabbar.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/test/html/index.html
  packages/perspective-workspace/test/js/integration/dom.spec.js
  packages/perspective-workspace/test/js/integration/html.spec.js
  packages/perspective-workspace/test/js/integration/restore.spec.js
  packages/perspective-workspace/test/js/unit/workspace.spec.js
  packages/perspective-workspace/test/results/linux.docker.json
Labels: JS, cla-present, enhancement

#915 Set up CI with Azure Pipelines
  .appveyor.yml
  .travis.yml
  README.md
  azure-pipelines.yml
  cpp/perspective/CMakeLists.txt
  python/perspective/setup.py
  scripts/build_js.js
  scripts/script_utils.js
Labels: WIP, cla-present, internal

#911 Fix bug where `perspective-viewer` doesn't resize
  packages/perspective-viewer/src/js/viewer/dom_element.js
Labels: cla-present

#916 Added Azure compatible reporting for tests
  azure-pipelines.yml
  package.json
  packages/perspective-test/jest.all.config.js
  scripts/build_python.js
  yarn.lock
Labels: cla-present, internal

#918 adding sdist check so we don't deploy broken sdists accidentally
  python/perspective/setup.py
Labels: Python, cla-present, enhancement

#922 Event regression fix
  cpp/perspective/src/cpp/view_config.cpp
  packages/perspective-viewer-d3fc/src/js/axis/ordinalAxis.js
  packages/perspective-workspace/src/js/workspace/workspace.js
Labels: cla-present

#920 Adds test coverage reporting for`@finos/perspective`
  .gitignore
  README.md
  azure-pipelines.yml
  package.json
  packages/perspective-test/jest.all.config.js
  packages/perspective-webpack-plugin/package.json
  packages/perspective/babel.config.js
  packages/perspective/package.json
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.wasm.js
  packages/perspective/src/js/psp.async.wasm.js
  packages/perspective/test/js/perspective.spec.js
  packages/perspective/test/js/sync_load.spec.js
  scripts/build_js.js
  yarn.lock
Labels: JS, cla-present, internal, tests

#925 Fix `perspective-workspace` non-unique generated slotid bug
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/test/js/integration/restore.spec.js
  packages/perspective-workspace/test/results/linux.docker.json
Labels: cla-present

#923 Fix for #921: unifies versioning between JS and Python libraries
  package.json
  python/perspective/.bumpversion.cfg
  python/perspective/MANIFEST.in
  python/perspective/docs/conf.py
  python/perspective/perspective/core/_version.py
  python/perspective/perspective/widget/widget.py
  python/perspective/scripts/write_version.py
  scripts/docs.js
  scripts/version_python.js
Labels: Python, cla-present, enhancement

#927 Remove some stale code
  python/perspective/requirements-dev.txt
  python/perspective/requirements.txt
  python/perspective/setup.py
Labels: Python, cla-present, enhancement

#930 Package/dist license in python package
  python/perspective/MANIFEST.in
  scripts/build_python.js
Labels: Python, cla-present, documentation

#924 Fix `perspective-workspace` initialize bug
  examples/workspace/src/index.html
  examples/workspace/src/index.js
  examples/workspace/webpack.config.js
  packages/perspective-workspace/src/js/index.js
Labels: JS, bug, cla-present

#934 Fix widget title in `perspective-workspace`
  packages/perspective-workspace/package.json
  packages/perspective-workspace/src/js/workspace/tabbar.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
Labels: JS, bug, cla-present

#943 Deal with np.int_ on Windows, handle missing __INDEX__
  azure-pipelines.yml
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/table/test_to_format.py
Labels: Python, bug, cla-present

#947 Fix #945: Improve Python install docs
  python/perspective/README.md
Labels: Python, cla-present, documentation

#946 Fix tables `delete` bug in `perspective-workspace`
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/test/js/unit/__mocks__/@finos/perspective-viewer.js
  packages/perspective-workspace/test/js/unit/tables.spec.js
Labels: JS, bug, cla-present

#949 Activate Perspective in FINOS Foundation
  README.md
Labels: cla-present

#948 Fixes off-by-one error in `end_col`
  packages/perspective-webpack-plugin/src/js/switch-inline-loader.js
  packages/perspective-workspace/src/js/index.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/to_format_viewport.spec.js
  yarn.lock
Labels: cla-present, internal

#939 Refactor `gnode` and `gnode_state`, remove C++ test suite
  cmake/GTest.txt.in
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/process_state.cpp
  cpp/perspective/src/cpp/schema.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/context_base.h
  cpp/perspective/src/include/perspective/context_one.h
  cpp/perspective/src/include/perspective/flat_traversal.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/pool.h
  cpp/perspective/src/include/perspective/process_state.h
  cpp/perspective/src/include/perspective/schema.h
  cpp/perspective/test/CMakeLists.txt
  cpp/perspective/test/cpp/psp.cpp
  cpp/perspective/test/cpp/simple.cpp
  cpp/perspective/test/include/perspective/simple.h
  cpp/perspective/test/include/perspective/test_utils.h
  examples/simple/streaming.js
  packages/perspective-bench/bench/perspective.benchmark.js
  packages/perspective-bench/bench/versions.js
  packages/perspective/src/js/perspective.js
  python/perspective/bench/bench.py
  python/perspective/bench/benchmark_hosted.html
  python/perspective/bench/perspective_benchmark.py
  python/perspective/bench/run_perspective_benchmark.py
  python/perspective/perspective/libpsp.py
  python/perspective/perspective/src/table.cpp
  python/perspective/setup.py
  scripts/setup.js
  scripts/test_js.js
Labels: C++, cla-present, internal

#953 Bugfix sdist
  cpp/perspective/CMakeLists.txt
  python/perspective/MANIFEST.in
  python/perspective/setup.py
Labels: Python, bug, cla-present

#956 Emit source maps for WebWorker.
  packages/perspective-webpack-plugin/src/js/psp-worker-loader.js
Labels: JS, bug, cla-present
