Repository finos/perspective, pull requests merged in 2020-10, with the labels that each got.

#1207 Upgrade WebAssembly build to Arrow 1.0.1
  cmake/arrow.txt.in
  cmake/arrow/CMakeLists.txt
  cmake/arrow/config.h
  cmake/modules/FindFlatbuffers.cmake
  cmake/modules/FindPyArrow.cmake
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/arrow_csv.cpp
  cpp/perspective/src/cpp/arrow_loader.cpp
  cpp/perspective/src/cpp/arrow_writer.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/vendor/arrow_single_threaded_reader.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/arrow_csv.h
  cpp/perspective/src/include/perspective/arrow_loader.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/vendor/arrow_single_threaded_reader.h
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective/README.md
  packages/perspective/package.json
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/view_formatters.js
  scripts/bench.js
Labels: cla-present

#1214 Fix `computed-column` and `table()` constructor Javascript bugs
  azure-pipelines.yml
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/include/perspective/pyutils.h
  packages/perspective/src/js/api/server.js
  packages/perspective/test/js/constructors.js
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/tests/table/test_view_computed.py
  scripts/build_python.js
Labels: cla-present

#1212 Add `perspective-plugin-update` event for d3fc
  examples/workspace/src/index.js
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
  packages/perspective-workspace/src/js/workspace/tabbar.js
  packages/perspective-workspace/src/js/workspace/workspace.js
Labels: cla-present

#1209 Send large arrow binaries as chunks, add client-level Websocket heartbeat
  examples/tornado-python/server.py
  packages/perspective-jupyterlab/src/ts/client.ts
  packages/perspective-jupyterlab/src/ts/view.ts
  packages/perspective-jupyterlab/test/js/unit/view.spec.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/websocket.js
  packages/perspective/test/js/remote.spec.js
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/tests/tornado_handler/test_tornado_handler.py
  python/perspective/perspective/tests/tornado_handler/test_tornado_handler_chunked.py
  python/perspective/perspective/tornado_handler/tornado_client.py
  python/perspective/perspective/tornado_handler/tornado_handler.py
  python/perspective/perspective/widget/widget.py
Labels: cla-present

#1217 adding binder link
  README.md
  binder/apt.txt
  binder/postBuild
  binder/requirements.txt
  binder/runtime.txt
  python/perspective/README.md
Labels: Jupyter, cla-present, documentation, enhancement

#1219 Fix infinite loop bug in 2-sided context
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  python/perspective/perspective/tests/table/test_view.py
Labels: Python, bug, cla-present

#1220 C++ Datetime Parsing
  cpp/perspective/src/cpp/arrow_csv.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/include/perspective/arrow_csv.h
  packages/perspective/package.json
  packages/perspective/src/js/data_accessor/date_parser.js
  packages/perspective/src/js/data_accessor/index.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/view_formatters.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/filters.js
Labels: C++, JS, cla-present, internal

#1221 Separate 'release' and 'debug' builds
  packages/perspective/package.json
  scripts/build_js.js
  scripts/clean.js
Labels: JS, cla-present, internal

#1227 Explicitly import `tornado.locks`
  python/perspective/perspective/tornado_handler/tornado_handler.py
  python/perspective/setup.py
Labels: cla-present

#1233 Refactor C++, misc. C++ fixes
  cpp/perspective/src/cpp/aggspec.cpp
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/context_base.h
  cpp/perspective/src/include/perspective/context_common_decls.h
  cpp/perspective/src/include/perspective/context_grouped_pkey.h
  cpp/perspective/src/include/perspective/context_one.h
  cpp/perspective/src/include/perspective/context_zero.h
  cpp/perspective/src/include/perspective/first.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/sparse_tree.h
  packages/perspective-bench/bench/perspective.benchmark.js
  packages/perspective-bench/bench/versions.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
  packages/perspective/src/js/websocket/client.js
  packages/perspective/src/js/websocket/manager.js
  packages/perspective/test/js/computed/deltas.js
  packages/perspective/test/js/delta.js
  packages/perspective/test/js/updates.js
  python/perspective/perspective/src/accessor.cpp
  python/perspective/perspective/src/computed.cpp
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/src/serialization.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/table/test_view_computed.py
Labels: C++, cla-present, internal

#1230 Add `get_index()` and `get_limit()` to the public API, internal code cleanup
  packages/perspective/src/js/api/table_api.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/clear.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/updates.js
  python/perspective/perspective/client/table_api.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/manager/test_manager.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/perspective/tests/widget/test_widget.py
  python/perspective/perspective/widget/widget.py
Labels: cla-present

#1234 tweak py wheel build on linux
  cpp/perspective/CMakeLists.txt
  python/perspective/setup.py
Labels: cla-present

#1236 Fix distributed editing in PerspectiveWidget
  python/perspective/perspective/widget/widget.py
Labels: Jupyter, Python, bug

#1235 Add unit context for 0-sided views
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/config.cpp
  cpp/perspective/src/cpp/context_handle.cpp
  cpp/perspective/src/cpp/context_unit.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_slice.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/config.h
  cpp/perspective/src/include/perspective/context_unit.h
  cpp/perspective/src/include/perspective/data_slice.h
  cpp/perspective/src/include/perspective/first.h
  cpp/perspective/src/include/perspective/flat_traversal.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/view.h
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/delta.js
  packages/perspective/test/js/multiple.js
  packages/perspective/test/js/to_format.js
  packages/perspective/test/js/updates.js
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/context.h
  python/perspective/perspective/include/perspective/python/serialization.h
  python/perspective/perspective/include/perspective/python/view.h
  python/perspective/perspective/src/context.cpp
  python/perspective/perspective/src/serialization.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/perspective/tests/table/test_view_computed.py
  scripts/build_js.js
Labels: C++, JS, Python, cla-present, enhancement

#1239 Fix example notebooks
  examples/jupyter-notebooks/filters.ipynb
  examples/jupyter-notebooks/plugins.ipynb
  examples/jupyter-notebooks/table_tutorial.ipynb
  examples/jupyter-notebooks/widget_tutorial.ipynb
  python/perspective/setup.py
Labels: cla-present
