Repository finos/perspective, pull requests merged in 2020-01, with the labels that each got.

#854 Fix `perspective-viewer` to allow loading a table before it's attache…
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
Labels: JS, cla-present, enhancement

#858 Workspace fixes
  packages/perspective-bench/bench/perspective.benchmark.js
  packages/perspective-bench/bench/versions.js
  packages/perspective-bench/src/js/bench.js
  packages/perspective-bench/src/js/browser_runtime.js
  packages/perspective-phosphor/config/tsconfig.json
  packages/perspective-phosphor/config/webpack.config.js
  packages/perspective-phosphor/config/webpack.umd.config.js
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/src/less/widget.less
  packages/perspective-phosphor/src/theme/default/index.less
  packages/perspective-phosphor/src/theme/default/tabbar.less
  packages/perspective-phosphor/src/theme/material/dockpanel.less
  packages/perspective-phosphor/src/theme/material/index.less
  packages/perspective-phosphor/src/theme/material/material-phosphor.less
  packages/perspective-phosphor/src/theme/material/menu.less
  packages/perspective-phosphor/src/theme/material/tabbar.less
  packages/perspective-phosphor/src/theme/material/widget.less
  packages/perspective-phosphor/src/theme/material/workspace.less
  packages/perspective-phosphor/src/theme/vaporwave/index.less
  packages/perspective-phosphor/src/ts/dockpanel/discrete.ts
  packages/perspective-phosphor/src/ts/dockpanel/dockpanel.ts
  packages/perspective-phosphor/src/ts/dockpanel/index.ts
  packages/perspective-phosphor/src/ts/index.ts
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-phosphor/src/ts/workspace/index.ts
  packages/perspective-phosphor/src/ts/workspace/workspace.ts
  packages/perspective-phosphor/test/results/results.json
  packages/perspective-phosphor/test/unit/__mocks__/@finos/perspective-viewer.js
  packages/perspective-phosphor/test/unit/js/dockpanel.spec.js
  packages/perspective-phosphor/test/unit/js/workspace.spec.js
  packages/perspective-viewer-d3fc/src/config/cjs.config.js
  packages/perspective-viewer-d3fc/src/config/umd.config.js
  packages/perspective-viewer-d3fc/src/js/axis/chartFactory.js
  packages/perspective-viewer-highcharts/src/config/cjs.config.js
  packages/perspective-viewer-highcharts/src/config/umd.config.js
  packages/perspective-viewer-hypergrid/src/config/cjs.config.js
  packages/perspective-viewer-hypergrid/src/config/umd.config.js
  packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
  packages/perspective-viewer-hypergrid/src/js/styles.js
  packages/perspective-viewer/src/config/cjs.config.js
  packages/perspective-viewer/src/config/umd.config.js
  packages/perspective-viewer/src/js/computed_column/state.js
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/themes/material-dense.less
  packages/perspective/src/config/common.config.js
  packages/perspective/src/config/perspective.config.js
  packages/perspective/src/config/perspective.node.config.js
  scripts/bench.js
  yarn.lock
Labels: cla-present

#855 add pypi badge
  README.md
Labels: documentation

#862 Improved error messages from C++
  cpp/perspective/src/cpp/arrow_loader.cpp
  cpp/perspective/src/cpp/arrow_writer.cpp
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/schema.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/cpp/view.cpp
  python/perspective/perspective/src/numpy.cpp
  python/perspective/perspective/tests/table/test_table_arrow.py
  python/perspective/perspective/tests/table/test_update_arrow.py
Labels: C++, cla-present, internal

#863 Python versioning fix
  python/perspective/.bumpversion.cfg
Labels: cla-present

#869 Added simple webpack example and renamed existing webpack example
  examples/webpack-cross-origin/README.md
  examples/webpack-cross-origin/package.json
  examples/webpack-cross-origin/src/index.css
  examples/webpack-cross-origin/src/index.html
  examples/webpack-cross-origin/src/index.js
  examples/webpack-cross-origin/webpack.config.js
  examples/webpack/.gitignore
  examples/webpack/README.md
  examples/webpack/index.less
  examples/webpack/output/public/index.html
  examples/webpack/package.json
  examples/webpack/src/index.css
  examples/webpack/src/index.js
  examples/webpack/webpack.config.js
Labels: cla-present

#866 Fix scrolling for pivoted hypergrid
  packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
  packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
  packages/perspective-viewer-hypergrid/test/js/utils.js
  packages/perspective-viewer-hypergrid/test/results/results.json
Labels: JS, bug, cla-present

#868 Allow plugins to be importable before '`perspective-viewer`
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-highcharts/src/js/highcharts/highcharts.js
  packages/perspective-viewer-hypergrid/src/js/hypergrid.js
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer/renderers.js
Labels: cla-present

#871 New computed functions `pow`, `invert`, `sqrt`, `abs`
  packages/perspective-viewer/src/js/computed_column.js
Labels: cla-present

#872 Improve `@finos/perspective-viewer` typings
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-phosphor/src/ts/workspace/workspace.ts
  packages/perspective-viewer/index.d.ts
  packages/perspective-viewer/package.json
  yarn.lock
Labels: cla-present

#867 Time zone awareness in perspective-python
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/tests/table/test_table_datetime.py
  python/perspective/perspective/tests/table/test_table_numpy.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/widget/widget.py
Labels: cla-present

#876 Hiring!
  README.md
Labels: cla-present

#877 Extend `perspective-viewer` typings and added a react-typescript example
  examples/react/package.json
  examples/react/src/index.css
  examples/react/src/index.html
  examples/react/src/index.tsx
  examples/react/tsconfig.json
  examples/react/webpack.config.js
  package.json
  packages/perspective-jupyterlab/package.json
  packages/perspective-phosphor/package.json
  packages/perspective-phosphor/src/ts/widget.ts
  packages/perspective-phosphor/src/ts/workspace/workspace.ts
  packages/perspective-viewer/index.d.ts
  yarn.lock
Labels: cla-present

#880 Fix `on_update` callbacks in Python
  python/perspective/perspective/manager/manager.py
Labels: cla-present

#873 Improve Perspective Documentation
  README.md
  docs/core/Footer.js
  docs/i18n/en.json
  docs/md/concepts.md
  docs/md/installation.md
  docs/md/js.md
  docs/md/python.md
  docs/pages/en/index.js
  docs/sidebars.json
  docs/siteConfig.js
  docs/static/css/concepts/index.css
  docs/static/css/custom.css
  docs/static/js/concepts/index.js
  examples/simple/superstore-arrow.html
  examples/simple/superstore-hypergrid.html
  packages/perspective-viewer/README.md
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective/README.md
  packages/perspective/src/js/perspective.js
  python/perspective/docs/perspective.table.rst
Labels: cla-present, documentation

#886 Fixed React types.
  packages/perspective-viewer/index.d.ts
Labels: JS, cla-present, enhancement

#889 Fix selection styling on `@finos/perspective-viewer-hypergrid`
  packages/perspective-viewer-hypergrid/src/js/styles.js
  packages/perspective-viewer/src/themes/material.less
Labels: JS, cla-present, enhancement
