Repository finos/perspective, pull requests merged in 2021-05, with the labels that each got.

#1408 Upgrade `puppeteer` to `9.0.0`
  azure-pipelines.yml
  docker/puppeteer/Dockerfile
  packages/perspective-jupyterlab/test/results/linux.docker.json
  packages/perspective-test/src/js/globalSetup.js
  packages/perspective-test/src/js/index.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/tooltip/tooltip.js
  packages/perspective-viewer-d3fc/test/html/shares-template.html
  packages/perspective-viewer-d3fc/test/js/integration/candlestick.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/ohlc.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/test/js/computed_expressions.spec.js
  packages/perspective-viewer/test/js/filters.spec.js
  packages/perspective-viewer/test/js/leaks.spec.js
  packages/perspective-viewer/test/js/simple_tests.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/src/js/index.js
  packages/perspective-workspace/test/js/integration/dom.spec.js
  packages/perspective-workspace/test/js/integration/restore.spec.js
  packages/perspective-workspace/test/results/linux.docker.json
  packages/perspective/test/js/pivots.js
Labels: cla-present, internal

#1410 Install Boost from JFrog, fix outdated docs from #1409
  docker/docs/Dockerfile
  docker/python/manylinux2010/Dockerfile
  docker/python/manylinux2014/Dockerfile
  docs/md/installation.md
  docs/md/js.md
  scripts/install_tools.js
Labels: cla-present

#1412 Fix memory leak(s), leak tests, `memory_usage()` wasm heap API
  packages/perspective/src/js/api/client.js
  packages/perspective/src/js/api/server.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/leaks.spec.js
Labels: bug, cla-present

#1411 Fix `react` and `remote-workspace` examples
  .gitignore
  examples/react/package.json
  examples/react/webpack.config.js
  examples/remote-workspace/package.json
  examples/remote-workspace/server.js
  examples/remote-workspace/src/index.html
  examples/remote-workspace/src/index.js
  examples/remote-workspace/webpack.config.js
  examples/workspace/webpack.config.js
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/themes/material-dense.dark.less
  packages/perspective-viewer/src/themes/material-dense.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-workspace/src/js/index.js
  packages/perspective-workspace/src/theme/material.dark.less
  packages/perspective-workspace/src/theme/material.less
  packages/perspective-workspace/test/js/integration/dom.spec.js
  packages/perspective-workspace/test/js/integration/restore.spec.js
  rust/perspective-vieux/Cargo.lock
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/src/less/column-style.less
  rust/perspective-vieux/src/less/radio-list.less
  rust/perspective-vieux/src/rust/column_style.rs
  rust/perspective-vieux/src/rust/components/column_style.rs
  rust/perspective-vieux/src/rust/components/mod.rs
  rust/perspective-vieux/src/rust/components/radio_list.rs
  rust/perspective-vieux/src/rust/components/split_panel.rs
  rust/perspective-vieux/src/rust/components/tests/column_style.rs
  rust/perspective-vieux/src/rust/components/tests/mod.rs
  rust/perspective-vieux/src/rust/components/tests/radio_list.rs
  rust/perspective-vieux/src/rust/lib.rs
  rust/perspective-vieux/src/rust/utils.rs
  rust/perspective-vieux/src/rust/vieux.rs
  scripts/toggle_puppeteer.js
  yarn.lock
Labels: cla-present, internal

#1414 Responsive column style menu
  rust/perspective-vieux/src/rust/column_style.rs
Labels: bug, cla-present

#1415 Color-by-string for Treemap/Sunburst
  packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
  packages/perspective-viewer-d3fc/src/js/charts/treemap.js
  packages/perspective-viewer-d3fc/src/js/data/treeData.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/series/seriesColors.js
  packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstArc.js
  packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstColor.js
  packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstLabel.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapColor.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/js/unit/data/testTreeData.js
  packages/perspective-viewer-d3fc/test/js/unit/data/treeData.spec.js
  packages/perspective-viewer-d3fc/test/js/unit/tooltip/generateHTML.spec.js
Labels: JS, cla-present, d3fc, enhancement

#1416 More Material style updates
  packages/perspective-jupyterlab/test/results/linux.docker.json
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLabel.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLayout.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/src/less/row-hover.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/less/scrollbars.less
  packages/perspective-viewer/src/less/variables.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/test/results/linux.docker.json
Labels: JS, cla-present, enhancement, styling

#1417 Fix styling bugs from CSS minification
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer/src/themes/material.dark.less
Labels: JS, bug, cla-present, styling

#1419 Fix CLI `async` regression
  packages/perspective-cli/src/js/index.js
Labels: bug, cla-present

#1420 Double-render fix
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/test/js/unit/throttle_promise.spec.js
  packages/perspective-workspace/src/theme/material.less
Labels: cla-present

#1381 organize azure pipelines file
  azure-pipelines.yml
Labels: cla-present, internal

#1431 Isolate expressions per-context and ensure memory stability
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_unit.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/expression_tables.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/cpp/tree_context_common.cpp
  cpp/perspective/src/include/perspective/computed_expression.h
  cpp/perspective/src/include/perspective/context_common_decls.h
  cpp/perspective/src/include/perspective/context_grouped_pkey.h
  cpp/perspective/src/include/perspective/context_one.h
  cpp/perspective/src/include/perspective/context_two.h
  cpp/perspective/src/include/perspective/context_zero.h
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/expression_tables.h
  cpp/perspective/src/include/perspective/flat_traversal.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/sparse_tree.h
  cpp/perspective/src/include/perspective/tree_context_common.h
  docs/md/view.md
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/clear.js
  packages/perspective/test/js/expressions.js
  packages/perspective/test/js/expressions/functionality.js
  packages/perspective/test/js/expressions/multiple_views.js
  packages/perspective/test/js/expressions/string.js
  packages/perspective/test/js/expressions/updates.js
  packages/perspective/test/js/leaks.spec.js
  python/perspective/perspective/include/perspective/python/view.h
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/tests/table/test_view_expression.py
  scripts/test_python.js
Labels: C++, JS, Python, cla-present, enhancement

#1432 Parse aggregates in column order
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/view_config.h
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective/src/js/config/constants.js
  packages/perspective/test/js/expressions/functionality.js
  packages/perspective/test/js/pivots.js
  packages/perspective/test/js/sort.js
  python/perspective/perspective/tests/table/test_view.py
Labels: C++, bug, cla-present

#1434 Expose `join` aggregate
  cpp/perspective/src/cpp/sparse_tree.cpp
  packages/perspective/src/js/config/constants.js
  packages/perspective/test/js/pivots.js
  python/perspective/perspective/core/aggregate.py
Labels: cla-present
