Repository finos/perspective, pull requests merged in 2021-08, with the labels that each got.

#1514 Remove filter limit
  packages/perspective-viewer/src/js/viewer/dom_element.js
Labels: bug, cla-present

#1516 Add new aggregates to ViewConfig enum
  packages/perspective/test/js/expressions/conversions.js
  rust/perspective-vieux/src/rust/config/view_config.rs
Labels: bug, JS, cla-present

#1524 Fix support for array-like filter terms
  rust/perspective-vieux/src/rust/config/view_config.rs
Labels: bug, cla-present

#1518 Fix count aggregate when last aggregate and partial updates are applied
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/sparse_tree.h
  packages/perspective/test/js/filters.js
  packages/perspective/test/js/pivots.js
  packages/perspective/test/js/updates.js
Labels: bug, C++, cla-present

#1519 Refactor `to_arrow`, fix row deltas for pivoted views
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/cpp/view.cpp
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/delta.js
  packages/perspective/test/js/expressions/deltas.js
  packages/perspective/test/js/pivots.js
  packages/perspective/test/js/to_format.js
Labels: bug, C++, cla-present

#1525 Fix M1 (Apple Silicon) build for `perspective-python` and improve developer docs
  cmake/modules/FindFlatbuffers.cmake
  docs/md/development.md
  scripts/lint_python.js
  scripts/test_python.js
Labels: enhancement, cla-present
