Repository finos/perspective, pull requests merged in 2021-04, with the labels that each got.

#1336 Deprecate py27 (linux), add py39 (osx)
  azure-pipelines.yml
  docker/python/manylinux2010/Dockerfile
  docker/python/manylinux2014/Dockerfile
  python/perspective/setup.py
  scripts/_wheel_python.js
Labels: Python, cla-present, enhancement

#1375 Add `call_loop` and `get_table_names`
  docs/md/python.md
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/tests/core/test_async.py
  python/perspective/perspective/tests/manager/test_manager.py
Labels: Python, cla-present, enhancement

#1377 Fix `@finos/perspective-jupyterlab` to work with WebAssembly/Webpack5
  docs/md/js.md
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/config/plugin.config.js
  packages/perspective-jupyterlab/src/config/webpack.config.js
  packages/perspective-jupyterlab/src/ts/renderer.ts
  packages/perspective-webpack-plugin/index.js
  packages/perspective/src/config/common.config.js
  rust/perspective-vieux/package.json
  rust/perspective-vieux/src/js/bootstrap.js
  rust/perspective-vieux/src/js/index.js
  scripts/jlab_link.js
Labels: cla-present

#1379 Update regular-table to 0.3.1
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  yarn.lock
Labels: JS, cla-present, internal

#1382 Adds `yarn repl` to launch a shell inside our docker images
  package.json
  scripts/repl.js
Labels: cla-present

#1380 Material Theme 2.0
  cpp/perspective/package.json
  docs/static/js/animation.js
  examples/blocks/src/custom/index.html
  examples/promo/script.js
  examples/promo/webpack.config.js
  examples/workspace/package.json
  packages/perspective-jupyterlab/test/results/linux.docker.json
  packages/perspective-viewer-d3fc/src/js/gridlines/gridlines.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/js/integration/candlestick.spec.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/less/mitered-headers.less
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/row-hover.less
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/computed_expression_widget.less
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/expression_editor.less
  packages/perspective-viewer/src/less/fonts.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/less/scrollbars.less
  packages/perspective-viewer/src/less/variables.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/js/render_warning_tests.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/dockpanel.less
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/less/widget.less
  packages/perspective-workspace/src/less/workspace.less
  packages/perspective-workspace/src/theme/material.dark.less
  packages/perspective-workspace/src/theme/material.less
  packages/perspective-workspace/test/results/linux.docker.json
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/src/less/perspective-vieux.less
  rust/perspective-vieux/src/less/status-bar.less
  rust/perspective-vieux/src/rust/components/perspective_vieux.rs
  rust/perspective-vieux/src/rust/session/view_subscription.rs
  rust/perspective-vieux/src/rust/utils.rs
  yarn.lock
Labels: cla-present

#1384 Backwards compatibility for table() and view()
  packages/perspective/src/js/api/client.js
  packages/perspective/src/js/api/server.js
  packages/perspective/src/js/api/table_api.js
  packages/perspective/src/js/api/view_api.js
  python/perspective/perspective/manager/manager_internal.py
Labels: JS, cla-present, enhancement

#1387 Fix cross-origin webpack defaults
  packages/perspective-webpack-plugin/index.js
  packages/perspective/src/config/common.config.js
  packages/perspective/src/config/perspective.inline.config.js
Labels: cla-present

#1388 Remove webcomponentsjs
  docs/md/installation.md
  docs/md/js.md
  docs/md/python.md
  docs/static/js/animation.js
  examples/blocks/src/csv/csv.js
  examples/blocks/src/dataset/index.html
  examples/blocks/src/editable/index.html
  examples/blocks/src/iex/index.js
  examples/blocks/src/mandelbrot/index.html
  examples/blocks/src/ohlc/index.html
  examples/blocks/src/streaming/streaming.js
  examples/blocks/src/workspace/workspace.js
  examples/git-history/chained.html
  examples/git-history/index.html
  examples/remote-express-typescript/assets/index.html
  examples/remote-express/index.html
  examples/tornado-python/client_server_editing.html
  examples/tornado-python/index.html
  examples/tornado-python/server_mode.html
  examples/tornado-streaming-python/index.html
  examples/webpack-cross-origin/src/index.js
  packages/perspective-bench/src/html/benchmark.html
  packages/perspective-cli/src/html/index.html
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective/src/js/perspective.node.js
  python/perspective/bench/runtime/benchmark_hosted.html
  yarn.lock
Labels: JS, breaking, cla-present

#1386 Datagrid Styleable Column
  .gitignore
  docs/i18n/en.json
  docs/static/css/custom.css
  docs/static/css/material.dark.css
  examples/blocks/dist.js
  packages/perspective-jupyterlab/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/config/rollup.config.js
  packages/perspective-viewer-datagrid/src/js/color_utils.js
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/plugin_menu.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/less/column-plugin.less
  packages/perspective-viewer-datagrid/src/less/column-style.less
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/config/rollup.config.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/themes/material-dense.dark.less
  packages/perspective-viewer/src/themes/material-dense.less
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/viewer.less
  packages/perspective-workspace/src/theme/material.dark.less
  packages/perspective-workspace/src/theme/material.less
  python/perspective/bench/runtime/benchmark_hosted.html
  rust/perspective-vieux/Cargo.lock
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/package.json
  rust/perspective-vieux/rollup.config.js
  rust/perspective-vieux/src/js/vieux.js
  rust/perspective-vieux/src/less/column-style.less
  rust/perspective-vieux/src/less/perspective-vieux.less
  rust/perspective-vieux/src/rust/components/column_style.rs
  rust/perspective-vieux/src/rust/components/mod.rs
  rust/perspective-vieux/src/rust/components/tests/column_style.rs
  rust/perspective-vieux/src/rust/components/tests/mod.rs
  rust/perspective-vieux/src/rust/lib.rs
  rust/perspective-vieux/src/rust/vieux.rs
Labels: Rust, cla-present, enhancement

#1353 Enable editing to mime renderer in JupyterLab
  docs/md/python.md
  packages/perspective-jupyterlab/src/ts/psp_widget.ts
  packages/perspective-jupyterlab/src/ts/renderer.ts
Labels: Jupyter, cla-present, enhancement

#1390 Fix `last` aggregate to preserve status
  cpp/perspective/src/cpp/aggregate.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/include/perspective/aggregate.h
  cpp/perspective/src/include/perspective/gnode_state.h
  packages/perspective/test/js/pivot_nulls.js
Labels: cla-present

#1391 Disable column style menu for non-numeric columns
  packages/perspective-jupyterlab/test/results/linux.docker.json
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/less/column-plugin.less
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/less/expression_editor.less
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/config/theme.config.js
  packages/perspective-workspace/test/results/linux.docker.json
Labels: cla-present

#1395 Add `get_min_max()` to Perspective API
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_unit.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/context_one.h
  cpp/perspective/src/include/perspective/context_two.h
  cpp/perspective/src/include/perspective/context_unit.h
  cpp/perspective/src/include/perspective/context_zero.h
  cpp/perspective/src/include/perspective/view.h
  packages/perspective-viewer-datagrid/src/js/plugin_menu.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective/src/js/api/view_api.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/get_min_max.spec.js
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/table/view.py
  rust/perspective-vieux/src/rust/utils.rs
Labels: JS, Python, cla-present, enhancement

#1399 Updated `gh-pages` site and `README.md`
  .gitignore
  README.md
  docs/README.md
  docs/js/concepts.js
  docs/js/index.js
  docs/js/logo.js
  docs/logo.config.js
  docs/md/table.md
  docs/md/view.md
  docs/package.json
  docs/pages/en/index.js
  docs/siteConfig.js
  docs/static/js/nyc-citibike-analysis/index.js
  docs/webpack.config.js
  examples/blocks/gists.json
  examples/blocks/src/movies/.block
  examples/blocks/src/movies/README.md
  examples/blocks/src/movies/index.html
  examples/blocks/src/movies/layout.json
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/less/column-plugin.less
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-workspace/src/less/dockpanel.less
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/theme/material.less
  packages/perspective/src/js/api/server.js
  python/perspective/perspective/client/view_api.py
  rust/perspective-vieux/package.json
  rust/perspective-vieux/src/rust/vieux.rs
Labels: cla-present
