Repository finos/perspective, pull requests merged in 2021-10, with the labels that each got.

#1565 Fix #1562, fix regressions in PerspectiveWidget
  binder/requirements.txt
  packages/perspective-jupyterlab/src/js/view.js
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
  python/perspective/perspective/core/plugin.py
  python/perspective/perspective/tests/core/test_plugin.py
  python/perspective/perspective/tests/viewer/test_validate.py
  python/perspective/perspective/tests/viewer/test_viewer.py
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/viewer/viewer_traitlets.py
Labels: bug, Jupyter, cla-present

#1593 Fix JupyterLab widget `filter` traitlet
  packages/perspective-jupyterlab/src/js/model.js
  packages/perspective-jupyterlab/src/js/view.js
  python/perspective/perspective/tests/viewer/test_validate.py
  python/perspective/perspective/tests/viewer/test_viewer.py
  python/perspective/perspective/viewer/validate.py
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/viewer/viewer_traitlets.py
  scripts/jlab_link.js
  scripts/setup.js
Labels: bug, Jupyter, cla-present

#1594 Persist edited expressions and add 'Reset' button
  rust/perspective-viewer/src/less/expression-editor.less
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/config_selector.rs
  rust/perspective-viewer/src/rust/components/containers/dragdrop_list.rs
  rust/perspective-viewer/src/rust/components/containers/dropdown.rs
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/components/expression_toolbar.rs
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/src/rust/components/pivot_item.rs
  rust/perspective-viewer/src/rust/config/aggregates.rs
  rust/perspective-viewer/src/rust/config/view_config.rs
  rust/perspective-viewer/src/rust/custom_elements/expression_editor.rs
  rust/perspective-viewer/src/rust/dragdrop.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/metadata.rs
  rust/perspective-viewer/src/rust/utils/js_object.rs
  rust/perspective-viewer/src/rust/utils/mod.rs
  rust/perspective-viewer/test/js/expressions.spec.js
  rust/perspective-viewer/test/results/results.json
Labels: enhancement, cla-present

#1595 Add ExprTK example fractal
  examples/blocks/gists.json
  examples/blocks/src/fractal/.block
  examples/blocks/src/fractal/README.md
  examples/blocks/src/fractal/index.css
  examples/blocks/src/fractal/index.html
  examples/blocks/src/fractal/index.js
  examples/blocks/src/mandelbrot/index.html
Labels: cla-present

#1596 Add Regex functions using Exprtk and RE2
  cmake/re2.txt.in
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/arrow_csv.cpp
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/regex.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/computed_expression.h
  cpp/perspective/src/include/perspective/computed_function.h
  cpp/perspective/src/include/perspective/context_common_decls.h
  cpp/perspective/src/include/perspective/context_grouped_pkey.h
  cpp/perspective/src/include/perspective/context_one.h
  cpp/perspective/src/include/perspective/context_two.h
  cpp/perspective/src/include/perspective/context_zero.h
  cpp/perspective/src/include/perspective/expression_vocab.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/parallel_for.h
  cpp/perspective/src/include/perspective/regex.h
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/expressions/functionality.js
  packages/perspective/test/js/expressions/string.js
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/tests/table/test_view_expression.py
  rust/perspective-viewer/src/rust/exprtk/language.rs
Labels: enhancement, C++, cla-present

#1599 Upgrade `d3fc` to `15.2.4` and switch "Heatmap" to use canvas renderer
  packages/perspective-test/jest.all.config.js
  packages/perspective-test/jest.config.js
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/js/axis/axisSplitter.js
  packages/perspective-viewer-d3fc/src/js/axis/chartFactory.js
  packages/perspective-viewer-d3fc/src/js/axis/flatten.js
  packages/perspective-viewer-d3fc/src/js/axis/splitterLabels.js
  packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
  packages/perspective-viewer-d3fc/src/js/d3fc/axis/multi-axis.js
  packages/perspective-viewer-d3fc/src/js/legend/styling/draggableComponent.js
  packages/perspective-viewer-d3fc/src/js/legend/styling/resizableComponent.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/series/heatmapSeries.js
  packages/perspective-viewer-d3fc/src/js/tooltip/nearbyTip.js
  packages/perspective-viewer-d3fc/src/js/tooltip/tooltip.js
  packages/perspective-viewer-d3fc/src/js/zoom/zoomableChart.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/js/unit/data/groupData.spec.js
  packages/perspective-viewer-d3fc/test/js/unit/series/seriesRange.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
  rust/perspective-viewer/package.json
  yarn.lock
Labels: internal, cla-present
