Repository finos/perspective, pull requests merged in 2021-01, with the labels that each got.

#1260 Fix build for pyarrow 2.0.0
  cmake/modules/FindPyArrow.cmake
Labels: Python, bug, cla-present

#1271 Cleanup docs and examples to viewer.load(table)
  docs/md/installation.md
  docs/md/js.md
  docs/static/js/animation.js
  packages/perspective-bench/src/html/benchmark.html
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
Labels: JS, cla-present, documentation, internal

#1273 free() pointer to arrow binary in Python
  python/perspective/perspective/src/table.cpp
Labels: C++, Python, cla-present, internal

#1275 New Documentation & Project Site
  README.md
  docs/blog/2018-10-01-v0.2.0-release.md
  docs/blog/2019-06-10-v0.3.0-release.md
  docs/blog/2020-01-06-v0.4.0-release.md
  docs/core/Footer.js
  docs/i18n/en.json
  docs/md/concepts.md
  docs/md/development.md
  docs/md/installation.md
  docs/md/js.md
  docs/md/python.md
  docs/md/server.md
  docs/md/table.md
  docs/md/view.md
  docs/pages/en/index.js
  docs/sidebars.json
  docs/siteConfig.js
  docs/static/css/concepts/index.css
  docs/static/css/custom.css
  docs/static/css/material.dark.css
  docs/static/css/material.dark.less
  docs/static/css/nyc-citibike-analysis/index.css
  docs/static/js/animation.js
  docs/static/js/concepts/index.js
  docs/static/js/nyc-citibike-analysis/index.js
  docs/static/svg/architecture.dot
  docs/static/svg/architecture.sub1.dot
  docs/static/svg/architecture.sub1.svg
  docs/static/svg/architecture.sub2.dot
  docs/static/svg/architecture.sub2.svg
  docs/static/svg/architecture.sub3.dot
  docs/static/svg/architecture.sub3.svg
  docs/static/svg/architecture.svg
  packages/perspective-viewer/README.md
  packages/perspective-viewer/src/themes/material-dense.dark.less
  packages/perspective-viewer/src/themes/material-dense.less
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.parallel.js
  python/perspective/README.md
  python/perspective/perspective/viewer/viewer.py
  scripts/docs.js
Labels: cla-present, documentation

#1272 Validate view config in engine, fix computed column state bugs
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/table.h
  cpp/perspective/src/include/perspective/view_config.h
  packages/perspective-bench/bench/perspective.benchmark.js
  packages/perspective-bench/bench/versions.js
  packages/perspective-bench/src/html/benchmark.html
  packages/perspective-viewer/src/html/expression_editor.html
  packages/perspective-viewer/src/js/computed_expressions/widget.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/test/js/computed_expressions.spec.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective/test/js/computed/expressions.js
  packages/perspective/test/js/computed/functionality.js
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/tests/table/test_exception.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/perspective/tests/table/test_view_computed.py
Labels: JS, Python, cla-present, enhancement, internal

#1281 Fix Date/Time formatting in `perspective-viewer` CSV output
  examples/blocks/src/superstore/index.html
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/to_format.js
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/table/test_to_format.py
Labels: JS, Python, bug, cla-present

#1288 Fix #1244: make test_wheels script use python -m pip
  python/perspective/scripts/test_wheels.sh
Labels: Python, cla-present, internal

#1232 Upgrade Emscripten to 2.0.6 and remove emsdk docker image
  README.md
  azure-pipelines.yml
  cpp/perspective/CMakeLists.txt
  docker/emsdk/Dockerfile
  docs/md/development.md
  package.json
  packages/perspective/babel.config.js
  packages/perspective/package.json
  packages/perspective/src/js/perspective.js
  scripts/build_js.js
  scripts/install_tools.js
  scripts/test_js.js
  yarn.lock
Labels: cla-present, internal

#1290 Statically link `perspective-python` and `libarrow`
  azure-pipelines.yml
  binder/requirements.txt
  cmake/arrow.txt.in
  cmake/arrow/CMakeLists.txt
  cmake/date.txt.in
  cmake/flatbuffers.txt.in
  cmake/modules/FindFlatbuffers.cmake
  cmake/modules/FindPyArrow.cmake
  cmake/modules/FindPybind.cmake
  cpp/perspective/CMakeLists.txt
  docker/python/manylinux2010/Dockerfile
  docker/python/manylinux2014/Dockerfile
  docs/md/development.md
  docs/md/python.md
  python/perspective/pyproject.toml
  python/perspective/setup.py
  scripts/_wheel_python.js
Labels: Python, cla-present, internal

#1287 Fixes style issue with <select> dark theme on Windows
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material.dark.less
Labels: cla-present, styling

#1294 JupyterLab update to ^3.0.0, and fix "Open With.." regression
  cpp/perspective/CMakeLists.txt
  package.json
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/ts/.eslintrc.json
  packages/perspective-jupyterlab/src/ts/client.ts
  packages/perspective-jupyterlab/src/ts/index.ts
  packages/perspective-jupyterlab/src/ts/plugin.ts
  packages/perspective-jupyterlab/src/ts/psp_widget.ts
  packages/perspective-jupyterlab/src/ts/renderer.ts
  packages/perspective-jupyterlab/src/ts/version.ts
  packages/perspective-jupyterlab/src/ts/view.ts
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective-workspace/package.json
  python/perspective/Makefile
  python/perspective/setup.cfg
  python/perspective/setup.py
  yarn.lock
Labels: 0.6.1, Jupyter, Python, cla-present, internal

#1286 Fix for sorting via `avg` aggregated column.
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/include/perspective/multi_sort.h
  cpp/perspective/src/include/perspective/traversal.h
  docs/md/development.md
  packages/perspective-bench/bench/perspective.benchmark.js
  packages/perspective-bench/bench/versions.js
  packages/perspective/test/js/sort.js
  python/perspective/perspective/tests/table/test_view.py
  scripts/bench.js
Labels: 0.6.1, C++, bug, cla-present

#1298 Fix partial updates in Python using dicts
  packages/perspective/test/js/updates.js
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/tests/table/test_update.py
  python/perspective/perspective/tests/table/test_update_arrow.py
Labels: 0.6.1, Python, bug, cla-present

#1309 Add `jlab_link` script to link local changes into development Jupyterlab
  docs/md/development.md
  docs/md/python.md
  docs/static/css/custom.css
  docs/static/css/material.dark.css
  docs/static/js/animation.js
  package.json
  packages/perspective-jupyterlab/package.json
  packages/perspective/src/js/perspective.js
  scripts/jlab_link.js
  scripts/script_utils.js
Labels: Jupyter, Python, cla-present, development

#1292 Add `@finos/perspective-cpp` module
  cpp/perspective/CMakeLists.txt
  cpp/perspective/build.js
  cpp/perspective/package.json
  docs/md/js.md
  docs/package.json
  examples/promo/package.json
  examples/react/package.json
  examples/remote-workspace/package.json
  examples/webpack-cross-origin/package.json
  examples/webpack-cross-origin/webpack.config.js
  examples/webpack/package.json
  examples/webpack/webpack.config.js
  examples/workspace-editing-python/package.json
  examples/workspace/package.json
  package.json
  packages/perspective-bench/package.json
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/config/plugin.config.js
  packages/perspective-jupyterlab/src/config/webpack.config.js
  packages/perspective-test/package.json
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/config/umd.config.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-webpack-plugin/README.md
  packages/perspective-webpack-plugin/index.js
  packages/perspective-webpack-plugin/package.json
  packages/perspective-webpack-plugin/src/js/null-loader.js
  packages/perspective-webpack-plugin/src/js/psp-worker-compiler-loader.js
  packages/perspective-webpack-plugin/src/js/psp-worker-loader.js
  packages/perspective-webpack-plugin/src/js/switch-inline-loader.js
  packages/perspective-webpack-plugin/src/js/utils.js
  packages/perspective-webpack-plugin/src/js/wasm-loader.js
  packages/perspective/package.json
  packages/perspective/src/config/common.config.js
  packages/perspective/src/config/minimizer.js
  packages/perspective/src/config/perspective.config.js
  packages/perspective/src/config/perspective.inline.config.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.parallel.js
  packages/perspective/src/js/perspective.worker.js
  packages/perspective/src/js/psp.async.wasm.js
  scripts/bench.js
  scripts/build_js.js
  scripts/clean.js
  scripts/docs.js
  scripts/install_emsdk.js
  scripts/script_utils.js
  scripts/setup.js
  yarn.lock
Labels: 0.6.1, C++, JS, cla-present, internal

#1293 Removed dead code from C++ src
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_unit.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/custom_column.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/histogram.cpp
  cpp/perspective/src/cpp/logtime.cpp
  cpp/perspective/src/cpp/min_max.cpp
  cpp/perspective/src/include/perspective/column.h
  cpp/perspective/src/include/perspective/context_base.h
  cpp/perspective/src/include/perspective/context_unit.h
  cpp/perspective/src/include/perspective/context_zero.h
  cpp/perspective/src/include/perspective/custom_column.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/histogram.h
  cpp/perspective/src/include/perspective/logtime.h
  cpp/perspective/src/include/perspective/min_max.h
  cpp/perspective/src/include/perspective/sparse_tree.h
Labels: C++, cla-present, internal

#1282 Date/datetime filter autocompletion, new timezone test suite for JS
  azure-pipelines.yml
  cpp/perspective/src/cpp/arrow_csv.cpp
  packages/perspective-viewer-d3fc/test/js/integration/candlestick.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/ohlc.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/test/html/filters.html
  packages/perspective-viewer/test/js/computed_expressions.spec.js
  packages/perspective-viewer/test/js/filters.spec.js
  packages/perspective-viewer/test/js/leaks.spec.js
  packages/perspective-viewer/test/js/simple_tests.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective/package.json
  packages/perspective/src/js/perspective.js
  packages/perspective/test/config/timezone/jest.config.js
  packages/perspective/test/config/timezone/set_timezone.js
  packages/perspective/test/js/constructors.js
  packages/perspective/test/js/filters.js
  packages/perspective/test/js/timezone/timezone.spec.js
  scripts/test_js.js
Labels: 0.6.1, JS, cla-present, enhancement
