Repository finos/perspective, pull requests merged in 2021-07, with the labels that each got.

#1465 Misc. plugin bug fixes
  packages/perspective-viewer-d3fc/src/js/axis/splitterLabels.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/layout/gridLayoutMultiChart.js
  packages/perspective-viewer-d3fc/src/js/legend/legend.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
  packages/perspective-viewer-d3fc/src/js/tooltip/nearbyTip.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/js/row.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  rust/perspective-vieux/src/js/vieux.js
  rust/perspective-vieux/src/less/perspective-vieux.less
  rust/perspective-vieux/src/rust/components/plugin_selector.rs
  rust/perspective-vieux/src/rust/components/tests/plugin_selector.rs
  rust/perspective-vieux/src/rust/components/vieux.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux.rs
  rust/perspective-vieux/src/rust/plugin.rs
Labels: bug, cla-present

#1469 Fix Binder by updating Jupyterlab to 3.0.14 from 3.0.9
  binder/requirements.txt
Labels: cla-present

#1470 New website
  .gitignore
  docs/js/concepts.js
  docs/js/examples.js
  docs/js/features.js
  docs/js/index.js
  docs/pages/en/index.js
  docs/static/css/custom.css
  docs/static/css/material.dark.less
  docs/webpack.config.js
  examples/blocks/src/streaming/index.html
  examples/blocks/src/streaming/streaming.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
Labels: cla-present, documentation

#1476 Add standard deviation and variance aggregates
  cpp/perspective/src/cpp/aggspec.cpp
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/config.cpp
  cpp/perspective/src/cpp/extract_aggregate.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/base.h
  examples/workspace-editing-python/package.json
  examples/workspace-editing-python/src/index.js
  packages/perspective/index.d.ts
  packages/perspective/src/js/config/constants.js
  packages/perspective/test/js/pivots.js
  packages/perspective/test/js/to_format.js
  python/perspective/bench/tornado/async_server.py
  python/perspective/bench/tornado/bench.py
  python/perspective/bench/tornado/distributed_mode.py
  python/perspective/perspective/core/aggregate.py
  python/perspective/perspective/tests/table/test_to_arrow.py
  python/perspective/perspective/tests/table/test_view.py
Labels: cla-present

#1475 Upgrade `regular-table`
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer/src/js/custom_styles.js
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  python/perspective/perspective/manager/manager_internal.py
  rust/perspective-vieux/Cargo.lock
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/src/js/vieux.js
  rust/perspective-vieux/src/rust/components/expression_editor.rs
  rust/perspective-vieux/src/rust/components/plugin_selector.rs
  rust/perspective-vieux/src/rust/components/status_bar.rs
  rust/perspective-vieux/src/rust/components/tests/plugin_selector.rs
  rust/perspective-vieux/src/rust/components/tests/status_bar.rs
  rust/perspective-vieux/src/rust/components/vieux.rs
  rust/perspective-vieux/src/rust/config/view_config.rs
  rust/perspective-vieux/src/rust/custom_elements/expression_editor.rs
  rust/perspective-vieux/src/rust/custom_elements/tests/vieux.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux/activate.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux/limits.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux/render_timer.rs
  rust/perspective-vieux/src/rust/exprtk/completions.rs
  rust/perspective-vieux/src/rust/js/monaco.rs
  rust/perspective-vieux/src/rust/js/perspective.rs
  rust/perspective-vieux/src/rust/js/perspective_viewer.rs
  rust/perspective-vieux/src/rust/plugin.rs
  rust/perspective-vieux/src/rust/plugin/registry.rs
  rust/perspective-vieux/src/rust/session.rs
  rust/perspective-vieux/src/rust/session/copy.rs
  rust/perspective-vieux/src/rust/session/download.rs
  rust/perspective-vieux/src/rust/session/view_subscription.rs
  rust/perspective-vieux/src/rust/utils/async_callback.rs
  rust/perspective-vieux/src/rust/utils/debounce.rs
  rust/perspective-vieux/src/rust/utils/errors.rs
  rust/perspective-vieux/src/rust/utils/future_to_promise.rs
  rust/perspective-vieux/src/rust/utils/mod.rs
  rust/perspective-vieux/src/rust/utils/request_animation_frame.rs
  rust/perspective-vieux/src/rust/utils/testing.rs
  rust/perspective-vieux/src/rust/utils/tests/request_animation_frame.rs
  yarn.lock
Labels: cla-present

#1479 Fix throttle attribute
  examples/blocks/dist.js
  examples/blocks/src/movies/layout.json
  examples/blocks/src/olympics/index.html
  examples/blocks/src/superstore/index.html
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/config/rollup.config.js
  packages/perspective-viewer/src/config/umd.config.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/test/results/linux.docker.json
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/src/js/vieux.js
  rust/perspective-vieux/src/less/perspective-vieux.less
  rust/perspective-vieux/src/rust/components/expression_editor.rs
  rust/perspective-vieux/src/rust/components/plugin_selector.rs
  rust/perspective-vieux/src/rust/components/render_warning.rs
  rust/perspective-vieux/src/rust/components/status_bar.rs
  rust/perspective-vieux/src/rust/components/tests/plugin_selector.rs
  rust/perspective-vieux/src/rust/components/vieux.rs
  rust/perspective-vieux/src/rust/config.rs
  rust/perspective-vieux/src/rust/config/view_config.rs
  rust/perspective-vieux/src/rust/custom_elements/tests/vieux.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux.rs
  rust/perspective-vieux/src/rust/js/perspective.rs
  rust/perspective-vieux/src/rust/js/perspective_viewer.rs
  rust/perspective-vieux/src/rust/lib.rs
  rust/perspective-vieux/src/rust/plugin.rs
  rust/perspective-vieux/src/rust/renderer.rs
  rust/perspective-vieux/src/rust/renderer/activate.rs
  rust/perspective-vieux/src/rust/renderer/limits.rs
  rust/perspective-vieux/src/rust/renderer/registry.rs
  rust/perspective-vieux/src/rust/renderer/render_timer.rs
  rust/perspective-vieux/src/rust/session.rs
  rust/perspective-vieux/src/rust/session/copy.rs
  rust/perspective-vieux/src/rust/session/download.rs
  rust/perspective-vieux/src/rust/session/view.rs
  rust/perspective-vieux/src/rust/session/view_subscription.rs
  rust/perspective-vieux/src/rust/utils/mod.rs
  rust/perspective-vieux/src/rust/utils/pubsub.rs
  rust/perspective-vieux/src/rust/utils/tests/perspective.rs
Labels: cla-present

#1480 Add required dependencies for webpack plugin
  package.json
  packages/perspective-webpack-plugin/index.js
  packages/perspective-webpack-plugin/package.json
Labels: cla-present

#1481 Preload fonts
  docs/js/concepts.js
  docs/js/examples.js
  docs/js/features.js
  docs/js/fonts.js
  docs/js/index.js
  docs/pages/en/index.js
  docs/siteConfig.js
  docs/static/css/custom.css
  docs/webpack.config.js
  examples/blocks/src/citibike/index.html
  examples/blocks/src/csv/index.html
  examples/blocks/src/editable/index.html
  examples/blocks/src/movies/index.html
  examples/blocks/src/olympics/index.html
  examples/blocks/src/streaming/index.html
  examples/blocks/src/superstore/index.html
  examples/blocks/src/workspace/index.html
  examples/workspace/src/index.html
  package.json
  rust/perspective-vieux/src/rust/custom_elements/vieux.rs
  rust/perspective-vieux/src/rust/renderer.rs
  yarn.lock
Labels: cla-present
