Repository finos/perspective, pull requests merged in 2021-09, with the labels that each got.

#1526 Fix D3FC chart resize via `preserveAspectRatio`
  packages/perspective-viewer-d3fc/src/js/axis/chartFactory.js
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: bug, cla-present

#1528 Fix #1505, #998, #1225 - results after remove are correct
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/gnode_state.h
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/heatmap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/yscatter.spec.js
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  packages/perspective-workspace/src/js/workspace/discrete.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/removes.spec.js
  packages/perspective/test/js/updates.js
Labels: bug, C++, cla-present

#1529 Fix `settings` key to trigger redraw + container redraw
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-datagrid/test/results/results.json
  rust/perspective-viewer/src/rust/components/active_column.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/test/js/settings.spec.js
  rust/perspective-viewer/test/results/results.json
Labels: bug, cla-present

#1530 Use TypeScript for `@finos/perspective-viewer`
  examples/react/package.json
  examples/react/src/index.css
  examples/react/src/index.tsx
  examples/react/webpack.config.js
  package.json
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/ts/psp_widget.ts
  packages/perspective-jupyterlab/src/ts/renderer.ts
  packages/perspective-jupyterlab/src/ts/widget.ts
  packages/perspective/index.d.ts
  packages/perspective/package.json
  rust/perspective-viewer/README.md
  rust/perspective-viewer/babel.config.js
  rust/perspective-viewer/concat-md.js
  rust/perspective-viewer/index.d.ts
  rust/perspective-viewer/package.json
  rust/perspective-viewer/rollup.config.js
  rust/perspective-viewer/src/js/dragdrop.js
  rust/perspective-viewer/src/js/index.js
  rust/perspective-viewer/src/js/monaco.js
  rust/perspective-viewer/src/rust/config/filters.rs
  rust/perspective-viewer/src/rust/js/monaco.rs
  rust/perspective-viewer/src/ts/index.ts
  rust/perspective-viewer/src/ts/monaco.ts
  rust/perspective-viewer/test/results/results.json
  rust/perspective-viewer/tsconfig.json
  yarn.lock
Labels: cla-present

#1531 Re-add `getEditPort()` and `restyleElement()` methods
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-datagrid/src/js/plugin.js
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/js/perspective.rs
  rust/perspective-viewer/src/rust/js/plugin.rs
  rust/perspective-viewer/src/rust/session/metadata.rs
  rust/perspective-viewer/src/ts/index.ts
Labels: bug

#1532 Fix drag/drop exclusive cases
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/session.rs
Labels: cla-present

#1533 Fix `docs` site and NPM artifact for `<perspective-viewer>` update
  docs/README.md
  docs/js/examples.js
  docs/js/features.js
  docs/js/index.js
  docs/static/css/material.dark.less
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapColor.js
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/rust/components/active_column.rs
  rust/perspective-viewer/src/rust/components/tests/mod.rs
  rust/perspective-viewer/src/rust/components/tests/viewer.rs
  rust/perspective-viewer/src/rust/custom_elements/mod.rs
  rust/perspective-viewer/src/rust/custom_elements/tests/mod.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/rust/renderer/render_timer.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/utils/testing.rs
Labels: cla-present

#1540 Fix workspace filter events
  examples/blocks/src/movies/layout.json
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionEvent.js
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-datagrid/src/js/getCellConfig.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/js/row_selection.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/rust/components/status_bar.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/ts/index.ts
  yarn.lock
Labels: cla-present

#1541 Fix `is (not) null`, `date`, `datetime` filters
  rust/perspective-viewer/src/less/config-selector.less
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/src/rust/components/tests/plugin_selector.rs
  rust/perspective-viewer/src/rust/config/filters.rs
Labels: cla-present

#1542 Fix column section collapse with expressions
  rust/perspective-viewer/src/rust/components/column_selector.rs
Labels: cla-present

#1433 add some light sdist tests and upload sdist in CI
  azure-pipelines.yml
  python/perspective/scripts/build_sdist.sh
  python/perspective/scripts/test_wheels.sh
Labels: internal, Python, cla-present

#1547 Boolean column filter controls for `<perspective-viewer>`
  cpp/perspective/build.js
  packages/perspective-test/src/js/index.js
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  python/perspective/setup.py
  rust/perspective-viewer/src/less/aggregate-selector.less
  rust/perspective-viewer/src/less/checkbox.less
  rust/perspective-viewer/src/less/config-selector.less
  rust/perspective-viewer/src/less/dropdown.less
  rust/perspective-viewer/src/less/filter-item.less
  rust/perspective-viewer/src/less/variables.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/containers/dropdown.rs
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/src/rust/config/column_type.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/themes/material.dark.less
  rust/perspective-viewer/src/themes/material.less
  rust/perspective-viewer/test/js/expressions.spec.js
  rust/perspective-viewer/test/results/results.json
Labels: cla-present

#1549 Persistent column widths
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
Labels: cla-present

#1551 Fixes `bucket()` computed function validation
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/expressions.js
  packages/perspective/test/js/expressions/parsing.js
  python/perspective/perspective/table/_utils.py
Labels: cla-present

#1548 Return booleans from expression comparisons, allow for vectors to be defined in expressions
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/context_unit.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/expression_tables.cpp
  cpp/perspective/src/cpp/multi_sort.cpp
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/include/perspective/computed_expression.h
  cpp/perspective/src/include/perspective/computed_function.h
  cpp/perspective/src/include/perspective/exprtk.h
  cpp/perspective/src/include/perspective/scalar.h
  packages/perspective-bench/bench/versions.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/expressions.js
  packages/perspective/test/js/expressions/conversions.js
  packages/perspective/test/js/expressions/datetime.js
  packages/perspective/test/js/expressions/functionality.js
  packages/perspective/test/js/expressions/invariant.js
  packages/perspective/test/js/expressions/multiple_views.js
  packages/perspective/test/js/expressions/numeric.js
  packages/perspective/test/js/expressions/string.js
  packages/perspective/test/js/expressions/updates.js
  packages/perspective/test/js/expressions/vectors.js
  packages/perspective/test/js/to_format.js
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/tests/table/test_view.py
  python/perspective/perspective/tests/table/test_view_expression.py
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/exprtk/language.rs
  rust/perspective-viewer/src/rust/js/perspective.rs
Labels: enhancement, C++, cla-present

#1553 Boolean datagrid columns
  packages/perspective-viewer-datagrid/src/js/editing.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/test/results/results.json
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/themes/material-dense.dark.less
  rust/perspective-viewer/src/themes/material-dense.less
  rust/perspective-viewer/src/themes/material.less
Labels: cla-present

#1554 Fix hidden sort aggregate as `unique` only when sorted on the same axis
  cpp/perspective/src/cpp/view_config.cpp
  packages/perspective/test/js/sort.js
  rust/perspective-viewer/src/themes/material.less
Labels: cla-present

#1556 Fix examples
  .gitattributes
  docker/docs/Dockerfile
  docs/static/css/custom.css
  docs/static/css/material.dark.less
  examples/blocks/src/citibike/citibike.js
  examples/blocks/src/custom/index.html
  examples/blocks/src/dataset/index.html
  examples/webpack/package.json
  examples/webpack/src/index.js
  examples/webpack/webpack.config.js
  examples/workspace/src/index.html
  examples/workspace/src/index.js
  examples/workspace/src/index.less
  packages/perspective-jupyterlab/test/results/results.json
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/test/results/results.json
  packages/perspective-webpack-plugin/index.js
  packages/perspective-webpack-plugin/package.json
  packages/perspective-workspace/test/results/results.json
  packages/perspective/src/config/common.config.js
  rust/perspective-viewer/README.md
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/less/split-panel.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/active_column.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/components/expression_toolbar.rs
  rust/perspective-viewer/src/rust/components/inactive_column.rs
  rust/perspective-viewer/src/rust/custom_elements/modal.rs
  rust/perspective-viewer/src/rust/js/monaco.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/themes/material-dense.dark.less
  rust/perspective-viewer/src/themes/material-dense.less
  rust/perspective-viewer/src/themes/material.dark.less
  rust/perspective-viewer/src/themes/material.less
  rust/perspective-viewer/test/js/expressions.spec.js
  rust/perspective-viewer/test/results/results.json
  rust/perspective-viewer/webpack.inline.config.js
Labels: cla-present

#1552 Fix python wheel CI
  python/perspective/scripts/test_wheels.sh
Labels: cla-present

#1557 Make `/node_modules` external to TS
  azure-pipelines.yml
  rust/perspective-viewer/rollup.config.js
Labels: cla-present
