Repository finos/perspective, pull requests merged in 2021-02, with the labels that each got.

#1318 Fix for layout jitter in the Column Selector
  .gitattributes
  packages/perspective-jupyterlab/test/results/linux.docker.json
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/src/html/viewer.html
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/computed_expression_widget.less
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/test/results/linux.docker.json
Labels: JS, bug, cla-present

#1319 Docs site updates
  docs/logo.js
  docs/package.json
  docs/pages/en/index.js
  docs/siteConfig.js
  docs/static/js/animation.js
  packages/perspective-bench/package.json
  packages/perspective-test/package.json
  packages/perspective-webpack-plugin/package.json
  scripts/build_js.js
  scripts/setup.js
Labels: JS, cla-present, internal

#1320 Fix missing return in ctx0::notify
  cpp/perspective/src/cpp/context_zero.cpp
  packages/perspective/test/js/filters.js
Labels: C++, bug, cla-present

#1321 Update regular-table to 0.2.1
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective/src/config/common.config.js
  yarn.lock
Labels: JS, cla-present, internal

#1322 Export inline `@finos/perspective` by default, and simplify some package `dist` with rollup
  package.json
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/plugin/template.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/config/cjs.config.js
  packages/perspective-viewer-datagrid/src/config/rollup.config.js
  packages/perspective-viewer-datagrid/src/config/webpack.config.js
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/config/cjs.config.js
  packages/perspective-viewer/src/config/rollup.config.js
  packages/perspective-viewer/src/config/umd.config.js
  packages/perspective-viewer/src/js/row.js
  packages/perspective-workspace/src/js/index.js
  packages/perspective/package.json
  packages/perspective/src/config/common.config.js
  python/perspective/package.json
  scripts/setup.js
  scripts/test_js.js
  yarn.lock
Labels: JS, cla-present, internal

#1323 Fix `@finos/perspective-jupyterlab` compat with webpack5
  packages/perspective/src/js/config/__node.js
  packages/perspective/src/js/config/index.js
Labels: cla-present

#1314 Status Bar Component
  .gitignore
  .rustfmt.toml
  azure-pipelines.yml
  package.json
  packages/perspective-jupyterlab/src/config/plugin.config.js
  packages/perspective-jupyterlab/src/config/webpack.config.js
  packages/perspective-jupyterlab/test/js/mocks/manager.js
  packages/perspective-jupyterlab/test/js/resize.spec.js
  packages/perspective-jupyterlab/test/results/linux.docker.json
  packages/perspective-viewer-d3fc/test/js/integration/ohlc.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/test/results/linux.docker.json
  packages/perspective-viewer/package.json
  packages/perspective-viewer/src/config/rollup.config.js
  packages/perspective-viewer/src/config/umd.config.js
  packages/perspective-viewer/src/html/viewer.html
  packages/perspective-viewer/src/js/utils.js
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/status_bar.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/js/leaks.spec.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-workspace/config/cjs.config.js
  packages/perspective-workspace/config/umd.config.js
  packages/perspective-workspace/config/watch.config.js
  packages/perspective-workspace/test/results/linux.docker.json
  packages/perspective/src/config/common.config.js
  rust/perspective-vieux/.cargo/config.toml
  rust/perspective-vieux/Cargo.lock
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/babel.config.js
  rust/perspective-vieux/package.json
  rust/perspective-vieux/rollup.config.js
  rust/perspective-vieux/src/js/bootstrap.js
  rust/perspective-vieux/src/js/index.js
  rust/perspective-vieux/src/less/container.less
  rust/perspective-vieux/src/rust/copy.rs
  rust/perspective-vieux/src/rust/download.rs
  rust/perspective-vieux/src/rust/lib.rs
  rust/perspective-vieux/src/rust/status_bar.rs
  rust/perspective-vieux/src/rust/utils.rs
  rust/perspective-vieux/src/rust/utils/perspective.rs
  rust/perspective-vieux/tests/status_bar.rs
  scripts/setup.js
  scripts/test_js.js
Labels: Rust, cla-present, enhancement

#1326 Add `SplitPanel` and port to Yew
  packages/perspective-jupyterlab/test/js/resize.spec.js
  packages/perspective-test/src/js/index.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/js/integration/candlestick.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/ohlc.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/treemap.spec.js
  packages/perspective-viewer-d3fc/test/results/linux.docker.json
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  packages/perspective-viewer/src/config/rollup.config.js
  packages/perspective-viewer/src/html/viewer.html
  packages/perspective-viewer/src/js/viewer.js
  packages/perspective-viewer/src/js/viewer/action_element.js
  packages/perspective-viewer/src/js/viewer/dom_element.js
  packages/perspective-viewer/src/js/viewer/perspective_element.js
  packages/perspective-viewer/src/less/default.less
  packages/perspective-viewer/src/less/viewer.less
  packages/perspective-viewer/src/themes/material-dense.less
  packages/perspective-viewer/src/themes/material.less
  packages/perspective-viewer/test/js/computed_expressions.spec.js
  packages/perspective-viewer/test/js/filters.spec.js
  packages/perspective-viewer/test/js/leaks.spec.js
  packages/perspective-viewer/test/js/regressions.spec.js
  packages/perspective-viewer/test/js/render_warning_tests.js
  packages/perspective-viewer/test/js/responsive_tests.js
  packages/perspective-viewer/test/js/simple_tests.js
  packages/perspective-viewer/test/js/slow.spec.js
  packages/perspective/src/config/common.config.js
  rust/perspective-vieux/Cargo.lock
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/package.json
  rust/perspective-vieux/rollup.config.js
  rust/perspective-vieux/src/js/bootstrap.js
  rust/perspective-vieux/src/js/index.js
  rust/perspective-vieux/src/less/container.less
  rust/perspective-vieux/src/less/perspective-vieux.less
  rust/perspective-vieux/src/less/split-panel.less
  rust/perspective-vieux/src/less/status-bar.less
  rust/perspective-vieux/src/rust/components/mod.rs
  rust/perspective-vieux/src/rust/components/perspective_vieux.rs
  rust/perspective-vieux/src/rust/components/split_panel.rs
  rust/perspective-vieux/src/rust/components/status_bar.rs
  rust/perspective-vieux/src/rust/components/status_bar_counter.rs
  rust/perspective-vieux/src/rust/components/tests/mod.rs
  rust/perspective-vieux/src/rust/components/tests/split_panel.rs
  rust/perspective-vieux/src/rust/components/tests/status_bar.rs
  rust/perspective-vieux/src/rust/components/tests/status_bar_counter.rs
  rust/perspective-vieux/src/rust/lib.rs
  rust/perspective-vieux/src/rust/session.rs
  rust/perspective-vieux/src/rust/session/copy.rs
  rust/perspective-vieux/src/rust/session/download.rs
  rust/perspective-vieux/src/rust/session/view_subscription.rs
  rust/perspective-vieux/src/rust/status_bar.rs
  rust/perspective-vieux/src/rust/utils.rs
  rust/perspective-vieux/src/rust/utils/perspective.rs
  rust/perspective-vieux/tests/perspective_vieux.rs
  rust/perspective-vieux/tests/status_bar.rs
Labels: cla-present, internal

#1331 Fix #1324: use ~major.minor.patch in PerspectiveWidget versioning
  python/perspective/perspective/widget/widget.py
Labels: Python, cla-present, internal
