Repository finos/perspective, pull requests merged in 2021-03, with the labels that each got.

#1342 Replace `emsdk-npm` with simple script
  .gitignore
  cpp/perspective/package.json
  package.json
  scripts/install_emsdk.js
  scripts/run_emsdk.js
  yarn.lock
Labels: cla-present, internal

#1341 fix binder
  binder/postBuild
  binder/requirements.txt
Labels: cla-present, internal

#1338 Add nightly complete builds
  azure-pipelines.yml
Labels: cla-present

#1343 Fix D3FC label font bug
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer/src/themes/material.less
Labels: cla-present, styling

#1349 Fix timezone tests to take DST into account
  packages/perspective/test/js/timezone/timezone.spec.js
Labels: cla-present

#1351 install boost via choco
  azure-pipelines.yml
Labels: cla-present
