Repository finos/perspective, pull requests merged in 2021-11, with the labels that each got.

#1598 More regex functions - find, substring, replace
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/include/perspective/computed_expression.h
  cpp/perspective/src/include/perspective/computed_function.h
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/expressions/conversions.js
  packages/perspective/test/js/expressions/functionality.js
  packages/perspective/test/js/expressions/numeric.js
  packages/perspective/test/js/expressions/string.js
  packages/perspective/test/js/leaks.spec.js
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/tests/table/test_view_expression.py
  rust/perspective-viewer/src/rust/exprtk/language.rs
Labels: enhancement, C++, cla-present

#1613 Publish script for Python
  python/perspective/scripts/build_sdist.sh
  scripts/publish_js.js
  scripts/publish_python.js
Labels: internal, cla-present

#1615 New example
  README.md
  examples/blocks/gists.json
  examples/blocks/src/covid/.block
  examples/blocks/src/covid/README.md
  examples/blocks/src/covid/index.html
Labels: documentation, cla-present

#1617 Fix D3 alt-axis regression
  packages/perspective-viewer-d3fc/src/js/axis/chartFactory.js
  packages/perspective-viewer-d3fc/src/js/legend/legend.js
Labels: cla-present

#1618 Fix `worker.js` cross-origin workaround for CDN
  packages/perspective/src/js/perspective.parallel.js
  rust/perspective-viewer/src/rust/exprtk/init.rs
  rust/perspective-viewer/src/rust/exprtk/mod.rs
  rust/perspective-viewer/src/rust/js/monaco.rs
  tools/perspective-build/worker.js
Labels: cla-present

#1619 Add `wait_for_table` flag to `getTable()`
  examples/blocks/src/custom/custom_plugin.js
  packages/perspective-jupyterlab/src/js/psp_widget.js
  packages/perspective-viewer-datagrid/src/js/plugin.js
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/ts/viewer.ts
  tools/perspective-test/src/js/index.js
Labels: cla-present

#1620 Fix publish through practice
  examples/jupyter-notebooks/Untitled.ipynb
  scripts/publish_python.js
Labels: cla-present

#1621 `PerspectiveWidget()` dialog theme fix
  packages/perspective-jupyterlab/src/less/index.less
  rust/perspective-viewer/src/themes/material-dense.dark.less
  rust/perspective-viewer/src/themes/material-dense.less
  rust/perspective-viewer/src/themes/material.dark.less
  rust/perspective-viewer/src/themes/material.less
Labels: bug

#1622 Fix `datetime` filter timezone bug
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/src/rust/utils/datetime.rs
  rust/perspective-viewer/src/rust/utils/errors.rs
  rust/perspective-viewer/src/rust/utils/mod.rs
Labels: cla-present

#1623 Fix partial-updates on tables with `limit` set for python
  python/perspective/perspective/src/fill.cpp
  python/perspective/perspective/tests/table/test_table_limit.py
  rust/perspective-viewer/build.js
Labels: bug, cla-present

#1624 Fix partial-updates on tables with `limit` set for javascript
  cpp/perspective/src/cpp/emscripten.cpp
  packages/perspective/test/js/constructors.js
Labels: cla-present

#1625 add threads explicit on mac
  cpp/perspective/CMakeLists.txt
Labels: cla-present

#1626 bump windows build for vc 14.2 / vs 16 2019, add macos 11 build for py3.9
  azure-pipelines.yml
  python/perspective/setup.py
Labels: cla-present

#1629 Fix Azure windows wheel step
  azure-pipelines.yml
Labels: cla-present

#1631 Update CMakeLists.txt for more thread help on mac for conda
  cpp/perspective/CMakeLists.txt
Labels: internal, cla-present

#1635 [Formatting] force line-feed line endings for all text files for easier windows development
  .gitattributes
Labels: internal, cla-present

#1630 [Formatting] Fix mixed tabs/spaces in C++ CMakeLists.txt
  cpp/perspective/CMakeLists.txt
Labels: internal, cla-present
