Repository finos/perspective, pull requests merged in 2021-06, with the labels that each got.

#1436 Fix benchmarks and remove versions pre 0.5.0 from benchmarking
  docs/package.json
  packages/perspective-bench/bench/perspective.benchmark.js
  packages/perspective-bench/bench/versions.js
  packages/perspective-bench/src/js/bench.js
  packages/perspective-bench/src/js/browser_runtime.js
  packages/perspective/src/js/perspective.js
Labels: JS, cla-present, internal

#1435 Optional lazy-load `monaco-editor`
  packages/perspective-viewer/test/html/superstore.html
  packages/perspective-viewer/test/js/expressions.spec.js
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective-webpack-plugin/index.js
  rust/perspective-vieux/src/js/vieux.js
  rust/perspective-vieux/src/less/expression-editor.less
  rust/perspective-vieux/src/rust/components/expression_editor.rs
  rust/perspective-vieux/src/rust/custom_elements/expression_editor.rs
  rust/perspective-vieux/src/rust/custom_elements/modal.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux.rs
  rust/perspective-vieux/src/rust/exprtk.rs
  rust/perspective-vieux/src/rust/utils/monaco.rs
Labels: cla-present

#1439 Add theme support to monaco
  packages/perspective-viewer/src/themes/material.dark.less
  packages/perspective-workspace/src/theme/material.dark.less
  packages/perspective-workspace/src/theme/material.less
  rust/perspective-vieux/src/rust/components/expression_editor.rs
  rust/perspective-vieux/src/rust/custom_elements/expression_editor.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux.rs
  rust/perspective-vieux/src/rust/exprtk.rs
Labels: cla-present

#1437 Add integer, float, string, date, and datetime conversion functions
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/config.cpp
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/expression_tables.cpp
  cpp/perspective/src/cpp/time.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/computed_expression.h
  cpp/perspective/src/include/perspective/computed_function.h
  cpp/perspective/src/include/perspective/config.h
  cpp/perspective/src/include/perspective/expression_tables.h
  cpp/perspective/src/include/perspective/time.h
  cpp/perspective/src/include/perspective/view.h
  cpp/perspective/src/include/perspective/view_config.h
  packages/perspective/test/js/expressions.js
  packages/perspective/test/js/expressions/conversions.js
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/tests/table/test_view_expression.py
  rust/perspective-vieux/src/rust/exprtk.rs
Labels: C++, cla-present, enhancement

#1441 Output more metadata on expression errors, fix #1440
  azure-pipelines.yml
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/binding.h
  cpp/perspective/src/include/perspective/computed_expression.h
  packages/perspective/index.d.ts
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/expressions/conversions.js
  packages/perspective/test/js/expressions/functionality.js
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/table/test_view_expression.py
  rust/perspective-vieux/src/rust/exprtk.rs
Labels: C++, cla-present, enhancement

#1443 Column name completion for `monaco`
  cpp/perspective/package.json
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/include/perspective/gnode.h
  examples/workspace/src/index.js
  packages/perspective-test/src/js/index.js
  packages/perspective-viewer-datagrid/src/js/plugin_menu.js
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer/src/less/fonts.less
  packages/perspective-viewer/src/less/row.less
  packages/perspective-viewer/test/js/expressions.spec.js
  packages/perspective-viewer/test/results/linux.docker.json
  rust/perspective-vieux/Cargo.lock
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/src/js/vieux.js
  rust/perspective-vieux/src/rust/components/column_style.rs
  rust/perspective-vieux/src/rust/components/expression_editor.rs
  rust/perspective-vieux/src/rust/components/radio_list.rs
  rust/perspective-vieux/src/rust/components/split_panel.rs
  rust/perspective-vieux/src/rust/components/tests/column_style.rs
  rust/perspective-vieux/src/rust/components/tests/radio_list.rs
  rust/perspective-vieux/src/rust/components/tests/status_bar.rs
  rust/perspective-vieux/src/rust/components/vieux.rs
  rust/perspective-vieux/src/rust/custom_elements/column_style.rs
  rust/perspective-vieux/src/rust/custom_elements/expression_editor.rs
  rust/perspective-vieux/src/rust/custom_elements/modal.rs
  rust/perspective-vieux/src/rust/custom_elements/tests/vieux.rs
  rust/perspective-vieux/src/rust/custom_elements/vieux.rs
  rust/perspective-vieux/src/rust/exprtk.rs
  rust/perspective-vieux/src/rust/exprtk/completions.rs
  rust/perspective-vieux/src/rust/exprtk/init.rs
  rust/perspective-vieux/src/rust/exprtk/language.rs
  rust/perspective-vieux/src/rust/exprtk/mod.rs
  rust/perspective-vieux/src/rust/session.rs
  rust/perspective-vieux/src/rust/session/copy.rs
  rust/perspective-vieux/src/rust/session/download.rs
  rust/perspective-vieux/src/rust/session/view_subscription.rs
  rust/perspective-vieux/src/rust/utils.rs
  rust/perspective-vieux/src/rust/utils/closure.rs
  rust/perspective-vieux/src/rust/utils/future_to_promise.rs
  rust/perspective-vieux/src/rust/utils/js_object.rs
  rust/perspective-vieux/src/rust/utils/mod.rs
  rust/perspective-vieux/src/rust/utils/monaco.rs
  rust/perspective-vieux/src/rust/utils/perspective.rs
  rust/perspective-vieux/src/rust/utils/request_animation_frame.rs
  rust/perspective-vieux/src/rust/utils/testing.rs
  rust/perspective-vieux/src/rust/utils/tests/mod.rs
  rust/perspective-vieux/src/rust/utils/tests/perspective.rs
  rust/perspective-vieux/src/rust/utils/tests/request_animation_frame.rs
  rust/perspective-vieux/src/rust/utils/weak_component_link.rs
Labels: cla-present

#1444 Error reporting for `monaco`
  packages/perspective-viewer/test/results/linux.docker.json
  rust/perspective-vieux/src/less/expression-editor.less
  rust/perspective-vieux/src/rust/components/expression_editor.rs
  rust/perspective-vieux/src/rust/exprtk/language.rs
  rust/perspective-vieux/src/rust/session.rs
  rust/perspective-vieux/src/rust/utils/monaco.rs
  rust/perspective-vieux/src/rust/utils/perspective.rs
Labels: cla-present, enhancement

#1446 Update Jupyter Notebook Examples
  examples/jupyter-notebooks/filters.ipynb
  examples/jupyter-notebooks/pandas.ipynb
  examples/jupyter-notebooks/pandas_pivot.ipynb
  examples/jupyter-notebooks/table_tutorial.ipynb
  examples/jupyter-notebooks/widget_tutorial.ipynb
  examples/tornado-python/README.md
Labels: Jupyter, cla-present

#1450 Expression editor bug fixes
  packages/perspective-jupyterlab/src/less/index.less
  packages/perspective-viewer/test/results/linux.docker.json
  packages/perspective/src/js/perspective.js
  rust/perspective-vieux/Cargo.lock
  rust/perspective-vieux/Cargo.toml
  rust/perspective-vieux/src/less/expression-editor.less
  rust/perspective-vieux/src/rust/components/expression_editor.rs
  rust/perspective-vieux/src/rust/custom_elements/modal.rs
  rust/perspective-vieux/src/rust/session.rs
  rust/perspective-vieux/src/rust/session/view_subscription.rs
Labels: cla-present

#1447 Read CSV strings in perspective-python
  cmake/arrow/CMakeLists.txt
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/arrow_csv.cpp
  cpp/perspective/src/cpp/arrow_loader.cpp
  cpp/perspective/src/cpp/column.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/include/perspective/arrow_loader.h
  cpp/perspective/src/include/perspective/column.h
  packages/perspective/test/js/constructors.js
  python/perspective/perspective/include/perspective/python/table.h
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/core/test_async.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_update.py
Labels: Python, cla-present, enhancement

#1453 Build Windows wheel, limit wheel builds to scheduled and tagged builds
  azure-pipelines.yml
  scripts/_wheel_python.js
Labels: Python, cla-present, internal

#1455 Fixes #1340 - removes dependency on removed ipywidgets API
  python/perspective/perspective/tests/client_mode/test_client_mode.py
  python/perspective/perspective/widget/widget.py
Labels: cla-present

#1459 Spark bar
  azure-pipelines.yml
  packages/perspective-viewer-datagrid/src/js/color_utils.js
  packages/perspective-viewer-datagrid/src/js/plugin_menu.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/row-hover.less
  rust/perspective-vieux/src/less/radio-list.less
  rust/perspective-vieux/src/rust/components/column_style.rs
  rust/perspective-vieux/src/rust/components/radio_list.rs
  rust/perspective-vieux/src/rust/components/tests/column_style.rs
  rust/perspective-vieux/src/rust/components/tests/plugin_selector.rs
  rust/perspective-vieux/src/rust/custom_elements/column_style.rs
  rust/perspective-vieux/src/rust/plugin/registry.rs
Labels: cla-present

#1464 Fix memory errors when streaming updates with expression columns
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/expression_tables.cpp
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/expression_tables.h
  packages/perspective/test/js/expressions/updates.js
  python/perspective/perspective/tests/table/test_view_expression.py
Labels: C++, bug, cla-present
