Repository finos/perspective, pull requests merged in 2021-12, with the labels that each got.

#1634 Overload re2 cmakelists to fix cmake/threads detection issue on conda-forge mac builds, and pin C++ dependency versions
  azure-pipelines.yml
  cmake/Pybind.txt.in
  cmake/arrow.txt.in
  cmake/double-conversion.txt.in
  cmake/hopscotch.txt.in
  cmake/ordered-map.txt.in
  cmake/rapidjson.txt.in
  cmake/re2.txt.in
  cmake/re2/CMakeLists.txt
  cpp/perspective/CMakeLists.txt
Labels: internal, cla-present, dependencies

#1633 Add auto-resizing to `<perspective-viewer>`
  docs/js/index.js
  packages/perspective-jupyterlab/src/js/psp_widget.js
  packages/perspective-jupyterlab/test/js/resize.spec.js
  packages/perspective-workspace/src/js/workspace/tabbar.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/js/mod.rs
  rust/perspective-viewer/src/rust/js/resize_observer.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/ts/viewer.ts
  rust/perspective-viewer/test/js/simple_tests.js
  tools/perspective-test/src/js/index.js
Labels: enhancement, cla-present

#1647 Parallelized `.wasm` download and deferred font loading
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/view.cpp
  examples/blocks/dist.js
  examples/blocks/src/editable/index.html
  examples/react/src/index.tsx
  examples/webpack-cross-origin/src/index.js
  packages/perspective/build.js
  packages/perspective/src/js/perspective.browser.js
  packages/perspective/src/js/perspective.node.js
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/build.js
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/less/fonts.less
  rust/perspective-viewer/src/rust/components/font_loader.rs
  rust/perspective-viewer/src/rust/components/mod.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/utils/request_animation_frame.rs
  rust/perspective-viewer/src/themes/material.less
  rust/perspective-viewer/src/ts/extensions.ts
  rust/perspective-viewer/src/ts/init.ts
  rust/perspective-viewer/src/ts/perspective-viewer.ts
  rust/perspective-viewer/src/ts/plugin.ts
  rust/perspective-viewer/src/ts/style.ts
  rust/perspective-viewer/src/ts/viewer.ts
  scripts/publish_python.js
  tools/perspective-build/wasm.js
  tools/perspective-build/worker.js
Labels: enhancement, cla-present

#1649 Emit `.d.ts` declaration files for `@finos/perspective-viewer`
  examples/react/src/index.tsx
  packages/perspective-webpack-plugin/index.js
  packages/perspective/src/js/perspective.node.js
  rust/perspective-viewer/build.js
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/rust/js/monaco.rs
  rust/perspective-viewer/tsconfig.json
Labels: cla-present

#1650 Fix column-selector collapse (inverted)
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/test/results/results.json
Labels: bug, cla-present

#1651 Remove wasm-pack artifacts which interfere with perspective packaging
  rust/perspective-viewer/build.js
Labels: cla-present

#1653 Fix `datetime`/`date`/`integer`/`float` filter occasionally resetting while typing
  rust/perspective-viewer/src/rust/components/filter_item.rs
Labels: cla-present

#1652 D3FC Treemap bug fixes
  packages/perspective-viewer-d3fc/src/js/charts/treemap.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapTransitions.js
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionEvent.js
Labels: bug, cla-present

#1657 Implement `getView()`
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/ts/viewer.ts
Labels: cla-present

#1654 add missing definition for re2 on os x to reenable conda builds
  cmake/arrow/CMakeLists.txt
  cmake/modules/FindExprTk.cmake
  cmake/modules/FindRe2.cmake
  cmake/re2/CMakeLists.txt
  cpp/perspective/CMakeLists.txt
Labels: internal, Python, cla-present

#1661 Fix `position: sticky` Chrome render bug in `perspective-viewer-datagrid`
  packages/perspective-viewer-datagrid/package.json
  yarn.lock
Labels: cla-present

#1643 Resizable expression editor
  rust/perspective-viewer/build.js
  rust/perspective-viewer/src/less/expression-editor.less
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/js/monaco.rs
  rust/perspective-viewer/tsconfig.json
Labels: cla-present

#1660 D3FC fast `Treemap`, fix for non-POSIX time axis, better resize
  packages/perspective-viewer-d3fc/src/js/axis/timeAxis.js
  packages/perspective-viewer-d3fc/src/js/layout/gridLayoutMultiChart.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLabel.js
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: cla-present

#1662 Fix `perspective-workspace` and add `monaco-editor-webpack-plugin` compatibility to `perspective-webpack-plugin`
  azure-pipelines.yml
  examples/react-monaco/README.md
  examples/react-monaco/package.json
  examples/react-monaco/src/index.css
  examples/react-monaco/src/index.html
  examples/react-monaco/src/index.tsx
  examples/react-monaco/tsconfig.json
  examples/react-monaco/webpack.config.js
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
  packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstClick.js
  packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstSeries.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapTransitions.js
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective-webpack-plugin/index.js
  packages/perspective-webpack-plugin/package.json
  packages/perspective-workspace/build.js
  packages/perspective-workspace/package.json
  packages/perspective-workspace/src/js/perspective-workspace.js
  packages/perspective-workspace/src/js/workspace/discrete.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/dockpanel.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/less/viewer.less
  packages/perspective-workspace/src/less/widget.less
  packages/perspective-workspace/src/less/workspace.less
  packages/perspective-workspace/src/themes/material.dark.less
  packages/perspective-workspace/test/results/results.json
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/rust/js/monaco.rs
  rust/perspective-viewer/src/ts/perspective-viewer.ts
  tools/perspective-build/replace.js
  tools/perspective-build/resolve.js
  tools/perspective-build/worker.js
Labels: cla-present

#1672 Build windows wheel every time so its tested
  .gitignore
  azure-pipelines.yml
  cmake/Pybind.txt.in
  cmake/arrow.txt.in
  cmake/date.txt.in
  cmake/double-conversion.txt.in
  cmake/exprtk.txt.in
  cmake/flatbuffers.txt.in
  cmake/hopscotch.txt.in
  cmake/modules/FindColor.cmake
  cmake/modules/FindExprTk.cmake
  cmake/modules/FindFlatbuffers.cmake
  cmake/modules/FindNumPy.cmake
  cmake/modules/FindPybind.cmake
  cmake/modules/FindPythonHeaders.cmake
  cmake/modules/FindRe2.cmake
  cmake/ordered-map.txt.in
  cmake/rapidjson.txt.in
  cmake/re2.txt.in
  cpp/perspective/CMakeLists.txt
  python/perspective/MANIFEST.in
  python/perspective/setup.py
Labels: cla-present

#1675 Fix `perspective-workspace` errors
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-workspace/src/js/perspective-workspace.js
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/renderer.rs
Labels: cla-present

#1673 Preserve `expressions` on reset (shift+ to force)
  rust/perspective-viewer/src/rust/components/status_bar.rs
  rust/perspective-viewer/src/rust/components/tests/status_bar.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/config/view_config.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/ts/viewer.ts
  rust/perspective-viewer/test/js/expressions.spec.js
  rust/perspective-viewer/test/results/results.json
Labels: cla-present

#1674 Use `puppeteer` for app from CLI
  packages/perspective-cli/package.json
  packages/perspective-cli/src/html/index.html
  packages/perspective-cli/src/js/index.js
  packages/perspective-jupyterlab/test/html/resize.html
  packages/perspective-viewer-d3fc/test/html/shares-template.html
  packages/perspective-viewer-d3fc/test/html/simple-template.html
  packages/perspective-viewer-d3fc/test/html/themed-template.html
  packages/perspective-viewer-datagrid/test/html/superstore.html
  packages/perspective-workspace/test/html/index.html
  packages/perspective/src/js/perspective.node.js
  packages/perspective/test/html/test.html
  rust/perspective-viewer/package.json
  rust/perspective-viewer/test/html/blank.html
  rust/perspective-viewer/test/html/filters.html
  rust/perspective-viewer/test/html/superstore.html
  tools/perspective-build/build.js
Labels: cla-present

#1676 Fix Treemap zoom when a group level is `null`
  packages/perspective-viewer-d3fc/src/js/data/treeData.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLabel.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLevelCalculation.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapTransitions.js
  packages/perspective-workspace/test/js/integration/restore.spec.js
  rust/perspective-viewer/src/rust/components/config_selector.rs
  rust/perspective-viewer/src/rust/config/view_config.rs
Labels: bug, cla-present

#1681 Benchmarks update
  azure-pipelines.yml
  package.json
  packages/perspective/src/js/perspective.node.js
  scripts/bench.js
  tools/perspective-bench/bench/perspective.benchmark.js
  tools/perspective-bench/bench/versions.js
  tools/perspective-bench/package.json
  tools/perspective-bench/src/html/benchmark.html
  tools/perspective-bench/src/js/bench.js
  tools/perspective-bench/src/js/browser_runtime.js
Labels: cla-present

#1680 Upgrade Arrow to `6.0.2`
  cmake/arrow.txt.in
  cmake/arrow/CMakeLists.txt
  cmake/arrow/config.h
Labels: cla-present

#1683 80% reduction in `.wasm` asset size
  .husky/pre-push
  cpp/perspective/build.js
  package.json
  packages/perspective/package.json
  packages/perspective/src/js/perspective.browser.js
  rust/perspective-viewer/build.js
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/ts/init.ts
  tools/perspective-build/build.js
  tools/perspective-build/wasm.js
  tools/perspective-build/worker.js
  yarn.lock
Labels: enhancement, cla-present

#1685 `date` and `datetime` filter bug fixes and support for non-Chrome browsers
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/src/rust/utils/datetime.rs
Labels: cla-present

#1679 fix wheel build, make extension first to ensure binaries are inlined, then assemble wheel
  azure-pipelines.yml
  python/perspective/MANIFEST.in
  scripts/_wheel_python.js
Labels: cla-present

#1688 Reduce CI: Turn off branch builds, only build on PRs to master
  azure-pipelines.yml
Labels: cla-present
