Repository finos/perspective, pull requests merged in 2022-02, with the labels that each got.

#1713 Update docs for new theme API
  .gitignore
  docs/js/concepts.js
  docs/js/examples.js
  docs/js/fonts.js
  docs/js/index.js
  docs/md/js.md
  docs/package.json
  docs/pages/en/index.js
  docs/siteConfig.js
  docs/static/css/custom.css
  docs/static/css/material-dark.less
  docs/static/css/material.dark.less
  docs/webpack.config.js
  examples/blocks/dist.js
  examples/blocks/src/citibike/index.html
  examples/blocks/src/covid/index.html
  examples/blocks/src/csv/index.html
  examples/blocks/src/dataset/index.html
  examples/blocks/src/editable/index.html
  examples/blocks/src/fractal/index.css
  examples/blocks/src/fractal/index.html
  examples/blocks/src/iex/index.html
  examples/blocks/src/movies/index.html
  examples/blocks/src/olympics/index.html
  examples/blocks/src/streaming/index.html
  examples/blocks/src/superstore/index.html
  examples/promo/src/index.js
  examples/react-monaco/src/index.css
  examples/react/src/index.css
  examples/webpack-cross-origin/src/index.css
  examples/webpack-example/src/index.js
  packages/perspective-jupyterlab/src/less/index.less
  packages/perspective-workspace/src/themes/material-dark.less
  packages/perspective-workspace/src/themes/material.less
  packages/perspective-workspace/test/results/results.json
  rust/perspective-viewer/src/rust/custom_elements/modal.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/themes/material-dark.less
  rust/perspective-viewer/src/themes/material.less
  rust/perspective-viewer/src/themes/monokai.less
  rust/perspective-viewer/src/themes/solarized-dark.less
  rust/perspective-viewer/src/themes/solarized.less
  rust/perspective-viewer/src/themes/vaporwave.less
Labels: documentation, cla-present

#1716 Drag/drop tests
  examples/blocks/dist.js
  package.json
  packages/perspective-viewer-d3fc/src/js/charts/xy-line.js
  rust/perspective-viewer/src/rust/components/active_column.rs
  rust/perspective-viewer/src/rust/components/aggregate_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/config_selector.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/components/expression_toolbar.rs
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/src/rust/components/inactive_column.rs
  rust/perspective-viewer/src/rust/components/plugin_selector.rs
  rust/perspective-viewer/src/rust/components/sort_item.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/config/column_type.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/custom_events.rs
  rust/perspective-viewer/src/rust/exprtk/mod.rs
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/rust/model.rs
  rust/perspective-viewer/src/rust/model/columns_iter_set.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/rust/renderer/limits.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/metadata.rs
  rust/perspective-viewer/src/rust/utils/mod.rs
  rust/perspective-viewer/test/html/column-selector-modes.html
  rust/perspective-viewer/test/js/dragdrop.spec.js
  rust/perspective-viewer/test/results/results.json
  yarn.lock
Labels: internal, cla-present

#1715 Add column-style-checkbox css variables
  rust/perspective-viewer/src/less/column-style.less
  rust/perspective-viewer/src/themes/material.less
Labels: cla-present

#1721 Add scroll_lock optional free scroll mode for `@finos/perspective-viewer-datagrid`
  docs/js/features.js
  docs/js/index.js
  docs/static/css/custom.css
  examples/blocks/src/movies/layout.json
  examples/blocks/src/streaming/streaming.js
  packages/perspective-jupyterlab/test/js/resize.spec.js
  packages/perspective-jupyterlab/test/results/results.json
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/editing.js
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/less/material.less
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/toolbar.less
  packages/perspective-viewer-datagrid/test/results/results.json
  packages/perspective-workspace/test/js/integration/restore.spec.js
  packages/perspective-workspace/test/results/results.json
  python/perspective/perspective/tests/viewer/test_viewer.py
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/rust/components/status_bar.rs
  rust/perspective-viewer/src/ts/migrate.ts
  rust/perspective-viewer/test/js/migrate_viewer.spec.js
  rust/perspective-viewer/test/results/results.json
  yarn.lock
Labels: enhancement, cla-present, breaking

#1722 Virtual column selector
  packages/perspective-jupyterlab/test/js/resize.spec.js
  packages/perspective-jupyterlab/test/results/results.json
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/less/scroll-panel.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/active_column.rs
  rust/perspective-viewer/src/rust/components/aggregate_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/config_selector.rs
  rust/perspective-viewer/src/rust/components/containers/mod.rs
  rust/perspective-viewer/src/rust/components/containers/scroll_panel.rs
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/inactive_column.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/model/columns_iter_set.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/utils/mod.rs
  rust/perspective-viewer/test/results/results.json
Labels: bug, cla-present

#1714 remove defunct IEX Cloud example - replace with Polygon.io stock example
  README.md
Labels: cla-present

#1724 Fix python memory leak in `table()`
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/table/test_leaks.py
  python/perspective/setup.py
  scripts/test_python.js
Labels: cla-present

#1725 Vertical resize for expression editor
  examples/blocks/src/fractal/index.css
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/less/expression-editor.less
  rust/perspective-viewer/src/less/fonts.less
  rust/perspective-viewer/src/less/split-panel.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/containers/tests/split_panel.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/custom_elements/expression_editor.rs
  rust/perspective-viewer/src/rust/custom_elements/filter_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/modal.rs
  rust/perspective-viewer/src/rust/custom_elements/number_column_style.rs
  rust/perspective-viewer/src/rust/custom_elements/string_column_style.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/js/monaco.rs
  rust/perspective-viewer/src/rust/renderer/registry.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/test/results/results.json
Labels: enhancement, cla-present

#1726 Fix filtering on string columns containing `null`
  cpp/perspective/src/cpp/build_filter.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/include/perspective/build_filter.h
  cpp/perspective/src/include/perspective/scalar.h
  packages/perspective/test/js/filters.js
Labels: bug, cla-present
