Repository finos/perspective, pull requests merged in 2022-01, with the labels that each got.

#1689 purge six dependency
  python/perspective/perspective/core/data/np.py
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/client_mode/test_client_mode.py
  python/perspective/perspective/tests/conftest.py
  python/perspective/perspective/tests/core/test_async.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_table_infer.py
  python/perspective/perspective/tests/table/test_table_limit.py
  python/perspective/perspective/tests/table/test_table_numpy.py
  python/perspective/perspective/tests/table/test_table_object.py
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/perspective/tests/table/test_to_format.py
  python/perspective/perspective/tests/widget/test_widget.py
  python/perspective/perspective/tornado_handler/tornado_client.py
  python/perspective/perspective/viewer/validate.py
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/widget/widget.py
  python/perspective/setup.py
Labels: internal, cla-present

#1695 Fix auto-reset when `HTMLPerspectiveViewerElement.load()` called twice
  rust/perspective-viewer/src/rust/session.rs
Labels: bug, cla-present

#1696 Fix `perspective-viewer` filter dropdown for values with double quotes
  rust/perspective-viewer/src/rust/session.rs
Labels: bug, cla-present

#1705 Pin `flatc` to 1.12.1
  scripts/install_tools.js
Labels: internal, cla-present

#1707 Fix async mode segfault on `.load()` with indexed Arrow
  cpp/perspective/src/cpp/arrow_loader.cpp
  python/perspective/perspective/include/perspective/python/table.h
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/tests/core/test_async.py
  scripts/test_python.js
Labels: bug, cla-present

#1708 Fix bad filter when `.update()` contains missing string column value
  cpp/perspective/src/cpp/data_table.cpp
  python/perspective/perspective/tests/table/test_table.py
Labels: bug, cla-present

#1712 Add `settings` and `theme` to `perspective-config-update` DOM event and `PerspectiveWidget` python class
  packages/perspective-jupyterlab/src/js/model.js
  packages/perspective-jupyterlab/src/js/psp_widget.js
  packages/perspective-jupyterlab/src/js/renderer.js
  packages/perspective-jupyterlab/src/js/view.js
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/viewer/viewer_traitlets.py
  rust/perspective-viewer/src/rust/components/tests/viewer.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/config.rs
  rust/perspective-viewer/src/rust/config/view_config.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/custom_events.rs
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/test/js/events.spec.js
Labels: bug, cla-present, breaking
