Repository finos/perspective, pull requests merged in 2022-03, with the labels that each got.

#1728 fix: fire config-update evnt on perspective-viewer
  packages/perspective-viewer-datagrid/src/js/plugin_menu.js
Labels: bug, cla-present

#1731 UI small fixes
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  rust/perspective-viewer/src/less/checkbox.less
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/less/column-style.less
  rust/perspective-viewer/src/less/config-selector.less
  rust/perspective-viewer/src/less/expression-editor.less
  rust/perspective-viewer/src/less/render-warning.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/config_selector.rs
  rust/perspective-viewer/src/rust/components/containers/scroll_panel.rs
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/status_bar.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/model.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/themes/material-dark.less
  rust/perspective-viewer/src/themes/material.less
  rust/perspective-viewer/src/themes/solarized-dark.less
  rust/perspective-viewer/src/themes/solarized.less
  rust/perspective-viewer/src/themes/vaporwave.less
  rust/perspective-viewer/test/results/results.json
Labels: bug, cla-present

#1733 Fix bugs reported from docs site
  docs/webpack.config.js
  packages/perspective-viewer-datagrid/package.json
  rust/perspective-viewer/src/themes/material.less
  yarn.lock
Labels: bug

#1736 Update dev docs
  docs/md/development.md
  package.json
Labels: documentation, cla-present

#1737 Allow `@finos/perspective` to run in single-threaded mode
  packages/perspective/src/js/perspective.browser.js
  tools/perspective-build/worker.js
Labels: cla-present

#1741 Disable Windows builds
  azure-pipelines.yml
Labels: cla-present

#1740 Export `.png`, `.html`, `.arrow`
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLabel.js
  packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
  packages/perspective-viewer-d3fc/test/results/results.json
  rust/perspective-viewer/build.js
  rust/perspective-viewer/src/less/dropdown-menu.less
  rust/perspective-viewer/src/less/select.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/aggregate_selector.rs
  rust/perspective-viewer/src/rust/components/containers/dropdown_menu.rs
  rust/perspective-viewer/src/rust/components/containers/mod.rs
  rust/perspective-viewer/src/rust/components/containers/select.rs
  rust/perspective-viewer/src/rust/components/export_dropdown.rs
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/src/rust/components/mod.rs
  rust/perspective-viewer/src/rust/components/plugin_selector.rs
  rust/perspective-viewer/src/rust/components/status_bar.rs
  rust/perspective-viewer/src/rust/components/tests/status_bar.rs
  rust/perspective-viewer/src/rust/custom_elements/export_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/mod.rs
  rust/perspective-viewer/src/rust/js/perspective.rs
  rust/perspective-viewer/src/rust/model.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/download.rs
Labels: enhancement, cla-present

#1745 Add `main` field to package json
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-workspace/package.json
  packages/perspective/package.json
  rust/perspective-viewer/package.json
Labels: cla-present

#1748 Fire `perspective-config-update` event on D3FC legend and axis events
  packages/perspective-viewer-d3fc/src/js/axis/splitterLabels.js
  packages/perspective-viewer-d3fc/src/js/legend/styling/draggableComponent.js
  packages/perspective-viewer-d3fc/test/js/integration/events.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: bug, cla-present

#1746 export `perspective-viewer-datagrid` plugin customElement and it's typings
  packages/perspective-viewer-datagrid/index.d.ts
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/plugin.js
Labels: bug, cla-present

#1754 Disable OSX Python CI
  azure-pipelines.yml
Labels: internal

#1752 D3FC Chart style and bug fixes
  packages/perspective-viewer-d3fc/src/js/charts/area.js
  packages/perspective-viewer-d3fc/src/js/legend/styling/draggableComponent.js
  packages/perspective-viewer-d3fc/src/js/series/areaSeries.js
  packages/perspective-viewer-d3fc/src/js/series/lineSeries.js
  packages/perspective-viewer-d3fc/src/js/zoom/zoomableChart.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/test/results/results.json
  rust/perspective-viewer/src/less/config-selector.less
  rust/perspective-viewer/src/rust/components/containers/mod.rs
  rust/perspective-viewer/src/rust/components/containers/modal_anchor.rs
  rust/perspective-viewer/src/rust/components/copy_dropdown.rs
  rust/perspective-viewer/src/rust/components/export_dropdown.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/components/filter_dropdown.rs
  rust/perspective-viewer/src/rust/components/number_column_style.rs
  rust/perspective-viewer/src/rust/components/string_column_style.rs
  rust/perspective-viewer/src/rust/components/tests/column_style.rs
  rust/perspective-viewer/src/rust/custom_elements/copy_dropdown.rs
  rust/perspective-viewer/src/rust/model.rs
  rust/perspective-viewer/src/rust/model/export_method.rs
  rust/perspective-viewer/src/rust/utils/clipboard.rs
  rust/perspective-viewer/src/rust/utils/download.rs
  rust/perspective-viewer/src/themes/material-dark.less
  rust/perspective-viewer/src/themes/material.less
  rust/perspective-viewer/src/themes/monokai.less
  rust/perspective-viewer/src/themes/solarized-dark.less
  rust/perspective-viewer/src/themes/solarized.less
  rust/perspective-viewer/test/results/results.json
Labels: bug

#1757 Fix flatbuffers
  azure-pipelines.yml
  cmake/arrow/CMakeLists.txt
  cmake/flatbuffers.txt.in
  cmake/modules/FindFlatbuffers.cmake
Labels: cla-present

#1759 Export `perspective-viewer-datagrid` types
  packages/perspective-viewer-d3fc/build.js
  packages/perspective-viewer-datagrid/build.js
  packages/perspective-viewer-datagrid/index.d.ts
  packages/perspective-viewer-datagrid/package.json
Labels: cla-present

#1762 Fix JLab `settings` flicker
  packages/perspective-jupyterlab/src/js/psp_widget.js
  packages/perspective-jupyterlab/src/js/view.js
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
  packages/perspective-jupyterlab/test/results/results.json
Labels: bug, cla-present

#1766 Fix `debug` build script
  rust/perspective-viewer/build.js
Labels: internal

#1769 Fix `--debug` flag for real this time
  examples/blocks/dist.js
  rust/perspective-viewer/build.js
Labels: internal, cla-present

#1772 Fix tree column override width persistence in `perspective-viewer-datagrid`
  packages/perspective-viewer-datagrid/src/js/plugin.js
Labels: cla-present

#1770 Add extra empty column indicator when columns can be appended
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/containers/scroll_panel.rs
  rust/perspective-viewer/src/rust/model/columns_iter_set.rs
  rust/perspective-viewer/test/results/results.json
Labels: enhancement, cla-present
