Repository finos/perspective, pull requests merged in 2022-05, with the labels that each got.

#1793 Fix `sum` aggregate to force re-agg for expression columns
  cpp/perspective/src/cpp/sparse_tree.cpp
Labels: bug, cla-present

#1794 Allow attempt to create workers from file protocol for e.g. electron
  tools/perspective-build/worker.js
Labels: bug, cla-present

#1795 Fix datagrid error when `resetThemes()` is called while hidden
  packages/perspective-viewer-datagrid/src/js/plugin.js
Labels: bug, cla-present

#1796 Add support for LargeUtf8 arrow column type
  cpp/perspective/src/cpp/arrow_loader.cpp
Labels: enhancement, cla-present

#1798 Support autocomplete for IN filter type
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/test/js/dragdrop.spec.js
  rust/perspective-viewer/test/results/results.json
Labels: enhancement

#1804 Make toggle-menu more responsive under load
  packages/perspective-workspace/src/js/workspace/workspace.js
  rust/perspective-viewer/src/rust/renderer.rs
Labels: cla-present

#1805 Fix jest timeouts for jupyterlab
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
Labels: internal, cla-present

#1806 Fix export-to-html
  tools/perspective-build/worker.js
Labels: bug, cla-present

#1809 try to unify the prebuilt extension with the existing extension
  .gitignore
  azure-pipelines.yml
  binder/postBuild
  docs/md/development.md
  docs/md/python.md
  package.json
  packages/perspective-jupyter/README.md
  packages/perspective-jupyter/build.js
  packages/perspective-jupyter/package.json
  packages/perspective-jupyter/src/config/webpack.config.js
  packages/perspective-jupyter/src/js/notebook/extension.js
  packages/perspective-jupyter/src/js/notebook/index.js
  packages/perspective-jupyter/src/js/plugin/client.js
  packages/perspective-jupyter/src/js/plugin/index.js
  packages/perspective-jupyter/src/js/plugin/model.js
  packages/perspective-jupyter/src/js/plugin/plugin.js
  packages/perspective-jupyter/src/js/plugin/psp_widget.js
  packages/perspective-jupyter/src/js/plugin/renderer.js
  packages/perspective-jupyter/src/js/plugin/utils.js
  packages/perspective-jupyter/src/js/plugin/version.js
  packages/perspective-jupyter/src/js/plugin/view.js
  packages/perspective-jupyter/src/js/plugin/widget.js
  packages/perspective-jupyter/src/less/index.less
  packages/perspective-jupyter/test/arrow/test.arrow
  packages/perspective-jupyter/test/config/jest.config.js
  packages/perspective-jupyter/test/config/jupyter/globalSetup.js
  packages/perspective-jupyter/test/config/jupyter/jest.config.js
  packages/perspective-jupyter/test/config/jupyter/jlab_start.js
  packages/perspective-jupyter/test/config/jupyter/jupyter_notebook_config.json
  packages/perspective-jupyter/test/config/jupyter/jupyter_server_config.json
  packages/perspective-jupyter/test/config/jupyter/teardown.js
  packages/perspective-jupyter/test/config/jupyter/user_settings/@jupyterlab/shortcuts-extension/shortcuts.jupyterlab-settings
  packages/perspective-jupyter/test/css/demo.css
  packages/perspective-jupyter/test/html/resize.html
  packages/perspective-jupyter/test/js/resize.spec.js
  packages/perspective-jupyter/test/jupyter/notebook_template.json
  packages/perspective-jupyter/test/jupyter/utils.js
  packages/perspective-jupyter/test/jupyter/widget.spec.js
  packages/perspective-jupyter/test/results/linux.docker.json
  packages/perspective-jupyter/test/results/results.json
  packages/perspective-jupyterlab/src/js/index.js
  packages/perspective-jupyterlab/src/js/version.js
  packages/perspective/src/js/perspective.node.js
  python/perspective/jupyter/babel.config.js
  python/perspective/jupyter/package.json
  python/perspective/jupyter/src/embed.js
  python/perspective/jupyter/src/extension.js
  python/perspective/jupyter/src/nbextension.js
  python/perspective/perspective/widget/widget.py
  python/perspective/scripts/write_version.py
  python/perspective/setup.py
  scripts/jlab_link.js
  scripts/setup.js
  scripts/test_js.js
  tools/perspective-test/jest.all.config.js
  yarn.lock
Labels: cla-present

#1815 remove duplicate steps
  azure-pipelines.yml
Labels: internal, cla-present

#1811 prune 2 more python2 references
  examples/tornado-python/package.json
  examples/tornado-streaming-python/package.json
Labels: cla-present

#1823 Fix jupyterlab test timeouts
  packages/perspective-jupyterlab/test/jupyter/utils.js
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
Labels: internal
