Repository finos/perspective, pull requests merged in 2022-12, with the labels that each got.

#2025 remove reference to gitter from contributing docs
  CONTRIBUTING.md
Labels: internal, cla-present

#2028 Fix Default Plugin Order
  .gitignore
  packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
  rust/perspective-viewer/src/rust/js/plugin.rs
  rust/perspective-viewer/src/rust/renderer/registry.rs
  rust/perspective-viewer/src/ts/plugin.ts
  rust/perspective-viewer/test/html/plugin-priority-order.html
  rust/perspective-viewer/test/js/plugins.spec.js
  rust/perspective-viewer/test/results/results.json
Labels: bug

#2015 Update docusaurus footer with correct link
  docs/docusaurus.config.js
Labels: internal, documentation

#2033 Add labels to Scatter plot points.
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
  packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: enhancement

#2034 Resize labels to avoid overlap
  packages/perspective-viewer-d3fc/src/js/axis/linearAxis.js
Labels: cla-present

#2035 Fix CSS and Scatter Chart positioning bugs
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/series/colorStyles.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/Cargo.toml
Labels: bug, cla-present

#2043 Fix parsing of bug related to d3fc splitting selection data (redux of #2039)
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/js/tooltip/generateHTML.js
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
  packages/perspective-viewer-d3fc/test/js/unit/tooltip/generateHTML.spec.js
  packages/perspective-viewer-d3fc/test/js/unit/tooltip/selectionData.spec.js
  rust/perspective-viewer/Cargo.lock
Labels: bug

#2042 Vec3 functions for ExprTK and new example "Ray Casting"
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/include/perspective/computed_expression.h
  cpp/perspective/src/include/perspective/computed_function.h
  examples/blocks/gists.json
  examples/blocks/src/raycasting/.block
  examples/blocks/src/raycasting/README.md
  examples/blocks/src/raycasting/index.css
  examples/blocks/src/raycasting/index.html
  examples/blocks/src/raycasting/index.js
Labels: enhancement, cla-present

#2044 Update README gallery
  README.md
Labels: documentation, cla-present

#2053 Fix copypasta in code of conduct, fix capitalization in readme
  .github/CODE_OF_CONDUCT.md
  README.md
Labels: documentation, cla-present

#2054 Move examples to `gh-pages` site
  .gitignore
  README.md
  docs/docusaurus.config.js
  docs/package.json
  docs/src/pages/block.js
  docs/src/pages/examples.js
  docs/src/pages/index.js
  examples/blocks/dist.js
  examples/blocks/examples.js
  examples/blocks/gists.json
  examples/blocks/index.js
  examples/blocks/package.json
  examples/blocks/src/citibike/preview.png
  examples/blocks/src/citibike/thumbnail.png
  examples/blocks/src/covid/preview.png
  examples/blocks/src/covid/thumbnail.png
  examples/blocks/src/csv/preview.png
  examples/blocks/src/csv/thumbnail.png
  examples/blocks/src/custom/preview.png
  examples/blocks/src/custom/thumbnail.png
  examples/blocks/src/editable/preview.png
  examples/blocks/src/editable/thumbnail.png
  examples/blocks/src/evictions/preview.png
  examples/blocks/src/evictions/thumbnail.png
  examples/blocks/src/fractal/preview.png
  examples/blocks/src/fractal/thumbnail.png
  examples/blocks/src/iex/preview.png
  examples/blocks/src/iex/thumbnail.png
  examples/blocks/src/movies/preview.png
  examples/blocks/src/movies/thumbnail.png
  examples/blocks/src/olympics/preview.png
  examples/blocks/src/olympics/thumbnail.png
  examples/blocks/src/raycasting/preview.png
  examples/blocks/src/raycasting/thumbnail.png
  examples/blocks/src/streaming/preview.png
  examples/blocks/src/streaming/thumbnail.png
  examples/blocks/src/superstore/preview.png
  examples/blocks/src/superstore/thumbnail.png
  rust/perspective-viewer/README.md
  rust/perspective-viewer/docs.js
  rust/perspective-viewer/exprtk.md
  yarn.lock
Labels: documentation, cla-present

#2065 Add Python 3.10 support, deprecate 3.7
  .github/workflows/build.yml
  cmake/modules/FindPythonHeaders.cmake
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/exception.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/scalar.h
  packages/perspective-jupyterlab/test/jupyter/utils.js
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/src/fill.cpp
  python/perspective/perspective/src/utils.cpp
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/tests/table/test_table_object.py
  python/perspective/perspective/tests/table/test_to_format.py
  python/perspective/setup.py
  scripts/publish_python.js
  scripts/script_utils.js
Labels: bug, cla-present, breaking

#2057 Cleanup examples
  README.md
  docs/docs/development.md
  docs/docusaurus.config.js
  docs/package.json
  docs/src/components/Demo/index.js
  docs/src/components/Demo/layouts.js
  docs/src/components/Demo/styles.module.css
  docs/src/pages/block.js
  docs/src/pages/examples.js
  docs/src/pages/index.js
  examples/blocks/examples.js
  examples/blocks/gists.json
  examples/blocks/index.js
  examples/blocks/package.json
  examples/blocks/server.js
  examples/blocks/src/citibike/README.md
  examples/blocks/src/citibike/layout.json
  examples/blocks/src/citibike/preview.png
  examples/blocks/src/citibike/thumbnail.png
  examples/blocks/src/covid/README.md
  examples/blocks/src/csv/README.md
  examples/blocks/src/custom/.block
  examples/blocks/src/custom/README.md
  examples/blocks/src/custom/custom_plugin.js
  examples/blocks/src/custom/index.html
  examples/blocks/src/custom/preview.png
  examples/blocks/src/custom/thumbnail.png
  examples/blocks/src/dataset/index.html
  examples/blocks/src/editable/README.md
  examples/blocks/src/editable/index.html
  examples/blocks/src/evictions/README.md
  examples/blocks/src/fractal/README.md
  examples/blocks/src/iex/.block
  examples/blocks/src/iex/README.md
  examples/blocks/src/iex/index.css
  examples/blocks/src/iex/index.html
  examples/blocks/src/iex/index.js
  examples/blocks/src/iex/layout.json
  examples/blocks/src/iex/preview.png
  examples/blocks/src/iex/thumbnail.png
  examples/blocks/src/movies/README.md
  examples/blocks/src/movies/layout.json
  examples/blocks/src/olympics/README.md
  examples/blocks/src/raycasting/README.md
  examples/blocks/src/streaming/README.md
  examples/blocks/src/streaming/preview.png
  examples/blocks/src/streaming/streaming.js
  examples/blocks/src/streaming/thumbnail.png
  examples/blocks/src/superstore/README.md
  package.json
  packages/perspective-viewer-datagrid/src/js/event_handlers/row_select_click.js
  rust/perspective-viewer/README.md
  scripts/install_tools.js
Labels: documentation, cla-present

#2067 Improved point label position
  packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
Labels: bug

#2068 Fix CSS compilation to not inline http resources
  packages/perspective-esbuild-plugin/ignore_fonts.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
Labels: internal, cla-present

#2069 Fix CSS compilation for `@finos/perspective-jupyterlab`
  packages/perspective-esbuild-plugin/ignore_fonts.js
  packages/perspective-jupyterlab/build.js
  packages/perspective-jupyterlab/src/less/index.less
  packages/perspective-viewer-datagrid/src/js/event_handlers/row_select_click.js
  packages/perspective-workspace/build.js
  packages/perspective-workspace/src/themes/material-dark.less
  packages/perspective-workspace/src/themes/material.less
  rust/perspective-viewer/build.js
Labels: internal, cla-present

#2070 Fix test regression in chrome
  packages/perspective-workspace/test/results/results.json
Labels: internal, cla-present

#2072 Add macOS arm wheels to build matrix
  .github/workflows/build.yml
  scripts/_wheel_python.js
Labels: enhancement, cla-present

#2071 Actually copy readme this time, fixes incomplete #1991
  scripts/script_utils.js
Labels: internal, cla-present
