Repository finos/perspective, pull requests merged in 2022-07, with the labels that each got.

#1881 Fix small memory leak and validate package.json with CI cache
  .github/workflows/build.yml
  cpp/perspective/src/cpp/sparse_tree.cpp
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/expressions/invariant.js
  packages/perspective/test/js/expressions/numeric.js
  packages/perspective/test/js/pivots.js
Labels: bug, cla-present

#1883 Changed default color label style for charts with multiple secondary axii
  packages/perspective-viewer-d3fc/src/less/chart.less
Labels: cla-present, styling

#1886 Pin `tornado` to 6.1 in CI
  .github/workflows/build.yml
  azure-pipelines.yml
Labels: internal, cla-present

#1854 GHA default (remove azure)
  README.md
  azure-pipelines.yml
  scripts/publish_python.js
  scripts/publish_python_azure.js
Labels: internal, cla-present

#1888 Expand/collapse on entire group cell, rather than just button
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
Labels: bug

#1889 Split foreground and background numeric column color modes
  packages/perspective-viewer-datagrid/src/js/plugin.js
  packages/perspective-viewer-datagrid/src/js/plugin_menu.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  rust/perspective-viewer/src/less/column-style.less
  rust/perspective-viewer/src/rust/components/number_column_style.rs
  rust/perspective-viewer/src/rust/components/tests/column_style.rs
Labels: enhancement, cla-present

#1890 Fix gradient bounds calc
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  rust/perspective-viewer/src/less/column-style.less
Labels: bug

#1887 Fix expand/collapse on first row of ctx2
  README.md
  cpp/perspective/src/cpp/traversal.cpp
  python/perspective/perspective/tests/table/test_view.py
Labels: bug, cla-present

#1891 Fix jlab tests to use local packages
  .github/workflows/build.yml
  python/perspective/perspective/tests/table/test_view.py
Labels: internal, cla-present

#1893 Remove custom docker images
  .gitattributes
  .github/workflows/build.yml
  docker/python/manylinux2010/Dockerfile
  docker/python/manylinux2014/Dockerfile
  docs/md/development.md
  scripts/_wheel_python.js
  scripts/install_tools.js
  scripts/script_utils.js
Labels: internal, cla-present

#1895 Add `pulse` numeric column background mode
  packages/perspective-viewer-datagrid/src/js/cell_flash.js
  packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
  packages/perspective-viewer-datagrid/src/js/sorting.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  rust/perspective-viewer/src/rust/components/number_column_style.rs
Labels: enhancement, cla-present

#1904 Fix webpack plugin compat with emsdk single-link build
  packages/perspective-webpack-plugin/index.js
Labels: bug, cla-present

#1905 Fix python CI builds for all linux variants
  scripts/_wheel_python.js
Labels: internal, cla-present

#1907 Fix Python sdist CI build
  .github/workflows/build.yml
Labels: internal, cla-present

#1908 Add categories to plugin selector
  packages/perspective-viewer-d3fc/src/js/charts/area.js
  packages/perspective-viewer-d3fc/src/js/charts/bar.js
  packages/perspective-viewer-d3fc/src/js/charts/candlestick.js
  packages/perspective-viewer-d3fc/src/js/charts/column.js
  packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/js/charts/ohlc.js
  packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
  packages/perspective-viewer-d3fc/src/js/charts/treemap.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-line.js
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/charts/y-scatter.js
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-datagrid/src/js/plugin.js
  rust/perspective-viewer/src/rust/components/aggregate_selector.rs
  rust/perspective-viewer/src/rust/components/containers/select.rs
  rust/perspective-viewer/src/rust/components/copy_dropdown.rs
  rust/perspective-viewer/src/rust/components/export_dropdown.rs
  rust/perspective-viewer/src/rust/components/plugin_selector.rs
  rust/perspective-viewer/src/rust/js/plugin.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/rust/renderer/plugin_store.rs
  rust/perspective-viewer/src/rust/renderer/registry.rs
  rust/perspective-viewer/test/results/results.json
Labels: enhancement, cla-present

#1914 Add migrate support for datagrid `plugin_config` API
  packages/perspective-viewer-d3fc/src/js/axis/ordinalAxis.js
  packages/perspective/src/js/config/index.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.worker.js
  rust/perspective-viewer/build.js
  rust/perspective-viewer/src/ts/migrate.ts
  rust/perspective-viewer/test/js/migrate_viewer.spec.js
  rust/perspective-viewer/test/results/results.json
Labels: bug, cla-present

#1915 Fix publish issues
  .github/workflows/build.yml
  binder/postBuild
  package.json
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/js/index.js
  packages/perspective-viewer-openlayers/package.json
  scripts/publish_python.js
  yarn.lock
Labels: internal, cla-present

#1918 Publish `@finos/perspective-esbuild-plugin`
  .eslintrc.json
  .gitignore
  docs/docs/js.md
  examples/blocks/src/editable/index.html
  examples/esbuild-example/README.md
  examples/esbuild-example/build.js
  examples/esbuild-example/package.json
  examples/esbuild-example/src/index.css
  examples/esbuild-example/src/index.html
  examples/esbuild-example/src/index.js
  examples/webpack-cross-origin/package.json
  examples/webpack-example/package.json
  package.json
  packages/perspective-esbuild-plugin/README.md
  packages/perspective-esbuild-plugin/build.js
  packages/perspective-esbuild-plugin/empty.js
  packages/perspective-esbuild-plugin/external.js
  packages/perspective-esbuild-plugin/ignore_css.js
  packages/perspective-esbuild-plugin/ignore_fonts.js
  packages/perspective-esbuild-plugin/index.js
  packages/perspective-esbuild-plugin/inline_css.js
  packages/perspective-esbuild-plugin/package.json
  packages/perspective-esbuild-plugin/replace.js
  packages/perspective-esbuild-plugin/resolve.js
  packages/perspective-esbuild-plugin/rust_wasm.js
  packages/perspective-esbuild-plugin/umd.js
  packages/perspective-esbuild-plugin/wasm.js
  packages/perspective-esbuild-plugin/worker.js
  packages/perspective-jupyterlab/build.js
  packages/perspective-jupyterlab/package.json
  packages/perspective-viewer-d3fc/build.js
  packages/perspective-viewer-datagrid/build.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-openlayers/build.js
  packages/perspective-workspace/build.js
  packages/perspective-workspace/package.json
  packages/perspective/build.js
  packages/perspective/package.json
  rust/perspective-viewer/build.js
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/rust/components/font_loader.rs
  rust/perspective-viewer/src/rust/components/modal.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/custom_events.rs
  tools/perspective-build/replace.js
  tools/perspective-build/rust_wasm.js
  yarn.lock
Labels: enhancement, cla-present

#1916 Make `perspective-viewer` crate importable for external wasm projects
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/build.js
  rust/perspective-viewer/docs.js
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/rust/custom_elements/copy_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/export_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/number_column_style.rs
  rust/perspective-viewer/src/rust/custom_elements/string_column_style.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/js/clipboard.rs
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/rust/utils/custom_element.rs
  rust/perspective-viewer/src/rust/utils/mod.rs
  rust/perspective-viewer/src/ts/bootstrap.ts
  rust/perspective-viewer/src/ts/copy_menu.ts
  rust/perspective-viewer/src/ts/export_menu.ts
  rust/perspective-viewer/src/ts/extensions.ts
  rust/perspective-viewer/src/ts/init.ts
  rust/perspective-viewer/src/ts/number-column-style.ts
  rust/perspective-viewer/src/ts/perspective-viewer.ts
  rust/perspective-viewer/src/ts/string-column-style.ts
  rust/perspective-viewer/src/ts/viewer.ts
  scripts/test_js.js
Labels: internal, cla-present

#1919 Fix "inline mode" build
  packages/perspective/src/js/perspective.browser.js
  packages/perspective/src/js/perspective.worker.js
Labels: bug, cla-present

#1920 Add zoom persistence to OpenLayers plugin
  packages/perspective-viewer-openlayers/src/js/plugin/plugin.js
  packages/perspective-viewer-openlayers/src/js/style/categoryShapes.js
  packages/perspective-viewer-openlayers/src/js/views/base-map.js
  packages/perspective-viewer-openlayers/src/js/views/map-view.js
Labels: enhancement, cla-present

#1921 Fix app export
  packages/perspective-esbuild-plugin/index.js
  packages/perspective-esbuild-plugin/worker.js
  packages/perspective-jupyterlab/build.js
  packages/perspective-workspace/build.js
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/build.rs
  rust/perspective-viewer/src/rust/model/copy_export.rs
  rust/perspective-viewer/src/rust/model/export_app.rs
Labels: bug, cla-present

#1917 Cleanup up python requirements installation in CI, remove some dangling azure references, refresh python README
  .artifactignore
  .github/workflows/build.yml
  .gitignore
  docs/docs/python.md
  package.json
  python/perspective/README.md
  python/perspective/perspective/tests/core/test_layout.py
  python/perspective/setup.py
  scripts/_requires_python.js
  scripts/_wheel_python.js
  scripts/build_python.js
  scripts/build_python_azure.js
  scripts/publish_python.js
  scripts/script_utils.js
Labels: internal, cla-present

#1926 Fix Python bug in `async` mode
  python/perspective/perspective/handlers/common.py
  python/perspective/perspective/tests/handlers/test_aiohttp_async_mode.py
  python/perspective/perspective/tests/handlers/test_starlette_async_mode.py
  python/perspective/perspective/tests/handlers/test_tornado_async_mode.py
  python/perspective/setup.py
Labels: bug, cla-present
