Repository finos/perspective, pull requests merged in 2022-06, with the labels that each got.

#1837 Fix scrolling in Chrome 102
  rust/perspective-viewer/src/themes/material-dark.less
  rust/perspective-viewer/src/themes/material.less
  rust/perspective-viewer/src/themes/solarized-dark.less
Labels: bug, cla-present

#1829 fix bug in setup.js where extra set of quotes prevents initial build
  scripts/setup.js
Labels: internal, cla-present

#1838 Fix `exports` field for Node.js 16 compatibility
  cpp/perspective/CMakeLists.txt
  package.json
  packages/perspective-cli/package.json
  packages/perspective-jupyterlab/src/js/client.js
  packages/perspective-viewer-d3fc/test/js/integration/area.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/barWidth.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/events.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/heatmap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/treemap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/xy-line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/yscatter.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective/package.json
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/perspective.worker.js
  python/perspective/docs/img/grid1.png
  python/perspective/docs/img/pandas1.png
  python/perspective/docs/img/pandas2.png
  python/perspective/docs/img/scatter.png
  python/perspective/docs/img/scatter1.png
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/rust/renderer.rs
  tools/perspective-test/src/js/index.js
  yarn.lock
Labels: internal, cla-present, breaking

#1845 ExprTK/Perspective Documentation
  docs/sidebars.json
  rust/perspective-viewer/README.md
  rust/perspective-viewer/docs.js
  rust/perspective-viewer/exprtk.md
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/rust/exprtk/language.rs
  rust/perspective-viewer/src/rust/exprtk/mod.rs
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/ts/viewer.ts
Labels: documentation

#1841 Include column name in error log for arrow filling
  cpp/perspective/src/cpp/arrow_loader.cpp
Labels: internal, cla-present

#1846 Make `PerspectiveViewerElement` rust type usable from non-wasm-abi
  rust/perspective-viewer/src/rust/components/filter_item.rs
  rust/perspective-viewer/src/rust/components/font_loader.rs
  rust/perspective-viewer/src/rust/components/plugin_selector.rs
  rust/perspective-viewer/src/rust/components/render_warning.rs
  rust/perspective-viewer/src/rust/components/status_bar.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/config/viewer_config.rs
  rust/perspective-viewer/src/rust/custom_elements/filter_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/custom_events.rs
  rust/perspective-viewer/src/rust/js/plugin.rs
  rust/perspective-viewer/src/rust/js/testing.rs
  rust/perspective-viewer/src/rust/model/structural.rs
  rust/perspective-viewer/src/rust/model/update_and_render.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/rust/renderer/activate.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/view.rs
  rust/perspective-viewer/src/rust/session/view_subscription.rs
  rust/perspective-viewer/src/rust/theme.rs
  rust/perspective-viewer/src/rust/utils/api_future.rs
  rust/perspective-viewer/src/rust/utils/debounce.rs
  rust/perspective-viewer/src/rust/utils/future_to_promise.rs
  rust/perspective-viewer/src/rust/utils/mod.rs
  rust/perspective-viewer/src/rust/utils/tests/debounce.rs
  rust/perspective-viewer/src/ts/viewer.ts
Labels: internal, cla-present

#1847 Fix `@finos/perspective-viewer-d3fc` chart-specific exports
  packages/perspective-viewer-d3fc/package.json
Labels: cla-present

#1850 Reimplement `editable` for PerspectiveWidget in JupyterLab to take into account the latest changes
  packages/perspective-jupyterlab/src/js/model.js
  packages/perspective-jupyterlab/src/js/psp_widget.js
  packages/perspective-jupyterlab/src/js/renderer.js
  packages/perspective-jupyterlab/src/js/view.js
  packages/perspective-jupyterlab/src/js/widget.js
  packages/perspective-jupyterlab/test/js/resize.spec.js
  packages/perspective-jupyterlab/test/jupyter/utils.js
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
  packages/perspective-jupyterlab/test/results/results.json
  packages/perspective-viewer-datagrid/src/js/editing.js
  packages/perspective-viewer-datagrid/src/js/plugin.js
  python/perspective/perspective/tests/viewer/test_viewer.py
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/viewer/viewer_traitlets.py
  python/perspective/perspective/widget/widget.py
  tools/perspective-test/src/js/index.js
Labels: bug, JS, Python, cla-present

#1855 Simplify and uplift binder to latest supported python, perspective wheel, and dependency set
  binder/apt.txt
  binder/postBuild
  binder/requirements.txt
  binder/runtime.txt
Labels: documentation, cla-present

#1859 Remove unused watch commands from viewer-d3fc and viewer-datagrid, remove dependabot, dont trigger full build on merge to master
  .github/dependabot.yml
  .github/workflows/build.yml
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-datagrid/package.json
Labels: internal, cla-present

#1852 Fix `set_threadpool_size(n)` for `n == 1`
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/expression_tables.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/expression_tables.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/parallel_for.h
  python/perspective/docs/perspective.core.rst
  python/perspective/perspective/libpsp.py
  python/perspective/perspective/tests/single_threaded/test_single_threaded.py
  scripts/test_python.js
Labels: bug, cla-present

#1867 Remove Python 3.6 support
  .github/workflows/build.yml
  azure-pipelines.yml
  python/perspective/setup.py
  scripts/build_python_azure.js
  scripts/publish_python.js
  scripts/publish_python_azure.js
  scripts/script_utils.js
Labels: cla-present, deprecation

#1866 Update `emsdk` to `3.1.14`
  .github/workflows/build.yml
  cmake/arrow/CMakeLists.txt
  cpp/perspective/CMakeLists.txt
  cpp/perspective/build.js
  cpp/perspective/src/cpp/emscripten.cpp
  package.json
  packages/perspective/build.js
  packages/perspective/src/js/perspective.js
  packages/perspective/src/js/perspective.node.js
  rust/perspective-viewer/build.js
  rust/perspective-viewer/src/rust/components/containers/select.rs
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/modal.rs
  rust/perspective-viewer/src/rust/components/number_column_style.rs
  rust/perspective-viewer/src/rust/components/string_column_style.rs
  rust/perspective-viewer/src/rust/config/filters.rs
  rust/perspective-viewer/src/rust/config/sort.rs
  rust/perspective-viewer/src/rust/dragdrop.rs
  rust/perspective-viewer/src/rust/js/mimetype.rs
  rust/perspective-viewer/src/rust/js/plugin.rs
  rust/perspective-viewer/src/rust/model/columns_iter_set.rs
  rust/perspective-viewer/src/rust/model/export_method.rs
  rust/perspective-viewer/src/rust/session/view_subscription.rs
  tools/perspective-bench/package.json
  tools/perspective-bench/src/js/bench.js
  tools/perspective-build/empty.js
  tools/perspective-build/rust_wasm.js
  tools/perspective-build/worker.js
Labels: internal
