Repository finos/perspective, pull requests merged in 2023-06, with the labels that each got.

#2241 Pyodide wheel
  .github/workflows/build.yml
  .gitignore
  cmake/modules/FindNumPy.cmake
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/column.cpp
  cpp/perspective/src/cpp/compat_impl_linux.cpp
  cpp/perspective/src/cpp/compat_impl_osx.cpp
  cpp/perspective/src/cpp/compat_impl_wasm.cpp
  cpp/perspective/src/cpp/compat_impl_win.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/none.cpp
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/raii.cpp
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/cpp/utils.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/column.h
  cpp/perspective/src/include/perspective/computed_function.h
  cpp/perspective/src/include/perspective/emscripten.h
  cpp/perspective/src/include/perspective/filter.h
  cpp/perspective/src/include/perspective/first.h
  cpp/perspective/src/include/perspective/mask.h
  cpp/perspective/src/include/perspective/none.h
  cpp/perspective/src/include/perspective/pool.h
  cpp/perspective/src/include/perspective/pyutils.h
  cpp/perspective/src/include/perspective/raii.h
  package.json
  packages/perspective/src/js/api/server.js
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/libpsp.py
  python/perspective/perspective/src/column.cpp
  python/perspective/perspective/table/__init__.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/_state.py
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/client_mode/test_client_mode.py
  python/perspective/perspective/tests/single_threaded/test_single_threaded.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/widget/widget.py
  scripts/build_python.js
  scripts/script_utils.js
Labels: enhancement, cla-present

#2243 Fix CSS positioning of expression panel in workspace
  packages/perspective-workspace/src/themes/pro-dark.less
  packages/perspective-workspace/src/themes/pro.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/less/viewer.less
Labels: bug, cla-present

#2244 Allow `pandas~=2.0.0` to be installed
  python/perspective/perspective/tests/table/test_table_pandas.py
  python/perspective/setup.py
Labels: cla-present

#2256 Validate installed emsdk version
  scripts/install_emsdk.js
  scripts/run_emsdk.js
Labels: cla-present

#2257 Fix workspace `save()` w/settings
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/dockpanel.less
  packages/perspective-workspace/test/js/restore.spec.js
  rust/perspective-viewer/Cargo.lock
  tools/perspective-test/src/js/global_startup.ts
  tools/perspective-test/src/js/global_teardown.ts
Labels: bug, cla-present

#2261 Thread-safe python readers
  .github/workflows/build.yml
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/arrow_loader.cpp
  cpp/perspective/src/cpp/arrow_writer.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/pyutils.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/arrow_writer.h
  cpp/perspective/src/include/perspective/first.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/pool.h
  cpp/perspective/src/include/perspective/pyutils.h
  cpp/perspective/src/include/perspective/view.h
  docs/docs/python.md
  examples/python-tornado-streaming/index.html
  examples/python-tornado-streaming/server.py
  examples/python-tornado/client_server_editing.html
  examples/python-tornado/index.html
  examples/python-tornado/server.py
  examples/python-tornado/server_mode.html
  python/perspective/bench/runtime/bench.py
  python/perspective/bench/runtime/perspective_benchmark.py
  python/perspective/bench/runtime/run_perspective_benchmark.py
  python/perspective/bench/tornado/async_server.py
  python/perspective/perspective/client/__init__.py
  python/perspective/perspective/client/base.py
  python/perspective/perspective/client/websocket.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/src/serialization.cpp
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_callback_cache.py
  python/perspective/perspective/tests/core/test_async.py
  python/perspective/perspective/tests/manager/test_manager.py
  scripts/_wheel_python.js
  scripts/install_tools.js
  scripts/publish.js
Labels: enhancement, Python, cla-present, breaking

#2262 Write custom parser for us locale time string format
  cpp/perspective/src/cpp/arrow_csv.cpp
  packages/perspective/test/js/constructors.spec.js
Labels: cla-present

#2267 Add API to give number of views into table
  packages/perspective/index.d.ts
  packages/perspective/src/js/api/table_api.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/updates.spec.js
  python/perspective/perspective/client/table_api.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/table/test_table.py
  rust/perspective-viewer/src/rust/lib.rs
Labels: cla-present

#2280 Fix bad CSS headers and update formatted CSS test snapshots
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/components/Demo/styles.module.css
  docs/src/components/DocItem/styles.module.css
  docs/src/components/ExampleGallery/styles.module.css
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/css/regular_table_reset.css
  docs/src/pages/index.module.css
  examples/blocks/index.mjs
  examples/blocks/src/citibike/index.css
  examples/blocks/src/csv/index.css
  examples/blocks/src/fractal/index.css
  examples/blocks/src/market/index.css
  examples/blocks/src/raycasting/index.css
  examples/blocks/src/streaming/index.css
  examples/esbuild-example/src/index.css
  examples/esbuild-remote/client/index.css
  examples/git-history/index.css
  examples/react-example/src/index.css
  examples/webpack-cross-origin/src/index.css
  examples/webpack-example/src/index.css
  python/perspective/docs/conf.py
  rust/perspective-viewer/test/css/demo.css
  tools/perspective-scripts/lint_headers.mjs
  tools/perspective-scripts/test_js.mjs
  tools/perspective-test/results.tar.gz
Labels: internal, cla-present

#2282 Fix bug preventing blocks example server from starting.
  examples/blocks/package.json
  examples/blocks/server.mjs
Labels: cla-present

#2281 Add `get_hosted_table_names` to js and python server apis.
  packages/perspective/src/js/api/client.js
  packages/perspective/src/js/api/server.js
  packages/perspective/test/js/hosted_tables.spec.js
  packages/perspective/test/js/remote.spec.js
  python/perspective/perspective/client/base.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/tests/manager/test_manager.py
  tools/perspective-test/results.tar.gz
Labels: cla-present

#2283 Fix python segfault in multi-threaded execution
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/include/perspective/pyutils.h
  python/perspective/perspective/client/websocket.py
  python/perspective/perspective/handlers/common.py
  python/perspective/perspective/handlers/tornado.py
  python/perspective/perspective/include/perspective/python.h
  python/perspective/perspective/include/perspective/python/table.h
  python/perspective/perspective/src/table.cpp
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/tests/handlers/test_tornado_thread_pool_executor.py
Labels: bug, cla-present
