Repository finos/perspective, pull requests merged in 2023-05, with the labels that each got.

#2214 Update `perspective-workspace` design
  .prettierrc.json
  examples/blocks/src/evictions/layout.json
  examples/blocks/src/fractal/index.css
  examples/blocks/src/movies/index.html
  examples/blocks/src/superstore/index.html
  examples/blocks/src/superstore/layout.json
  packages/perspective-jupyterlab/package.json
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-workspace/build.js
  packages/perspective-workspace/package.json
  packages/perspective-workspace/src/js/workspace/commands.js
  packages/perspective-workspace/src/js/workspace/dockpanel.js
  packages/perspective-workspace/src/js/workspace/menu.js
  packages/perspective-workspace/src/js/workspace/tabbar.js
  packages/perspective-workspace/src/js/workspace/tabbarrenderer.js
  packages/perspective-workspace/src/js/workspace/utils.js
  packages/perspective-workspace/src/js/workspace/widget.js
  packages/perspective-workspace/src/js/workspace/workspace.js
  packages/perspective-workspace/src/less/dockpanel.less
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/less/widget.less
  packages/perspective-workspace/src/themes/pro-dark.less
  packages/perspective-workspace/src/themes/pro.less
  packages/perspective-workspace/test/js/migrate_workspace.spec.js
  packages/perspective-workspace/test/js/visibility.spec.js
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/column_selector/filter_column.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/presentation.rs
  rust/perspective-viewer/src/rust/utils/datetime.rs
  rust/perspective-viewer/src/svg/bookmark-icon.svg
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/src/ts/migrate.ts
  rust/perspective-viewer/test/html/blank.html
  rust/perspective-viewer/test/html/column-selector-modes.html
  rust/perspective-viewer/test/html/filters.html
  rust/perspective-viewer/test/html/plugin-priority-order.html
  rust/perspective-viewer/test/html/superstore-all.html
  rust/perspective-viewer/test/html/superstore.html
  tools/perspective-test/results.tar.gz
  tools/perspective-test/src/html/basic-test.html
  tools/perspective-test/src/html/themed-test.html
  tools/perspective-test/src/html/workspace-test.html
  yarn.lock
Labels: enhancement, cla-present

#2216 Fix `sum` aggregate for `integer` type expression columns
  cpp/perspective/src/cpp/sparse_tree.cpp
  packages/perspective/test/js/expressions/numeric.spec.js
Labels: cla-present

#2217 Fix windows python builds
  cpp/perspective/src/include/perspective/step_delta.h
  scripts/_wheel_python.js
Labels: bug, cla-present

#2218 Workspace bug fixes
  cpp/perspective/src/cpp/sparse_tree.cpp
  packages/perspective-viewer-d3fc/src/js/charts/line.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-datagrid/src/less/column-plugin.less
  packages/perspective-viewer-datagrid/src/less/mitered-headers.less
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/toolbar.less
  packages/perspective-workspace/src/js/workspace/commands.js
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/themes/pro-dark.less
  packages/perspective-workspace/src/themes/pro.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/themes/monokai.less
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/src/themes/solarized-dark.less
  rust/perspective-viewer/src/themes/solarized.less
  rust/perspective-viewer/src/themes/vaporwave.less
  tools/perspective-test/results.tar.gz
Labels: bug, cla-present

#2222 Public `perspective-viewer` components
  .gitignore
  docs/static/img/jupyterlab.png
  docs/static/img/mtg_preview.png
  docs/static/img/mtg_thumbnail.png
  packages/perspective-webpack-plugin/package.json
  rust/perspective-viewer/src/less/containers/split-panel.less
  rust/perspective-viewer/src/rust/components/column_dropdown.rs
  rust/perspective-viewer/src/rust/components/column_selector/empty_column.rs
  rust/perspective-viewer/src/rust/components/form/code_editor.rs
  rust/perspective-viewer/src/rust/components/mod.rs
  rust/perspective-viewer/src/rust/components/plugin_selector.rs
  rust/perspective-viewer/src/rust/components/style/style_cache.rs
  rust/perspective-viewer/src/rust/components/style/style_provider.rs
  rust/perspective-viewer/src/rust/custom_elements/column_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/copy_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/modal.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/lib.rs
  tools/perspective-test/results.tar.gz
Labels: internal, cla-present

#2223 Add 3.7 wheel
  .github/workflows/build.yml
  python/perspective/setup.py
  scripts/publish.js
Labels: internal, Python, cla-present

#2236 Fix a bug when calling `load()` with a rejected promise
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/test/js/settings.spec.js
Labels: bug, cla-present

#2224 Fix median miscalculation for even-sized item list
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/include/perspective/sparse_tree.h
  packages/perspective/test/js/expressions/functionality.spec.js
  python/perspective/perspective/tests/core/test_aggregates.py
Labels: bug, cla-present

#2230 Add skip test: _update_with_missing_or_null_values
  python/perspective/perspective/tests/table/test_update.py
Labels: internal, cla-present

#2238 Disallow non-1 multiplicity for bucketing weeks and days
  cpp/perspective/src/cpp/computed_function.cpp
  packages/perspective/test/js/expressions/datetime.spec.js
  tools/perspective-test/results.tar.gz
Labels: bug, cla-present

#2234 Add Python 3.11 support
  .github/workflows/build.yml
  cmake/Pybind.txt.in
  scripts/publish.js
Labels: internal, cla-present

#2240 Developer QoL fixes
  cpp/perspective/CMakeLists.txt
  packages/perspective/src/js/perspective.node.js
  rust/perspective-viewer/src/rust/components/containers/dragdrop_list.rs
  tools/perspective-bench/package.json
  tools/perspective-bench/src/js/bench.js
  tools/perspective-bench/src/js/worker.js
  tools/perspective-test/src/js/global_teardown.ts
Labels: internal, cla-present
