Repository finos/perspective, pull requests merged in 2023-10, with the labels that each got.

#2371 fix some viewer bugs
  packages/perspective-viewer-datagrid/src/js/plugin/activate.js
  rust/perspective-viewer/src/less/containers/split-panel.less
  rust/perspective-viewer/src/less/viewer.less
Labels: cla-present

#2380 Fix tests
  examples/blocks/server.mjs
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/test/js/column_settings/datagrid.spec.ts
  rust/perspective-viewer/test/js/migrate_viewer.spec.js
  tools/perspective-test/playwright.config.ts
  tools/perspective-test/results.tar.gz
Labels: internal, cla-present

#2383 Datagrid rows restyle
  examples/blocks/src/file/index.html
  packages/perspective-viewer-datagrid/build.js
  packages/perspective-viewer-datagrid/src/less/pro.less
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/row-hover.less
  packages/perspective-viewer-datagrid/src/less/scrollbar.less
  packages/perspective-viewer-datagrid/src/less/sub-cell-scroll.less
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/src/themes/monokai.less
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/solarized.less
  rust/perspective-viewer/src/themes/vaporwave.less
  tools/perspective-scripts/publish.mjs
Labels: enhancement, cla-present

#2384 fix gradient values
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab.rs
  rust/perspective-viewer/src/rust/components/number_column_style.rs
  rust/perspective-viewer/src/rust/js/perspective.rs
Labels: bug, cla-present

#2374 Add `index()`, `col()`, and `vlookup()` to ExprTk
  cpp/perspective/src/cpp/computed_expression.cpp
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/emscripten.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/computed_expression.h
  cpp/perspective/src/include/perspective/computed_function.h
  cpp/perspective/src/include/perspective/context_common_decls.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/raw_types.h
  packages/perspective/test/js/expressions/functionality.spec.js
  python/perspective/perspective/src/view.cpp
  python/perspective/perspective/table/_utils.py
  rust/perspective-viewer/src/rust/exprtk/language.rs
Labels: enhancement, cla-present

#2385 Column selector style updates
  packages/perspective-viewer-datagrid/src/js/data_listener/formatter_cache.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/column_header.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/less/column-settings-panel.less
  rust/perspective-viewer/src/less/column-style.less
  rust/perspective-viewer/src/less/dom/checkbox.less
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector/active_column.rs
  rust/perspective-viewer/src/rust/components/column_selector/expression_toolbar.rs
  rust/perspective-viewer/src/rust/components/column_selector/inactive_column.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab.rs
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/model/columns_iter_set.rs
  rust/perspective-viewer/src/themes/variables.less
  tools/perspective-test/results.tar.gz
Labels: bug, cla-present

#2393 New themes `Gruvbox` and `Dracula` + UI performance improvements
  .gitignore
  examples/blocks/src/magic/index.css
  examples/blocks/src/magic/index.html
  examples/blocks/src/market/layouts.json
  examples/blocks/src/raycasting/index.html
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/less/pro.less
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/row-hover.less
  packages/perspective-workspace/src/less/tabbar.less
  packages/perspective-workspace/src/themes/pro.less
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/build.rs
  rust/perspective-viewer/rust-toolchain.toml
  rust/perspective-viewer/src/less/column-selector.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector/add_expression_button.rs
  rust/perspective-viewer/src/rust/components/column_selector/expression_toolbar.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/attributes_tab.rs
  rust/perspective-viewer/src/rust/components/containers/scroll_panel.rs
  rust/perspective-viewer/src/rust/components/containers/sidebar.rs
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/expression_panel_sidebar.rs
  rust/perspective-viewer/src/rust/components/form/code_editor.rs
  rust/perspective-viewer/src/rust/components/form/highlight.rs
  rust/perspective-viewer/src/rust/components/modal.rs
  rust/perspective-viewer/src/rust/components/number_column_style.rs
  rust/perspective-viewer/src/rust/components/tests/column_style.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/exprtk/tokenize.rs
  rust/perspective-viewer/src/themes/dracula.less
  rust/perspective-viewer/src/themes/gruvbox-dark.less
  rust/perspective-viewer/src/themes/gruvbox.less
  rust/perspective-viewer/src/themes/monokai.less
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/src/themes/solarized-dark.less
  rust/perspective-viewer/src/themes/solarized.less
  rust/perspective-viewer/src/themes/themes.less
  rust/perspective-viewer/src/themes/vaporwave.less
  tools/perspective-test/playwright.config.ts
  tools/perspective-test/results.tar.gz
  yarn.lock
Labels: enhancement, cla-present

#2403 Fix `in` and `not in` filter UI bug
  rust/perspective-viewer/src/rust/components/column_selector/config_selector.rs
  rust/perspective-viewer/test/js/regressions.spec.js
  tools/perspective-test/results.tar.gz
Labels: bug, Python, cla-present

#2404 Fix scroll panel height calculation bug
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol.rs
  rust/perspective-viewer/src/rust/components/containers/mod.rs
  rust/perspective-viewer/src/rust/components/containers/scroll_panel.rs
  rust/perspective-viewer/src/rust/components/containers/scroll_panel_item.rs
  rust/perspective-viewer/src/rust/model/export_method.rs
  rust/perspective-viewer/tasks/bundle/Cargo.toml
  tools/perspective-test/results.tar.gz
Labels: bug, cla-present
