Repository finos/perspective, pull requests merged in 2023-04, with the labels that each got.

#2161 A11y front page labels
  docs/src/components/Demo/index.js
  docs/src/components/ExampleGallery/features.js
  docs/src/components/ExampleGallery/index.js
Labels: documentation

#2156 Auto-complete text field column selectors
  rust/perspective-viewer/src/less/column-dropdown.less
  rust/perspective-viewer/src/less/config-selector.less
  rust/perspective-viewer/src/less/empty-column.less
  rust/perspective-viewer/src/less/filter-item.less
  rust/perspective-viewer/src/less/render-warning.less
  rust/perspective-viewer/src/rust/components/column_dropdown.rs
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector/active_column.rs
  rust/perspective-viewer/src/rust/components/column_selector/config_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector/empty_column.rs
  rust/perspective-viewer/src/rust/components/column_selector/filter_column.rs
  rust/perspective-viewer/src/rust/components/column_selector/pivot_column.rs
  rust/perspective-viewer/src/rust/components/column_selector/sort_column.rs
  rust/perspective-viewer/src/rust/components/containers/dragdrop_list.rs
  rust/perspective-viewer/src/rust/components/mod.rs
  rust/perspective-viewer/src/rust/components/modal.rs
  rust/perspective-viewer/src/rust/custom_elements/column_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/filter_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/function_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/mod.rs
  rust/perspective-viewer/src/rust/custom_elements/modal.rs
  rust/perspective-viewer/src/themes/monokai.less
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/src/themes/solarized-dark.less
  rust/perspective-viewer/src/themes/solarized.less
  rust/perspective-viewer/src/themes/vaporwave.less
  rust/perspective-viewer/test/results/results.json
  yarn.lock
Labels: enhancement, cla-present

#2157 gracefully handle websocket errors on python side, fixes #2132
  examples/python-tornado-streaming/index.html
  examples/python-tornado/client_server_editing.html
  examples/python-tornado/index.html
  examples/python-tornado/server_mode.html
  python/perspective/perspective/handlers/aiohttp.py
  python/perspective/perspective/handlers/starlette.py
  python/perspective/perspective/handlers/tornado.py
Labels: bug, cla-present

#2163 Run yarn cache path commands in bash shell
  .github/workflows/build.yml
Labels: internal, cla-present

#2166 link for dark mode logo in readme
  README.md
Labels: documentation, cla-present

#2176 Reorder examples on `README.md`
  README.md
  docs/src/pages/block.js
  examples/blocks/examples.js
  examples/blocks/index.js
  examples/blocks/src/evictions/layout.json
  examples/blocks/src/market/layouts.json
  examples/blocks/src/market/market.js
Labels: documentation, cla-present

#2178 Fix expression editor bug with escaped characters in strings
  rust/perspective-viewer/src/rust/exprtk/tokenize.rs
  rust/perspective-viewer/src/rust/exprtk/tokenize/string.rs
Labels: bug, cla-present

#2179 Better logging and build for rust/wasm
  packages/perspective-esbuild-plugin/index.js
  packages/perspective-esbuild-plugin/replace.js
  packages/perspective-esbuild-plugin/rust_wasm.js
  packages/perspective-jupyterlab/build.js
  packages/perspective/src/js/perspective.browser.js
  rust/perspective-viewer/.cargo/config.toml
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/build.js
  rust/perspective-viewer/rust-toolchain.toml
  rust/perspective-viewer/src/rust/components/containers/split_panel.rs
  rust/perspective-viewer/src/rust/components/datetime_column_style.rs
  rust/perspective-viewer/src/rust/components/font_loader.rs
  rust/perspective-viewer/src/rust/components/style/style_cache.rs
  rust/perspective-viewer/src/rust/config/viewer_config.rs
  rust/perspective-viewer/src/rust/custom_elements/modal.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/js/clipboard.rs
  rust/perspective-viewer/src/rust/js/perspective.rs
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/rust/model/update_and_render.rs
  rust/perspective-viewer/src/rust/presentation.rs
  rust/perspective-viewer/src/rust/renderer/registry.rs
  rust/perspective-viewer/src/rust/utils/browser/download.rs
  rust/perspective-viewer/src/rust/utils/browser/focus.rs
  rust/perspective-viewer/src/rust/utils/browser/mod.rs
  rust/perspective-viewer/src/rust/utils/browser/request_animation_frame.rs
  rust/perspective-viewer/src/rust/utils/browser/selection.rs
  rust/perspective-viewer/src/rust/utils/console_logger.rs
  rust/perspective-viewer/src/rust/utils/debounce.rs
  rust/perspective-viewer/src/rust/utils/mod.rs
  rust/perspective-viewer/tasks/bundle/Cargo.toml
  rust/perspective-viewer/tasks/bundle/main.rs
Labels: internal, cla-present

#2187 pass through websocket connection arguments in python websocket clients, normalize max message size and ensure set for aiohttp
  python/perspective/perspective/client/aiohttp.py
  python/perspective/perspective/client/tornado.py
  python/perspective/perspective/client/websocket.py
Labels: bug, Python, cla-present

#2191 Handle zero values in line plots
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
Labels: cla-present

#2189 Coerce to float64 when user tries to pass in float32 as float64 - fixes #1717
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/tests/table/test_table.py
  python/perspective/perspective/tests/table/test_table_numpy.py
Labels: bug, cla-present

#2209 rename context menu names for perspective renderers in jupyterlab
  packages/perspective-jupyterlab/src/js/renderer.js
Labels: internal, JS, Jupyter, cla-present

#2210 Add scalar factors to Exprtk `bucket()`
  cpp/perspective/src/cpp/computed_function.cpp
  cpp/perspective/src/include/perspective/computed_function.h
  packages/perspective/test/js/expressions/common.js
  packages/perspective/test/js/expressions/datetime.spec.js
Labels: enhancement, cla-present
