Repository finos/perspective, pull requests merged in 2023-11, with the labels that each got.

#2319 Add support for StringDtype (fixes #1237)
  python/perspective/perspective/core/data/pd.py
  python/perspective/perspective/tests/table/test_table_pandas.py
Labels: Python, cla-present

#2399 Expressions API Updates
  packages/perspective/index.d.ts
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/expressions/functionality.spec.js
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/tests/table/test_view_expression.py
  rust/perspective-viewer/src/less/column-settings-panel.less
  rust/perspective-viewer/src/less/containers/tabs.less
  rust/perspective-viewer/src/rust/components/column_dropdown.rs
  rust/perspective-viewer/src/rust/components/column_selector/active_column.rs
  rust/perspective-viewer/src/rust/components/column_selector/config_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector/empty_column.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/attributes_tab.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/attributes_tab/expression_editor.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/sidebar.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/config/expression.rs
  rust/perspective-viewer/src/rust/config/mod.rs
  rust/perspective-viewer/src/rust/config/view_config.rs
  rust/perspective-viewer/src/rust/custom_elements/column_dropdown.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/metadata.rs
  rust/perspective-viewer/src/rust/session/replace_expression_update.rs
  rust/perspective-viewer/test/js/column_settings.spec.ts
  tools/perspective-test/results.tar.gz
  tools/perspective-test/src/js/models/column_settings.ts
  tools/perspective-test/src/js/models/settings_panel.ts
Labels: cla-present

#2402 Upgrade `pyodide` compatibility to v0.24.1
  .github/workflows/build.yml
  .gitignore
  cmake/modules/FindInstallDependency.cmake
  package.json
  vendor/pyodide/Emscripten.cmake
Labels: cla-present, dependencies

#2431 Fix expression alias UX/API
  packages/perspective-viewer-d3fc/test/js/barWidth.spec.ts
  packages/perspective-workspace/test/js/migrate_workspace.spec.js
  packages/perspective/src/js/perspective.js
  packages/perspective/test/js/expressions/functionality.spec.js
  rust/perspective-viewer/src/less/column-settings-panel.less
  rust/perspective-viewer/src/less/expression-editor.less
  rust/perspective-viewer/src/rust/components/column_selector/active_column.rs
  rust/perspective-viewer/src/rust/components/column_selector/config_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector/empty_column.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/attributes_tab/expression_editor.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/components/form/code_editor.rs
  rust/perspective-viewer/src/rust/config/expression.rs
  rust/perspective-viewer/src/rust/config/expressions.rs
  rust/perspective-viewer/src/rust/config/mod.rs
  rust/perspective-viewer/src/rust/config/view_config.rs
  rust/perspective-viewer/src/rust/custom_elements/column_dropdown.rs
  rust/perspective-viewer/src/rust/js/perspective.rs
  rust/perspective-viewer/src/rust/js/tests/perspective.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/replace_expression_update.rs
  rust/perspective-viewer/src/rust/utils/console_logger.rs
  rust/perspective-viewer/src/ts/migrate.ts
  rust/perspective-viewer/test/js/events.spec.ts
  rust/perspective-viewer/test/js/migrate_viewer.spec.js
  rust/perspective-viewer/test/js/plugins.spec.js
  rust/perspective-viewer/test/js/regressions.spec.js
  rust/perspective-viewer/test/js/save_restore.spec.js
Labels: internal

#2418 `PerspectiveWidget` HTML export support in Jupyter
  docs/docs/development.md
  python/perspective/perspective/__init__.py
  python/perspective/perspective/templates/exported_widget.html.jinja
  python/perspective/perspective/widget/__init__.py
  python/perspective/perspective/widget/widget.py
  python/perspective/requirements/requirements-310.txt
  python/perspective/requirements/requirements-311.txt
  python/perspective/requirements/requirements-37.txt
  python/perspective/requirements/requirements-38.txt
  python/perspective/requirements/requirements-39.txt
  python/perspective/setup.py
  tools/perspective-scripts/update_python.mjs
Labels: cla-present

#2421 Column Settings Panel UI Tweaks
  rust/perspective-viewer/src/rust/components/column_selector.rs
  rust/perspective-viewer/src/rust/components/column_selector/active_column.rs
  rust/perspective-viewer/src/rust/components/column_selector/expression_toolbar.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/sidebar.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/column_style.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol.rs
  rust/perspective-viewer/src/rust/components/containers/sidebar.rs
  rust/perspective-viewer/src/rust/components/containers/tablist.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/model/plugin_config.rs
  rust/perspective-viewer/test/js/column_settings.spec.ts
  tools/perspective-test/results.tar.gz
Labels: cla-present

#2429 X/Y Scatter Symbol Serialization as Dictionary
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-datagrid/src/js/event_handlers/edit_click.js
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol/types.rs
  rust/perspective-viewer/src/rust/components/containers/kvpair.rs
Labels: bug, cla-present, breaking

#2436 Serialize Expressions to Objects
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
  rust/perspective-viewer/src/rust/config/expressions.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/replace_expression_update.rs
Labels: cla-present

#2451 Better CSS build
  cpp/perspective/CMakeLists.txt
  cpp/perspective/build.js
  docs/src/components/Demo/styles.module.css
  docs/src/css/regular_table_reset.css
  examples/blocks/index.mjs
  examples/blocks/src/fractal/index.css
  examples/blocks/src/market/index.css
  examples/blocks/src/webcam/index.css
  packages/perspective-jupyterlab/package.json
  packages/perspective-viewer-d3fc/package.json
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-datagrid/src/less/pro.less
  packages/perspective-workspace/build.js
  packages/perspective-workspace/package.json
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/themes/pro-dark.less
  packages/perspective-workspace/src/themes/pro.less
  packages/perspective/src/js/perspective.js
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/build.rs
  rust/perspective-viewer/src/less/column-settings-panel.less
  rust/perspective-viewer/src/less/column-style.less
  rust/perspective-viewer/src/less/containers/dropdown-menu.less
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/themes/dracula.less
  rust/perspective-viewer/src/themes/fonts.less
  rust/perspective-viewer/src/themes/gruvbox-dark.less
  rust/perspective-viewer/src/themes/gruvbox.less
  rust/perspective-viewer/src/themes/icons.less
  rust/perspective-viewer/src/themes/monokai.less
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/src/themes/solarized-dark.less
  rust/perspective-viewer/src/themes/solarized.less
  rust/perspective-viewer/src/themes/vaporwave.less
  rust/perspective-viewer/src/ts/init.ts
  rust/perspective-viewer/test/css/demo.css
  rust/perspective-viewer/test/html/plugin-priority-order.html
  rust/perspective-viewer/test/js/regressions.spec.js
  tools/perspective-test/src/html/basic-test.html
  tools/perspective-test/src/html/superstore-test.html
  tools/perspective-test/src/html/themed-test.html
  tools/perspective-test/src/html/workspace-test.html
  yarn.lock
Labels: bug

#2454 Fix Blocks build script execution
  examples/blocks/index.mjs
  examples/blocks/package.json
  examples/blocks/src/superstore/README.md
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  rust/perspective-viewer/src/rust/custom_elements/copy_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/export_dropdown.rs
  rust/perspective-viewer/src/rust/session.rs
  tools/perspective-scripts/sh.mjs
Labels: cla-present

#2444 Fix 2.7.0 Migration
  rust/perspective-viewer/src/ts/migrate.ts
  rust/perspective-viewer/src/ts/migrate/0-0-0.ts
  rust/perspective-viewer/src/ts/migrate/2-6-1.ts
  rust/perspective-viewer/src/ts/migrate/semver.ts
  rust/perspective-viewer/tsconfig.json
Labels: cla-present

#2452 Fix `perspective-click` event for `"Treemap"` plugin
  packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
  packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
  packages/perspective-workspace/test/js/global_filter.spec.js
  python/perspective/bench/runtime/bench.py
  python/perspective/bench/runtime/run_perspective_benchmark.py
  rust/perspective-viewer/src/less/column-settings-panel.less
  rust/perspective-viewer/src/rust/presentation.rs
  rust/perspective-viewer/src/rust/utils/console_logger.rs
  rust/perspective-viewer/src/themes/dracula.less
  rust/perspective-viewer/src/themes/gruvbox-dark.less
  rust/perspective-viewer/src/themes/gruvbox.less
  rust/perspective-viewer/test/js/leaks.spec.js
  tools/perspective-bench/package.json
  tools/perspective-bench/yarn.lock
  tools/perspective-test/playwright.config.ts
  tools/perspective-test/results.tar.gz
Labels: bug, cla-present
