Repository finos/perspective, pull requests merged in 2023-07, with the labels that each got.

#2285 Fix build regression in python dependency
  .github/workflows/build.yml
Labels: internal, cla-present

#2290 Fix racing tests.
  packages/perspective-cli/test/js/superstore.spec.js
  python/perspective/perspective/table/_state.py
  python/perspective/perspective/tests/handlers/test_tornado_thread_pool_executor.py
Labels: bug, cla-present

#2303 Fix XY-Scatter Plots Colors - Rebased
  packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
  packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
  packages/perspective-viewer-d3fc/src/js/series/seriesColors.js
Labels: bug, cla-present

#2302 Fix empty column name validation in ExprTk editor
  packages/perspective/src/js/perspective.js
Labels: cla-present

#2294 Add GitHub Releases
  .github/workflows/build.yml
  .gitignore
  .vscode/settings.default.json
  package.json
  tools/perspective-scripts/publish.mjs
Labels: internal, cla-present

#2311 Fix expression column aggregate calculation with `group_by` after `remove()`
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/expression_tables.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/include/perspective/context_common_decls.h
  cpp/perspective/src/include/perspective/expression_tables.h
  cpp/perspective/src/include/perspective/gnode.h
  python/perspective/perspective/tests/table/test_remove.py
Labels: bug, cla-present

#2313 Fix build.rs escaping OUT_DIR
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/build.js
  rust/perspective-viewer/build.rs
  rust/perspective-viewer/src/rust/components/column_dropdown.rs
  rust/perspective-viewer/src/rust/components/filter_dropdown.rs
  rust/perspective-viewer/src/rust/components/function_dropdown.rs
  rust/perspective-viewer/src/rust/components/style/mod.rs
Labels: internal, cla-present
