Repository finos/perspective, pull requests merged in 2023-08, with the labels that each got.

#2327 Pin Python dependency versions
  .github/workflows/build.yml
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/requirements-310.txt
  python/perspective/requirements-311.txt
  python/perspective/requirements-37.txt
  python/perspective/requirements-38.txt
  python/perspective/requirements-39.txt
  tools/perspective-scripts/_requires_python.mjs
  tools/perspective-scripts/_wheel_python.mjs
  tools/perspective-scripts/build_python.mjs
  tools/perspective-scripts/sh_perspective.mjs
Labels: internal, cla-present

#2323 Fix over-calculation in when loading data in `perspective-viewer`
  rust/perspective-viewer/src/rust/session.rs
Labels: bug, JS, Python, cla-present

#2328 Fix `update()` with `expressions` overcalc
  cpp/perspective/src/cpp/context_grouped_pkey.cpp
  cpp/perspective/src/cpp/context_one.cpp
  cpp/perspective/src/cpp/context_two.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/expression_tables.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/context_common_decls.h
  cpp/perspective/src/include/perspective/expression_tables.h
  cpp/perspective/src/include/perspective/gnode_state.h
  tools/perspective-bench/src/js/worker.js
Labels: bug, cla-present

#2289 Fix TypeScript 5 `moduleResolution: "bundler"` support
  examples/react-example/tsconfig.json
  examples/react-example/webpack.config.js
  package.json
  packages/perspective-cli/package.json
  packages/perspective/package.json
  rust/perspective-viewer/package.json
  yarn.lock
Labels: bug, cla-present

#2333 prune win 2019 from ci, switch over to windows-2022 only
  .github/workflows/build.yml
Labels: internal, cla-present

#2342 Fix binder installation to not manage dependencies seperately
  binder/apt.txt
  binder/postBuild
  binder/requirements.txt
  binder/runtime.txt
Labels: internal, Jupyter, cla-present

#2351 Datagrid column header configuration UX update
  packages/perspective-viewer-datagrid/build.js
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/js/data_listener/format_cell.js
  packages/perspective-viewer-datagrid/src/js/data_listener/index.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/header_click.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/sort.js
  packages/perspective-viewer-datagrid/src/js/get_cell_config.js
  packages/perspective-viewer-datagrid/src/js/model/create.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/column_header.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/editable.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/group_header.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/table_cell/datetime.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/table_cell/index.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/table_cell/string.js
  packages/perspective-viewer-datagrid/src/js/style_menu.js
  packages/perspective-viewer-datagrid/src/less/column-plugin.less
  packages/perspective-viewer-datagrid/src/less/mitered-headers.less
  packages/perspective-viewer-datagrid/src/less/pro.less
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/presentation.rs
  rust/perspective-viewer/src/rust/session.rs
  tools/perspective-test/results.tar.gz
  yarn.lock
Labels: enhancement, cla-present

#2350 Update webpack dev server configuration options, fixes for perspective 2.0+
  examples/promo/webpack.config.js
  examples/workspace-editing-python/src/index.js
  examples/workspace-editing-python/src/index.less
  examples/workspace-editing-python/webpack.config.js
  examples/workspace/src/index.js
  examples/workspace/src/index.less
  examples/workspace/webpack.config.js
Labels: internal, cla-present

#2352 Fix Jupyter plugin resize behavior
  .prettierignore
  cmake/arrow/CMakeLists.txt
  packages/perspective-jupyterlab/src/less/index.less
  python/perspective/setup.py
Labels: bug, cla-present

#2353 Fix filter number validation with trailing zeroes
  packages/perspective-viewer-datagrid/src/js/data_listener/format_cell.js
  packages/perspective-viewer-datagrid/src/js/data_listener/format_tree_header.js
  packages/perspective-viewer-datagrid/src/js/data_listener/index.js
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  rust/perspective-viewer/src/rust/components/column_selector/filter_column.rs
  rust/perspective-viewer/test/js/regressions.spec.js
  tools/perspective-test/results.tar.gz
Labels: bug, cla-present
