Repository finos/perspective, pull requests merged in 2023-03, with the labels that each got.

#2122 Update docs/branding
  README.md
  docs/build.js
  docs/docusaurus.config.js
  docs/src/components/Demo/index.js
  docs/src/components/Demo/styles.module.css
  docs/src/components/ExampleGallery/index.js
  docs/src/components/HomepageFeatures/description.md
  docs/src/components/HomepageFeatures/feature1.md
  docs/src/components/HomepageFeatures/feature2.md
  docs/src/components/HomepageFeatures/feature3.md
  docs/src/components/HomepageFeatures/index.js
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/css/regular_table_reset.css
  docs/src/pages/block.js
  docs/src/pages/examples.js
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/static/svg/feature1.svg
  docs/static/svg/feature2.svg
  docs/static/svg/feature3.svg
  docs/static/svg/perspective-logo-dark.svg
  docs/static/svg/perspective-logo-light.svg
Labels: cla-present

#2129 Fix readme logo link
  README.md
Labels: internal, cla-present

#2123 Implement `title` field in `PerspectiveWidget`
  packages/perspective-jupyterlab/src/js/view.js
  python/perspective/perspective/viewer/validate.py
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/viewer/viewer_traitlets.py
Labels: internal, cla-present

#2142 Fix autocomplete behavior for `in` and `not in` filter ops
  rust/perspective-viewer/src/less/filter-item.less
  rust/perspective-viewer/src/rust/components/config_selector.rs
  rust/perspective-viewer/src/rust/components/config_selector/filter_item.rs
  rust/perspective-viewer/src/rust/custom_elements/filter_dropdown.rs
  rust/perspective-viewer/test/js/regressions.spec.js
  rust/perspective-viewer/test/results/results.json
Labels: bug, cla-present

#2144 Miscellaneous cleanup from big Jupyter prebuilt overhaul, python 3.7 deprecation, and various other accumulated but unfixed issues
  .gitignore
  cpp/perspective/CMakeLists.txt
  package.json
  packages/perspective-viewer-openlayers/src/js/views/base-map.js
  python/perspective/bench/runtime/bench.py
  python/perspective/bench/runtime/perspective_benchmark.py
  python/perspective/bench/runtime/run_perspective_benchmark.py
  python/perspective/bench/tornado/bench.py
  python/perspective/perspective/client/aiohttp.py
  python/perspective/perspective/client/client.py
  python/perspective/perspective/client/starlette_test.py
  python/perspective/perspective/client/table_api.py
  python/perspective/perspective/client/tornado.py
  python/perspective/perspective/client/view_api.py
  python/perspective/perspective/client/websocket.py
  python/perspective/perspective/core/data/np.py
  python/perspective/perspective/core/data/pd.py
  python/perspective/perspective/handlers/common.py
  python/perspective/perspective/handlers/tornado.py
  python/perspective/perspective/libpsp.py
  python/perspective/perspective/manager/manager.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/manager/session.py
  python/perspective/perspective/nbextension/__init__.py
  python/perspective/perspective/table/_accessor.py
  python/perspective/perspective/table/_callback_cache.py
  python/perspective/perspective/table/_data_formatter.py
  python/perspective/perspective/table/_date_validator.py
  python/perspective/perspective/table/_utils.py
  python/perspective/perspective/table/table.py
  python/perspective/perspective/table/view.py
  python/perspective/perspective/viewer/validate.py
  python/perspective/perspective/viewer/viewer.py
  python/perspective/perspective/widget/widget.py
  python/perspective/pyproject.toml
  python/perspective/setup.cfg
  python/perspective/setup.py
  scripts/repl.js
Labels: internal, cla-present

#2143 Specify that Yarn v1 must be used in development docs.
  docs/docs/development.md
Labels: documentation

#2151 Fix ping loop state, make node server `close` method async
  package.json
  packages/perspective/src/js/perspective.node.js
  packages/perspective/src/js/websocket/client.js
  packages/perspective/test/js/remote.spec.js
  yarn.lock
Labels: bug, cla-present
