Repository finos/perspective, pull requests merged in 2023-02, with the labels that each got.

#2092 Update charting tests to cover more HTML
  packages/perspective-viewer-d3fc/test/js/integration/area.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/barWidth.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/events.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/heatmap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/treemap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/xy-line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/yscatter.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
  packages/perspective/test/js/ports.js
  tools/perspective-test/src/js/html_compare.js
  tools/perspective-test/src/js/index.js
Labels: internal, cla-present

#2101 Update dependencies to be compatible with jupyterlab 3.6.1
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/src/js/view.js
  packages/perspective-jupyterlab/src/js/widget.js
  packages/perspective-workspace/package.json
  packages/perspective-workspace/test/results/results.json
  python/perspective/perspective/widget/widget.py
  python/perspective/setup.py
  yarn.lock
Labels: bug, cla-present

#2103 Update ExprTk package to 0.0.2 tag
  cmake/exprtk.txt.in
  cmake/modules/FindExprTk.cmake
Labels: enhancement

#2107 Fix legend on X/Y line chart
  packages/perspective-viewer-d3fc/src/js/charts/xy-line.js
  packages/perspective-viewer-d3fc/test/js/integration/xy-line.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: cla-present

#2098 Updated README.md
  README.md
Labels: documentation

#2077 Update contributing guidelines
  .github/ISSUE_TEMPLATE/Support_question.md
  CONTRIBUTING.md
Labels: documentation, cla-present

#2113 Invert heatmap y-axis
  examples/blocks/src/movies/layout.json
  packages/perspective-viewer-d3fc/src/js/axis/axisFactory.js
  packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
  packages/perspective-viewer-d3fc/test/js/integration/area.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/barWidth.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/events.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/heatmap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/treemap.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/xy-line.spec.js
  packages/perspective-viewer-d3fc/test/js/integration/yscatter.spec.js
  packages/perspective-viewer-d3fc/test/results/results.json
Labels: bug, cla-present

#2111 New icons
  rust/perspective-viewer/src/svg/align-scroll-icon.svg
  rust/perspective-viewer/src/svg/bg-pattern.png
  rust/perspective-viewer/src/svg/boolean-type.svg
  rust/perspective-viewer/src/svg/checkbox-hover.svg
  rust/perspective-viewer/src/svg/checkbox-off.svg
  rust/perspective-viewer/src/svg/checkbox-on.svg
  rust/perspective-viewer/src/svg/column-settings-icon.svg
  rust/perspective-viewer/src/svg/date-type.svg
  rust/perspective-viewer/src/svg/drag-handle.svg
  rust/perspective-viewer/src/svg/drawer-bg-pattern-hidpi.png
  rust/perspective-viewer/src/svg/drawer-tab.svg
  rust/perspective-viewer/src/svg/dropdown-selector.svg
  rust/perspective-viewer/src/svg/duplicate-icon.svg
  rust/perspective-viewer/src/svg/editable-icon.svg
  rust/perspective-viewer/src/svg/export-icon.svg
  rust/perspective-viewer/src/svg/expression.svg
  rust/perspective-viewer/src/svg/free-scroll-icon.svg
  rust/perspective-viewer/src/svg/inactive-mouseover.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-candlestick.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-datagrid.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-heatmap.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-map-scatter.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-ohlc.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-sunburst.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-treemap.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-x-bar.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-x:y-line.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-x:y-scatter.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-y-area.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-y-bar.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-y-line.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-y-scatter.svg
  rust/perspective-viewer/src/svg/number-type.svg
  rust/perspective-viewer/src/svg/radio-hover.svg
  rust/perspective-viewer/src/svg/radio-off.svg
  rust/perspective-viewer/src/svg/radio-on.svg
  rust/perspective-viewer/src/svg/read-only-icon.svg
  rust/perspective-viewer/src/svg/revert-icon.svg
  rust/perspective-viewer/src/svg/sort-abs-asc-icon.svg
  rust/perspective-viewer/src/svg/sort-abs-col-asc-icon.svg
  rust/perspective-viewer/src/svg/sort-abs-col-desc-icon.svg
  rust/perspective-viewer/src/svg/sort-abs-desc-icon.svg
  rust/perspective-viewer/src/svg/sort-asc-icon.svg
  rust/perspective-viewer/src/svg/sort-col-asc-icon.svg
  rust/perspective-viewer/src/svg/sort-col-desc-icon.svg
  rust/perspective-viewer/src/svg/sort-desc-icon.svg
  rust/perspective-viewer/src/svg/sort-none-icon.svg
  rust/perspective-viewer/src/svg/string-type.svg
  rust/perspective-viewer/src/svg/theme-icon.svg
Labels: internal

#2118 fix icon filenames for windows
  rust/perspective-viewer/src/svg/mega-menu-icons-x-y-line.svg
  rust/perspective-viewer/src/svg/mega-menu-icons-x-y-scatter.svg
Labels: internal, cla-present

#2116 vendor all C++ dependencies at build time, fixes #2075, closes #2076,
  .github/workflows/build.yml
  cmake/modules/FindInstallDependency.cmake
  cpp/perspective/CMakeLists.txt
  python/perspective/bench/runtime/bench.py
  python/perspective/bench/runtime/perspective_benchmark.py
  python/perspective/perspective/client/websocket.py
  python/perspective/perspective/manager/manager_internal.py
  python/perspective/perspective/table/table.py
Labels: internal, C++, cla-present, dependencies
