Repository finos/perspective, pull requests merged in 2024-08, with the labels that each got.

#2702 Fix Python `sdist`, update docs, add `lint` to CI
  .github/actions/install-deps/action.yaml
  .github/workflows/build.yaml
  README.md
  docs/docs/development.md
  docs/docs/js.md
  docs/docs/python.md
  examples/rust-axum/src/main.rs
  package.json
  rust/perspective-client/docs/client.md
  rust/perspective-client/docs/client/system_info.md
  rust/perspective-client/docs/client/table.md
  rust/perspective-client/docs/table/get_client.md
  rust/perspective-client/docs/table/get_features.md
  rust/perspective-client/docs/view/get_config.md
  rust/perspective-client/src/rust/view.rs
  rust/perspective-js/package.json
  rust/perspective-python/Cargo.toml
  rust/perspective-python/bench/tornado/server/new_api.py
  rust/perspective-python/build.mjs
  rust/perspective-python/perspective/__init__.py
  rust/perspective-python/perspective/handlers/__init__.py
  rust/perspective-python/perspective/tests/conftest.py
  rust/perspective-python/perspective/tests/core/test_async.py
  rust/perspective-python/perspective/tests/server/test_server.py
  rust/perspective-python/perspective/tests/table/test_table.py
  rust/perspective-python/perspective/tests/table/test_table_datetime.py
  rust/perspective-python/perspective/tests/table/test_table_infer.py
  rust/perspective-python/perspective/tests/table/test_table_limit.py
  rust/perspective-python/perspective/tests/table/test_to_arrow.py
  rust/perspective-python/perspective/tests/table/test_to_arrow_lz4.py
  rust/perspective-python/perspective/tests/table/test_update_numpy.py
  rust/perspective-python/perspective/tests/table/test_view.py
  rust/perspective-python/perspective/tests/table/test_view_expression.py
  rust/perspective-python/perspective/tests/viewer/test_validate.py
  rust/perspective-python/perspective/widget/widget.py
  rust/perspective-python/pyproject.toml
  rust/perspective-viewer/docs.js
  rust/perspective-viewer/exprtk.md
  rust/perspective-viewer/package.json
  rust/perspective-viewer/src/rust/components/containers/sidebar.rs
  tools/perspective-scripts/docs.mjs
  tools/perspective-scripts/fix.mjs
  tools/perspective-scripts/fix_python.mjs
  tools/perspective-scripts/lint.mjs
  tools/perspective-scripts/lint_cpp.mjs
  tools/perspective-scripts/lint_python.mjs
  tools/perspective-scripts/repack_wheel.mjs
Labels: bug

#2701 Calculate `group_by` in parallel
  cpp/perspective/src/cpp/sparse_tree.cpp
Labels: enhancement

#2698 Draw 0 axis prominently
  packages/perspective-viewer-d3fc/src/ts/gridlines/gridlines.ts
Labels: enhancement

#2705 Fix Windows JupyterLab packaging
  .gitignore
  packages/perspective-jupyterlab/build.mjs
  packages/perspective-jupyterlab/package.json
  packages/perspective-jupyterlab/webpack.config.js
  pnpm-lock.yaml
  rust/perspective-python/build.mjs
  rust/perspective-python/perspective.data/data/share/jupyter/labextensions/@finos/perspective-jupyterlab/install.json
  rust/perspective-python/pyproject.toml
  tools/perspective-scripts/repack_wheel.mjs
Labels: bug

#2707 Add Pyodide support and split Rust/C++ builds for Python wheel
  .github/actions/install-deps/action.yaml
  .github/workflows/build.yaml
  .gitignore
  Cargo.lock
  Cargo.toml
  cpp/perspective/CMakeLists.txt
  cpp/perspective/src/cpp/binding_api.cpp
  cpp/perspective/src/cpp/emscripten_api.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/proto_api.cpp
  cpp/perspective/src/cpp/server.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/exprtk.h
  cpp/perspective/src/include/perspective/proto_api.h
  pnpm-lock.yaml
  rust-toolchain.toml
  rust/perspective-client/Cargo.toml
  rust/perspective-js/Cargo.toml
  rust/perspective-js/src/ts/emscripten_api.ts
  rust/perspective-js/src/ts/engine.ts
  rust/perspective-js/src/ts/perspective.ts
  rust/perspective-python/Cargo.toml
  rust/perspective-python/build.mjs
  rust/perspective-python/build/main.rs
  rust/perspective-python/build/psp.rs
  rust/perspective-python/package.json
  rust/perspective-python/perspective/__init__.py
  rust/perspective-python/perspective/psp_cffi.py
  rust/perspective-python/pyproject.toml
  rust/perspective-python/src/lib.rs
  rust/perspective-server/Cargo.toml
  rust/perspective-server/build/main.rs
  rust/perspective-server/build/psp.rs
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/rust/lib.rs
  tools/perspective-scripts/sh.mjs
Labels: enhancement

#2708 Update `docusaurus` website and examples
  .github/workflows/build.yaml
  .prettierignore
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/server.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/exprtk.h
  docs/docs/table.md
  docs/docs/view.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/components/Demo/layouts.js
  docs/src/components/DocItem/browser.js
  docs/src/components/DocItem/index.js
  examples/blocks/src/citibike/citibike.js
  examples/blocks/src/covid/index.html
  examples/blocks/src/fractal/index.js
  examples/blocks/src/magic/index.js
  examples/blocks/src/market/index.html
  examples/blocks/src/market/market.js
  examples/blocks/src/movies/index.html
  examples/blocks/src/olympics/index.html
  examples/blocks/src/webcam/index.html
  examples/blocks/src/webcam/webcam.js
  rust/perspective-client/docs/table/get_num_views.md
  rust/perspective-client/docs/table/replace.md
  rust/perspective-client/docs/table/update.md
  rust/perspective-client/docs/table/view.md
  rust/perspective-client/docs/view/remove_update.md
  rust/perspective-client/src/rust/table.rs
  rust/perspective-python/perspective/__init__.py
  rust/perspective-python/src/client/client_sync.rs
  rust/perspective-python/src/client/python.rs
  rust/perspective-python/src/lib.rs
  rust/perspective-viewer/build.rs
Labels: internal

#2712 Fix missing icons
  .github/workflows/build.yaml
  docs/docs/js.md
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/themes/icons.less
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/src/themes/solarized-dark.less
Labels: bug

#2713 Better Timestamp Parsing
  cpp/perspective/src/cpp/arrow_csv.cpp
  rust/perspective-js/src/ts/emscripten_api.ts
  rust/perspective-js/test/js/clear.spec.ts
  rust/perspective-js/test/js/constructors.spec.js
  tools/perspective-test/src/js/results.tar.gz
Labels: enhancement

#2700 Stringify Arrow lists
  cpp/perspective/src/cpp/arrow_loader.cpp
  rust/perspective-js/test/arrow/lists.arrow
  rust/perspective-js/test/js/constructors.spec.js
  rust/perspective-js/test/js/test_arrows.js
Labels: enhancement

#2690 fix: Doctype in html export
  rust/perspective-viewer/src/rust/model/export_app.rs
Labels: bug

#2720 Fix `PerspectiveTornadoHandler` misnamed `close()`
  rust/perspective-python/perspective/__init__.py
  rust/perspective-python/perspective/psp_cffi.py
  rust/perspective-python/perspective/tests/core/test_async.py
  rust/perspective-python/perspective/tests/server/test_server.py
  rust/perspective-python/perspective/tests/server/test_session.py
  rust/perspective-python/perspective/tests/table/test_table_pandas.py
  rust/perspective-python/perspective/viewer/viewer_traitlets.py
  rust/perspective-python/src/client/client_sync.rs
  rust/perspective-python/src/client/python.rs
  rust/perspective/src/lib.rs
Labels: bug

#2726 Fix link error in emscripten wheel
  cpp/perspective/src/cpp/vendor/arrow_single_threaded_reader.cpp
  cpp/perspective/src/include/perspective/vendor/arrow_single_threaded_reader.h
  packages/perspective-jupyterlab/test/jupyter/widget.spec.mts
  rust/perspective-server/build/main.rs
Labels: bug
