Repository finos/perspective, pull requests merged in 2024-11, with the labels that each got.

#2828 Fix `plugin` switch
  packages/perspective-jupyterlab/test/jupyter/widget.spec.mts
  packages/perspective-viewer-datagrid/src/js/model/toolbar.js
Labels: bug

#2831 Add back Table and View exports, make constructors throw like pyarrow.Table
  package.json
  rust/perspective-python/perspective/__init__.py
  rust/perspective-python/perspective/tests/table/test_exception.py
  rust/perspective-python/src/client/client_sync.rs
Labels: enhancement, Python

#2835 Fix concurrent update segfault
  cpp/perspective/src/cpp/pool.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/pool.h
  rust/perspective-python/perspective/tests/multi_threaded/__init__.py
  rust/perspective-python/perspective/tests/multi_threaded/test_multi_threaded.py
  rust/perspective-python/src/client/client_sync.rs
  rust/perspective-python/src/server/server_sync.rs
Labels: bug

#2833 Fixed workspace persistence structure symmetry
  packages/perspective-workspace/src/ts/workspace/commands.ts
  packages/perspective-workspace/src/ts/workspace/tabbar.ts
  packages/perspective-workspace/src/ts/workspace/widget.ts
  packages/perspective-workspace/src/ts/workspace/workspace.ts
  packages/perspective-workspace/test/js/restore.spec.js
  tools/perspective-test/results.tar.gz
Labels: bug

#2841 Import importlib metadata submodule
  rust/perspective-python/perspective/tests/viewer/test_validate.py
  rust/perspective-python/perspective/widget/__init__.py
  rust/perspective-python/perspective/widget/viewer/viewer_traitlets.py
Labels: bug

#2842 Fix `integer` cast expression function
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  packages/perspective-workspace/package.json
  pnpm-lock.yaml
  rust/perspective-js/test/js/expressions/numeric.spec.js
Labels: bug

#2851 Fix `perspective-workspace` restore call on errored table
  packages/perspective-viewer-datagrid/src/js/model/toolbar.js
  packages/perspective-workspace/test/js/table.spec.js
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/js/plugin.rs
  rust/perspective-viewer/src/rust/model/get_viewer_config.rs
  rust/perspective-viewer/src/rust/model/restore_and_render.rs
  rust/perspective-viewer/src/rust/renderer.rs
  tools/perspective-test/results.tar.gz
Labels: bug

#2849 Support input/output to/from polars via python (not native rust)
  rust/perspective-python/docs/client/to_pandas.md
  rust/perspective-python/docs/client/to_polars.md
  rust/perspective-python/docs/lib.md
  rust/perspective-python/perspective/tests/table/test_table_polars.py
  rust/perspective-python/requirements.txt
  rust/perspective-python/src/client/client_sync.rs
  rust/perspective-python/src/client/mod.rs
  rust/perspective-python/src/client/polars.rs
  rust/perspective-python/src/client/python.rs
Labels: enhancement

#2854 Fix empty Arrow `Table` constructor
  cpp/perspective/src/cpp/arrow_loader.cpp
  docs/src/components/DocItem/browser.js
  examples/blocks/src/raycasting/index.js
  packages/perspective-esbuild-plugin/index.js
  packages/perspective-esbuild-plugin/wasm.js
  packages/perspective-esbuild-plugin/worker.js
  rust/perspective-python/perspective/tests/table/test_table_arrow.py
  rust/perspective-python/src/client/client_sync.rs
  rust/perspective-python/src/server/server_sync.rs
Labels: bug

#2856 Add some information on JSON input formats
  rust/perspective-client/docs/table.md
Labels: internal, documentation

#2862 Remove `workspace-layout-update` event debounce
  examples/blocks/src/superstore/index.html
  packages/perspective-viewer-datagrid/src/less/row-hover.less
  packages/perspective-workspace/build.js
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/less/viewer.less
  packages/perspective-workspace/src/less/workspace.less
  packages/perspective-workspace/src/themes/pro-dark.less
  packages/perspective-workspace/src/themes/pro.less
  packages/perspective-workspace/src/ts/perspective-workspace.ts
  packages/perspective-workspace/src/ts/utils/custom_elements.ts
  packages/perspective-workspace/src/ts/workspace/commands.ts
  packages/perspective-workspace/src/ts/workspace/dockpanel.ts
  packages/perspective-workspace/src/ts/workspace/menu.ts
  packages/perspective-workspace/src/ts/workspace/tabbar.ts
  packages/perspective-workspace/src/ts/workspace/widget.ts
  packages/perspective-workspace/src/ts/workspace/workspace.ts
  packages/perspective-workspace/test/js/restore.spec.js
  rust/bundle/main.rs
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/config/viewer_config.rs
  rust/perspective-viewer/test/js/save_restore.spec.js
  tools/perspective-test/results.tar.gz
  tools/perspective-test/src/html/workspace-test.html
Labels: bug
