Repository finos/perspective, pull requests merged in 2024-12, with the labels that each got.

#2864 Fix workspace dark theme, theme render bug
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/themes/pro-dark.less
  packages/perspective-workspace/src/themes/pro.less
  packages/perspective-workspace/src/ts/workspace/commands.ts
  packages/perspective-workspace/src/ts/workspace/tabbar.ts
  packages/perspective-workspace/src/ts/workspace/widget.ts
  packages/perspective-workspace/src/ts/workspace/workspace.ts
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/presentation.rs
Labels: bug

#2829 Allow for passthrough of event loop in psp webserver handlers
  examples/python-starlette/server.py
  rust/perspective-python/perspective/handlers/aiohttp.py
  rust/perspective-python/perspective/handlers/starlette.py
  rust/perspective-python/perspective/handlers/tornado.py
Labels: bug, Python

#2872 Fix duplicate columns
  cpp/perspective/src/cpp/arrow_loader.cpp
  examples/python-tornado-streaming/server.py
  packages/perspective-workspace/src/less/menu.less
  packages/perspective-workspace/src/ts/workspace/workspace.ts
  rust/perspective-js/test/js/constructors.spec.js
Labels: bug

#2873 Support ndjson
  cpp/perspective/src/cpp/server.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/cpp/view.cpp
  cpp/perspective/src/include/perspective/server.h
  cpp/perspective/src/include/perspective/table.h
  cpp/perspective/src/include/perspective/view.h
  cpp/protos/perspective.proto
  rust/perspective-client/docs/table.md
  rust/perspective-client/docs/view/to_ndjson.md
  rust/perspective-client/src/rust/table.rs
  rust/perspective-client/src/rust/table_data.rs
  rust/perspective-client/src/rust/view.rs
  rust/perspective-js/src/rust/table.rs
  rust/perspective-js/src/rust/view.rs
  rust/perspective-js/test/js/constructors.spec.js
  rust/perspective-js/test/js/to_format.spec.js
  rust/perspective-python/src/client/client_sync.rs
  rust/perspective-python/src/client/python.rs
  rust/perspective-python/src/client/update_data.rs
  rust/perspective-viewer/src/rust/components/copy_dropdown.rs
  rust/perspective-viewer/src/rust/components/export_dropdown.rs
  rust/perspective-viewer/src/rust/model/copy_export.rs
  rust/perspective-viewer/src/rust/model/export_method.rs
  rust/perspective-viewer/src/rust/session.rs
Labels: enhancement

#2882 Fix memory corruption on filter text overflow
  cpp/perspective/src/cpp/scalar.cpp
  cpp/perspective/src/cpp/server.cpp
  cpp/perspective/src/include/perspective/scalar.h
  rust/perspective-js/test/js/filters.spec.js
Labels: bug

#2883 Fix `ViewConfig` serialization for internal arrow types
  cpp/perspective/src/cpp/server.cpp
  rust/perspective-js/test/arrow/float32.arrow
  rust/perspective-js/test/js/constructors.spec.js
  rust/perspective-js/test/js/filters.spec.js
  rust/perspective-js/test/js/test_arrows.js
Labels: bug

#2884 Add `min` and `max` aggregates for `date` and `datetime` columns
  cpp/perspective/src/cpp/sparse_tree.cpp
  rust/perspective-client/src/rust/config/aggregates.rs
  rust/perspective-js/test/js/pivots.spec.js
Labels: enhancement

#2886 Fix examples and cleanup CSS
  examples/blocks/src/dataset/index.html
  examples/blocks/src/market/market.js
  examples/python-tornado-streaming/index.html
  examples/python-tornado/client_server_editing.html
  examples/python-tornado/index.html
  examples/python-tornado/server_mode.html
  examples/webpack-example/src/index.js
  packages/perspective-viewer-datagrid/src/less/toolbar.less
  packages/perspective-workspace/src/svg/bookmark-icon.svg
  packages/perspective-workspace/src/svg/drag-handle.svg
  packages/perspective-workspace/src/themes/pro-dark.less
  packages/perspective-workspace/src/themes/pro.less
  rust/perspective-js/src/ts/perspective.node.ts
  rust/perspective-python/bench/runtime/benchmark-python.html
  rust/perspective-python/bench/runtime/benchmark_hosted.html
  rust/perspective-python/docs/lib.md
  rust/perspective-viewer/src/less/config-selector.less
  rust/perspective-viewer/src/less/plugin-selector.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/form/color_range_selector.rs
  rust/perspective-viewer/src/themes/icons.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/src/themes/vaporwave.less
Labels: internal
