Repository finos/perspective, pull requests merged in 2024-01, with the labels that each got.

#2486 Add column edit highlight to `perspective-viewer-datagrid`
  packages/perspective-viewer-datagrid/src/js/data_listener/format_cell.js
  packages/perspective-viewer-datagrid/src/js/plugin/activate.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/column_header.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/row-hover.less
  rust/perspective-viewer/Cargo.lock
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/attributes_tab.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/sidebar.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/column_style.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol/row_selector.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol/symbol_config.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol/symbol_pairs.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol/symbol_selector.rs
  rust/perspective-viewer/src/rust/components/containers/mod.rs
  rust/perspective-viewer/src/rust/components/containers/tab_list.rs
  rust/perspective-viewer/src/rust/components/string_column_style.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/dragdrop.rs
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/rust/model/plugin_config.rs
  rust/perspective-viewer/src/rust/presentation.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/view.rs
  rust/perspective-viewer/src/rust/utils/json.rs
  rust/perspective-viewer/src/rust/utils/mod.rs
  rust/perspective-viewer/src/rust/utils/pubsub.rs
  rust/perspective-viewer/src/rust/utils/scope.rs
  rust/perspective-viewer/src/rust/utils/tests/pubsub.rs
  rust/perspective-viewer/tasks/bundle/main.rs
  rust/perspective-viewer/test/js/column_settings/datagrid.spec.ts
  tools/perspective-test/results.tar.gz
  tools/perspective-test/src/js/models/column_settings.ts
  tools/perspective-test/src/js/models/page.ts
Labels: enhancement, cla-present

#2489 Fix datagrid cell pulse styling
  packages/perspective-viewer-datagrid/src/js/style_handlers/table_cell/cell_flash.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/table_cell/index.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/table_cell/numeric.js
  packages/perspective-viewer-datagrid/test/js/column_style.spec.js
  tools/perspective-test/load-viewer-csv.js
  tools/perspective-test/results.tar.gz
Labels: bug, cla-present

#2495 Fix output scrolling in Jupyter when `perspective-python` is installed
  packages/perspective-jupyterlab/src/less/index.less
Labels: bug

#2498 Fix datagrid scroll performance regression via `regular-table` upgrade
  packages/perspective-viewer-datagrid/package.json
  yarn.lock
Labels: bug, cla-present

#2505 Update `http-server` examples dependency
  examples/esbuild-example/package.json
  examples/promo/package.json
  examples/webpack-cross-origin/package.json
  examples/workspace-editing-python/package.json
  examples/workspace/package.json
  yarn.lock
Labels: internal, cla-present

#2482 Render table in the shadow DOM for `@finos/perspective-viewer-datagrid`
  examples/blocks/src/editable/index.html
  examples/blocks/src/magic/.gitignore
  examples/blocks/src/magic/index.css
  examples/blocks/src/magic/index.js
  examples/blocks/src/magic/mana_cost_utils.js
  packages/perspective-jupyterlab/test/js/resize.spec.js
  packages/perspective-jupyterlab/test/jupyter/utils.js
  packages/perspective-jupyterlab/test/jupyter/widget.spec.js
  packages/perspective-viewer-datagrid/index.d.ts
  packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
  packages/perspective-viewer-datagrid/src/js/data_listener/index.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/edit_click.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/header_click.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/sort.js
  packages/perspective-viewer-datagrid/src/js/model/create.js
  packages/perspective-viewer-datagrid/src/js/plugin/activate.js
  packages/perspective-viewer-datagrid/src/js/plugin/connected.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/column_header.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/editable.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/focus.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/table_cell/index.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/sub-cell-scroll.less
  packages/perspective-viewer-datagrid/test/js/column_style.spec.js
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  packages/perspective-viewer-openlayers/test/html/superstore.html
  python/perspective/perspective/templates/exported_widget.html.jinja
  python/perspective/perspective/widget/widget.py
  rust/perspective-viewer/test/js/migrate_viewer.spec.js
  tools/perspective-test/results.tar.gz
  tools/perspective-test/src/html/basic-test.html
  tools/perspective-test/src/html/superstore-test.html
  tools/perspective-test/src/html/themed-test.html
  tools/perspective-test/src/js/utils.ts
Labels: enhancement, cla-present
