Repository finos/perspective, pull requests merged in 2024-03, with the labels that each got.

#2562 Fix Candlestick & OHLC charts
  packages/perspective-viewer-d3fc/src/ts/data/ohlcData.ts
Labels: bug

#2547 Update Pyodide to version 0.25.0
  .github/workflows/build.yml
  vendor/pyodide/Emscripten.cmake
Labels: internal, cla-present

#2551 Fix get_hosted_table_names in Python client
  python/perspective/perspective/client/base.py
  python/perspective/perspective/tests/handlers/test_starlette_handler.py
Labels: bug, cla-present

#2572 Expression editor & filter UX updates
  rust/perspective-viewer/src/less/column-settings-panel.less
  rust/perspective-viewer/src/less/containers/split-panel.less
  rust/perspective-viewer/src/less/containers/tabs.less
  rust/perspective-viewer/src/less/expression-editor.less
  rust/perspective-viewer/src/less/filter-item.less
  rust/perspective-viewer/src/less/form/code-editor.less
  rust/perspective-viewer/src/less/viewer.less
  rust/perspective-viewer/src/rust/components/column_selector/filter_column.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/attributes_tab.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/sidebar.rs
  rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/stub.rs
  rust/perspective-viewer/src/rust/components/expression_editor.rs
  rust/perspective-viewer/src/rust/components/form/code_editor.rs
  rust/perspective-viewer/src/rust/components/style/style_cache.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/custom_elements/filter_dropdown.rs
  rust/perspective-viewer/src/rust/exprtk/tokenize.rs
  rust/perspective-viewer/src/rust/exprtk/tokenize/string.rs
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/svg/drawer-tab-hover.svg
  rust/perspective-viewer/src/svg/drawer-tab.svg
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/test/js/column_settings.spec.ts
  rust/perspective-viewer/test/js/column_settings/xy.spec.ts
  rust/perspective-viewer/test/js/regressions.spec.js
  tools/perspective-test/results.tar.gz
Labels: enhancement, cla-present

#2570 Fix compatibility with other MSVC versions by explicitly converting to string
  python/perspective/setup.py
Labels: bug, cla-present
