Repository finos/perspective, pull requests merged in 2025-05, with the labels that each got.

#2987 Nightly artifacts
  .github/actions/config/action.yaml
  .github/workflows/build.yaml
Labels: internal

#2989 Fix `ProxySession` message routing bug with Jupyter widget
  .cargo/config.toml
  Cargo.lock
  pnpm-lock.yaml
  rust/perspective-client/Cargo.toml
  rust/perspective-client/src/rust/client.rs
  rust/perspective-client/src/rust/utils/mod.rs
  rust/perspective-js/Cargo.toml
  rust/perspective-js/src/rust/utils/browser.rs
  rust/perspective-python/perspective/tests/server/test_session.py
  rust/perspective-python/src/client/proxy_session.rs
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/rust/components/form/debug.rs
  rust/perspective-viewer/src/rust/custom_events.rs
  rust/perspective-viewer/src/rust/utils/browser/blob.rs
  tools/perspective-bench/package.json
Labels: bug

#2990 Nightly versions
  .github/actions/install-deps/action.yaml
  .github/workflows/build.yaml
  README.md
  package.json
  pnpm-lock.yaml
  tools/perspective-scripts/lint_headers.mjs
  tools/perspective-scripts/publish.mjs
  tools/perspective-scripts/version.mjs
  tools/perspective-scripts/workspace.mjs
Labels: internal

#2998 Add `max by` and `min by` aggregates
  cpp/perspective/src/cpp/aggspec.cpp
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/config.cpp
  cpp/perspective/src/cpp/extract_aggregate.cpp
  cpp/perspective/src/cpp/sparse_tree.cpp
  cpp/perspective/src/cpp/view_config.cpp
  cpp/perspective/src/include/perspective/base.h
  packages/perspective-jupyterlab/build.mjs
  rust/perspective-client/src/rust/config/aggregates.rs
  rust/perspective-js/test/js/aggregates.spec.js
  rust/perspective-python/perspective/widget/__init__.py
  rust/perspective-viewer/src/less/aggregate-selector.less
  rust/perspective-viewer/src/rust/components/column_selector/aggregate_selector.rs
  rust/perspective-viewer/src/rust/components/containers/select.rs
  rust/perspective-viewer/src/rust/session/metadata.rs
  tools/perspective-scripts/version.mjs
Labels: enhancement

#3000 `<perspective-workspace>` toolbar fix
  packages/perspective-viewer-datagrid/package.json
  packages/perspective-viewer-datagrid/src/less/toolbar.less
  packages/perspective-workspace/src/themes/pro-dark.less
  packages/perspective-workspace/src/ts/perspective-workspace.ts
  packages/perspective-workspace/src/ts/workspace/widget.ts
  packages/perspective-workspace/src/ts/workspace/workspace.ts
  packages/perspective-workspace/test/js/restore.spec.js
  pnpm-lock.yaml
  rust/perspective-viewer/src/less/dom/select.less
  rust/perspective-viewer/src/less/form/code-editor.less
  rust/perspective-viewer/src/less/plugin-selector.less
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/rust/components/containers/select.rs
  rust/perspective-viewer/src/rust/components/status_bar.rs
  rust/perspective-viewer/src/rust/custom_events.rs
  rust/perspective-viewer/src/themes/pro-dark.less
  rust/perspective-viewer/src/themes/pro.less
  rust/perspective-viewer/src/themes/solarized-dark.less
  rust/perspective-viewer/test/js/events.spec.ts
  tools/perspective-test/results.tar.gz
  tools/perspective-test/src/js/utils.ts
Labels: internal
