Repository finos/perspective, pull requests merged in 2025-06, with the labels that each got.

#3003 New error UX
  Cargo.lock
  packages/perspective-workspace/test/js/table.spec.js
  rust/perspective-client/src/rust/client.rs
  rust/perspective-client/src/rust/utils/mod.rs
  rust/perspective-js/Cargo.toml
  rust/perspective-js/src/rust/client.rs
  rust/perspective-js/src/rust/table_data.rs
  rust/perspective-js/src/rust/utils/errors.rs
  rust/perspective-js/src/rust/utils/futures.rs
  rust/perspective-js/src/rust/utils/local_poll_loop.rs
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/rust/components/column_selector/inactive_column.rs
  rust/perspective-viewer/src/rust/components/error_message.rs
  rust/perspective-viewer/src/rust/components/plugin_selector.rs
  rust/perspective-viewer/src/rust/components/status_bar.rs
  rust/perspective-viewer/src/rust/components/status_indicator.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/model/restore_and_render.rs
  rust/perspective-viewer/src/rust/model/update_and_render.rs
  rust/perspective-viewer/src/rust/session.rs
  rust/perspective-viewer/src/rust/session/metadata.rs
  rust/perspective-viewer/test/js/settings.spec.js
Labels: enhancement, breaking

#3004 Fix Windows CI
  rust/perspective-client/build.rs
Labels: internal

#3005 Fix `perspective_viewer::restore` calls blurring
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/utils/browser/mod.rs
  rust/perspective-viewer/test/html/superstore_with_input.html
  rust/perspective-viewer/test/js/focus.spec.js
Labels: bug

#3006 Fix `to_arrow` thread safety
  cpp/perspective/src/cpp/view.cpp
  rust/perspective-python/perspective/tests/multi_threaded/test_multi_threaded.py
Labels: bug

#3014 Fix datagrid `abs` sorting on header click
  docs/md/how_to/javascript/plugin_settings.md
  packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/header_click.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/sort.js
  packages/perspective-viewer-datagrid/src/js/model/create.js
  packages/perspective-viewer-datagrid/src/js/plugin/draw.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/column_header.js
  packages/perspective-viewer-datagrid/src/js/style_handlers/table_cell/index.js
  packages/perspective-viewer-datagrid/src/less/regular_table.less
  packages/perspective-viewer-datagrid/src/less/row-hover.less
  tools/perspective-test/results.tar.gz
Labels: enhancement

#3016 Fix `max_by`, `min_by`, `max`, `min` aggregates with empty filter sets
  cpp/perspective/src/cpp/sparse_tree.cpp
  rust/perspective-js/test/js/aggregates.spec.js
Labels: bug

#3021 Fix typo in docs for replace_all
  rust/perspective-client/src/rust/config/expressions.rs
Labels: internal
