Repository finos/perspective, pull requests merged in 2025-03, with the labels that each got.

#2934 Shrink `d3fc` bundle
  cpp/perspective/CMakeLists.txt
  packages/perspective-cli/package.json
  packages/perspective-viewer-d3fc/build.js
  packages/perspective-viewer-d3fc/src/ts/axis/axisFactory.ts
  packages/perspective-viewer-d3fc/src/ts/axis/axisLabel.ts
  packages/perspective-viewer-d3fc/src/ts/axis/chartFactory.ts
  packages/perspective-viewer-d3fc/src/ts/axis/linearAxis.ts
  packages/perspective-viewer-d3fc/src/ts/axis/minBandwidth.ts
  packages/perspective-viewer-d3fc/src/ts/axis/ordinalAxis.ts
  packages/perspective-viewer-d3fc/src/ts/axis/splitterLabels.ts
  packages/perspective-viewer-d3fc/src/ts/axis/timeAxis.ts
  packages/perspective-viewer-d3fc/src/ts/axis/withoutTicks.ts
  packages/perspective-viewer-d3fc/src/ts/charts/area.ts
  packages/perspective-viewer-d3fc/src/ts/charts/bar.ts
  packages/perspective-viewer-d3fc/src/ts/charts/candlestick.ts
  packages/perspective-viewer-d3fc/src/ts/charts/column.ts
  packages/perspective-viewer-d3fc/src/ts/charts/line.ts
  packages/perspective-viewer-d3fc/src/ts/charts/ohlc.ts
  packages/perspective-viewer-d3fc/src/ts/charts/ohlcCandle.ts
  packages/perspective-viewer-d3fc/src/ts/charts/xy-line.ts
  packages/perspective-viewer-d3fc/src/ts/charts/y-scatter.ts
  packages/perspective-viewer-d3fc/src/ts/d3fc/axis/multi-axis.ts
  packages/perspective-viewer-d3fc/src/ts/d3fc/padding/hardLimitZero.ts
  packages/perspective-viewer-d3fc/src/ts/gridlines/gridlines.ts
  packages/perspective-viewer-d3fc/src/ts/legend/colorRangeLegend.ts
  packages/perspective-viewer-d3fc/src/ts/legend/scrollableLegend.ts
  packages/perspective-viewer-d3fc/src/ts/series/areaSeries.ts
  packages/perspective-viewer-d3fc/src/ts/series/barSeries.ts
  packages/perspective-viewer-d3fc/src/ts/series/categoryPointSeries.ts
  packages/perspective-viewer-d3fc/src/ts/series/heatmapSeries.ts
  packages/perspective-viewer-d3fc/src/ts/series/lineSeries.ts
  packages/perspective-viewer-d3fc/src/ts/series/ohlcCandleSeries.ts
  packages/perspective-viewer-d3fc/src/ts/series/pointSeriesCanvas.ts
  packages/perspective-viewer-d3fc/src/ts/series/xy-scatter/xyScatterSeries.ts
  packages/perspective-viewer-d3fc/src/ts/tooltip/nearbyTip.ts
  packages/perspective-viewer-openlayers/package.json
  pnpm-lock.yaml
  rust/perspective-js/src/ts/wasm/emscripten_api.ts
  rust/perspective-js/tsconfig.browser.json
  rust/perspective-viewer/tsconfig.json
Labels: internal

#2943 Fix segfault in Python webservers
  rust/perspective-python/Cargo.toml
  rust/perspective-python/perspective/tests/async/test_websocket_client.py
  rust/perspective-python/perspective/tests/multi_threaded/test_multi_threaded.py
  rust/perspective-python/src/client/client_async.rs
  rust/perspective-python/src/server/server_sync.rs
Labels: bug

#2948 Add `Client::on_hosted_tables_update`
  Cargo.lock
  cpp/perspective/src/cpp/server.cpp
  cpp/perspective/src/include/perspective/server.h
  cpp/protos/perspective.proto
  examples/blocks/src/editable/README.md
  examples/blocks/src/editable/index.html
  packages/perspective-workspace/src/ts/workspace/commands.ts
  rust/perspective-client/docs/client/on_hosted_tables_update.md
  rust/perspective-client/docs/client/remove_hosted_tables_update.md
  rust/perspective-client/docs/table/get_name.md
  rust/perspective-client/src/rust/client.rs
  rust/perspective-js/Cargo.toml
  rust/perspective-js/src/rust/client.rs
  rust/perspective-js/src/rust/lib.rs
  rust/perspective-js/src/rust/table.rs
  rust/perspective-js/src/ts/perspective.browser.ts
  rust/perspective-js/src/ts/perspective.node.ts
  rust/perspective-js/test/js/hosted_tables.spec.js
  rust/perspective-python/src/client/client_async.rs
  rust/perspective-python/src/client/client_sync.rs
  rust/perspective-server/src/local_client.rs
  rust/perspective-viewer/Cargo.toml
  rust/perspective-viewer/src/less/status-bar.less
  rust/perspective-viewer/src/rust/custom_elements/copy_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/export_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/ts/bootstrap.ts
Labels: enhancement

#2957 Fix date filters in perspective-{select,click} events
  cpp/perspective/src/cpp/server.cpp
  packages/perspective-viewer-datagrid/test/js/superstore.spec.js
  tools/perspective-test/assets/all_types_small_multi.arrow
  tools/perspective-test/load-viewer-all-types-small-multi-arrow.js
  tools/perspective-test/src/html/all-types-small-multi-arrow-test.html
  tools/perspective-test/src/js/simple_viewer_tests.ts
Labels: bug

#2960 Fix export-to-html in `perspective-viewer`
  rust/perspective-viewer/test/html/superstore-single-threaded.html
  rust/perspective-viewer/test/js/export_table.spec.ts
  tools/perspective-esbuild-plugin/worker.js
  tools/perspective-test/load-viewer-csv-single-threaded.js
  tools/perspective-test/src/js/start_test_server.ts
Labels: bug
