Repository finos/perspective, pull requests merged in 2025-04, with the labels that each got.

#2964 Update `limit` behavior to use incrementing `index` (fix `last_by_index` aggregate)
  .github/workflows/build.yaml
  cpp/perspective/build.js
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/binding_api.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/server.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/flat_traversal.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/parallel_for.h
  cpp/perspective/src/include/perspective/scalar.h
  rust/perspective-js/test/js/constructors.spec.js
  rust/perspective-js/test/js/expressions/multiple_views.spec.js
  rust/perspective-js/test/js/limit.spec.js
  rust/perspective-js/test/js/updates.spec.js
  rust/perspective-python/perspective/tests/table/test_table_limit.py
  rust/perspective-server/build/psp.rs
  tools/perspective-bench/cross_platform_suite.mjs
Labels: enhancement

#2971 Fix chart bug which rounds subsecond ticks
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/server.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/scalar.h
  packages/perspective-viewer-d3fc/src/ts/axis/axisLabel.ts
  packages/perspective-viewer-d3fc/src/ts/axis/ordinalAxis.ts
  packages/perspective-viewer-d3fc/src/ts/legend/filter.ts
  packages/perspective-viewer-d3fc/test/js/line.spec.ts
  tools/perspective-test/playwright.config.ts
  tools/perspective-test/results.tar.gz
Labels: bug

#2972 Fix parallel_for and cleanup commented out code.
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/include/perspective/parallel_for.h
Labels: internal

#2975 Add API for keyboard copy from `perspective-viewer-datagrid`
  packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
  packages/perspective-viewer-datagrid/src/js/data_listener/format_cell.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/click.js
  packages/perspective-viewer-datagrid/src/js/event_handlers/select_region.js
  packages/perspective-viewer-datagrid/src/js/model/create.js
  packages/perspective-viewer-datagrid/src/js/model/toolbar.js
  rust/perspective-client/src/rust/client.rs
  rust/perspective-client/src/rust/config/view_config.rs
  rust/perspective-client/src/rust/session.rs
  rust/perspective-client/src/rust/utils/clone.rs
  rust/perspective-client/src/rust/view.rs
  rust/perspective-js/src/rust/client.rs
  rust/perspective-js/src/rust/utils/console_logger.rs
  rust/perspective-js/src/rust/utils/futures.rs
  rust/perspective-python/src/client/client_async.rs
  rust/perspective-viewer/src/rust/components/copy_dropdown.rs
  rust/perspective-viewer/src/rust/components/export_dropdown.rs
  rust/perspective-viewer/src/rust/components/viewer.rs
  rust/perspective-viewer/src/rust/custom_elements/copy_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/export_dropdown.rs
  rust/perspective-viewer/src/rust/custom_elements/viewer.rs
  rust/perspective-viewer/src/rust/lib.rs
  rust/perspective-viewer/src/rust/model/copy_export.rs
  rust/perspective-viewer/src/rust/model/export_method.rs
  rust/perspective-viewer/src/rust/model/get_viewer_config.rs
  rust/perspective-viewer/src/rust/renderer.rs
  rust/perspective-viewer/src/rust/session.rs
Labels: enhancement

#2978 Fix support for browsers lacking the `SharedWorker` API
  .github/workflows/build.yaml
  rust/perspective-js/src/rust/utils/console_logger.rs
  rust/perspective-js/src/ts/wasm/browser.ts
  rust/perspective-js/test/js/workers.spec.js
  tools/perspective-bench/cross_platform_suite.mjs
Labels: bug

#2959 Add vscode settings to enable prettier
  .vscode/settings.default.json
  rust/perspective-viewer/README.md
Labels: internal

#2983 Fix `limit` overflow bug
  cpp/perspective/src/cpp/arrow_loader.cpp
  cpp/perspective/src/cpp/base.cpp
  cpp/perspective/src/cpp/binding_api.cpp
  cpp/perspective/src/cpp/context_zero.cpp
  cpp/perspective/src/cpp/data_table.cpp
  cpp/perspective/src/cpp/flat_traversal.cpp
  cpp/perspective/src/cpp/gnode.cpp
  cpp/perspective/src/cpp/gnode_state.cpp
  cpp/perspective/src/cpp/server.cpp
  cpp/perspective/src/cpp/table.cpp
  cpp/perspective/src/include/perspective/arrow_loader.h
  cpp/perspective/src/include/perspective/base.h
  cpp/perspective/src/include/perspective/data_table.h
  cpp/perspective/src/include/perspective/flat_traversal.h
  cpp/perspective/src/include/perspective/gnode.h
  cpp/perspective/src/include/perspective/gnode_state.h
  cpp/perspective/src/include/perspective/scalar.h
  cpp/perspective/src/include/perspective/server.h
  rust/perspective-js/src/ts/wasm/engine.ts
  rust/perspective-js/test/js/updates.spec.js
  rust/perspective-python/perspective/tests/table/test_table_limit.py
  rust/perspective-server/src/ffi.rs
  rust/perspective-server/src/local_session.rs
Labels: bug, breaking

#2986 Fix line chart alt Y axis on zoom
  packages/perspective-viewer-d3fc/build.js
  packages/perspective-viewer-d3fc/src/less/chart.less
  packages/perspective-viewer-d3fc/src/less/gradient_colors.less
  packages/perspective-viewer-d3fc/src/less/series_colors.less
  packages/perspective-viewer-d3fc/src/ts/axis/chartFactory.ts
  packages/perspective-viewer-d3fc/src/ts/axis/ordinalAxis.ts
  packages/perspective-viewer-d3fc/src/ts/charts/line.ts
  packages/perspective-viewer-d3fc/src/ts/series/colorStyles.ts
  packages/perspective-viewer-d3fc/test/js/line.spec.ts
  tools/perspective-test/results.tar.gz
Labels: bug
